0 0 dataAuditErrors
513 0 DEVICE Error: Illegal nmosh device
604 0 Not Qualified CPMIM device
616 0 DEVICE Error illegal element : CVAR_device RF not supported for this technology
937 0 INFO: unidentified diffusion = diff without implant, outside hv devices
1020 0 Process Modules : PHDPINB750 not available for this process module
1448 0 Illegal Device : nmos50ts not supported
1449 0 Illegal Device : nmos50ms not supported
1486 0 Illegal Device : nmos20ts not supported
1487 0 Illegal Device : nmos20ms not supported
1757 0 PMOSD20M INFO only : large device w > 200  gate split up
1758 0 PMOSD20T INFO only : large device w > 200  gate split up
1763 0 PMOSD20M INFO only : this device is identical with pmos20m with m-factor 1 , but with text pmosd20m on HVDEF layer
1768 0 PMOSD20T INFO only : this device is identical with pmos20t with m-factor 1 , but with text pmosd20t on HVDEF layer
1789 0 Illegal Device : pmos20ts not supported
1790 0 Illegal Device : pmos20ms not supported
1890 0 Illegal Device : pmos50ts not supported
1891 0 Illegal Device : pmos50ms not supported
1919 0 Illegal Device : pmos120t not supported
2007 0 Unsupported Device PMOSVS with HVOX
2009 0 Unsupported Device PMOSVS with MIDOX
2099 0 Unsupported Device PMOSDVS with HVOX
2101 0 Unsupported Device PMOSDVS with MIDOX
2316 0 NMOSDI20H INFO only : large device w > 200  gate split up
2317 0 NMOSDI20M INFO only : large device w > 200  gate split up
2488 0 Unsupported Device NMOSDIVS with MIDOX
2513 0 Unsupported Device NMOSDIVS with HVOX
2623 0 Unsupported Device NMOSIVS with MIDOX
2648 0 Unsupported Device NMOSIVS with HVOX
2691 0 Illegal Device: NMOSFI25T not supported
2692 0 Illegal Device: NMOSFI25M not supported
2723 0 Illegal Device: NMOSFI25MS not supported
2725 0 Illegal Device: NMOSFI25TS not supported
3572 0 Error: MET1 resistors (shorts) must be rectangular
3574 0 Error: Number of MET1 resistor terminals != 2
3576 0 Error: MET1 resistor def layer METRES touches CONT OR VIA1
3592 0 Error: MET2 resistors (shorts) must be rectangular
3594 0 Error: Number of MET2 resistor terminals != 2
3596 0 Error: MET2 resistor def layer METRES touches VIA1 or VIA2
3612 0 Error: MET3 resistors (shorts) must be rectangular
3614 0 Error: Number of MET3 resistor terminals != 2
3616 0 Error: MET3 resistor def layer METRES touches VIA2 or VIA3
3630 0 Error: MET4 resistors (shorts) must be rectangular
3632 0 Error: Number of MET4 resistor terminals != 2
3633 0 Error: MET4 resistor def layer METRES touches VIA3
3643 0 RVIA1 Definition layer: does not open all via connection, is shorted
3646 0 RVIA1 Definition layer: truncates via1, device shorted
3647 0 RVIA1 Definition layer: does not define a device
3651 0 RVIA1 Definition layer: over METRES
3658 0 RVIA2 Definition layer: does not open all via connection, is shorted
3661 0 RVIA2 Definition layer: truncates via2, device shorted
3662 0 RVIA2 Definition layer : does not define a device
3666 0 RVIA2 Definition layer: over METRES
3674 0 RVIA3 Definition layer: does not open all via connection, is shorted
3677 0 RVIA3 Definition layer: truncates via3, device shorted
3678 0 RVIA3 Definition layer : does not define a device
3682 0 RVIA3 Definition layer: over METRES
3827 0 ERROR : POLY1 pin outside poly1
3828 0 ERROR : MET1 pin outside met1
3829 0 ERROR : MET2 pin outside met2
3832 0 ERROR : MET3 pin outside met3
3834 0 ERROR : MET4 pin outside met4
3835 0 ERROR : PAD pin outside pad metal
3875 0 HVDEF_isoVoltage layer does not have any isoVoltage text
3878 0 HVDEF_isoType layer does not have any isoType text
3879 0 INFO : isotype_definition_type1
3880 0 INFO : isotype_definition_type2
3881 0 INFO : isovolt_definition_volt5
3882 0 INFO : isovolt_definition_volt20
3883 0 INFO : isovolt_definition_volt50
3884 0 INFO : isovolt_definition_volt120
3887 0  IsoVolt 50/120 overlaps definition layer for ISOVOLT
3888 0  IsoVolt 20/120 overlaps definition layer for ISOVOLT
3889 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
3890 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
3891 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
3892 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
3893 0  IsoType 1/2  overlaps definition layer for ISOTYPE
3959 0 CPMIM Error: cpmim must be totally inside POLY2
3960 0 CPMIM Error: cpoly must enclose cmim
3962 0 CPMIM Error: met3/poly1 plates of CPMIM not connected correctly
3964 0 CPMIM Error: met2/poly2 plates of CPMIM not connected correctly
3966 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
3968 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
3973 0 HVR001 : No HVDEF on CWPM
3974 0 HVR001 : Version of CWPM obsolete or missing
3975 0 HVR001 : HVDEF has illegal name on CWPM
3979 0 HVR001 : No HVDEF on VERTN1
3980 0 HVR001 : Version of VERTN1 obsolete or missing
3981 0 HVR001 : HVDEF has illegal name on VERTN1
3985 0 HVR001 : No HVDEF on VERTPH
3986 0 HVR001 : Version of VERTPH obsolete or missing
3987 0 HVR001 : HVDEF has illegal name on VERTPH
3991 0 HVR001 : No HVDEF on RPWELLR
3992 0 HVR001 : Version of RPWELLR obsolete or missing
3993 0 HVR001 : HVDEF has illegal name on RPWELLR
3997 0 HVR001 : No HVDEF on RNWELLS
3998 0 HVR001 : Version of RNWELLS obsolete or missing
3999 0 HVR001 : HVDEF has illegal name on RNWELLS
4003 0 HVR001 : No HVDEF on PJFET
4004 0 HVR001 : Version of PJFET obsolete or missing
4005 0 HVR001 : HVDEF has illegal name on PJFET
4015 0 HVR001 : No HVDEF on NMOS50T
4016 0 HVR001 : No HVDEF on NMOS50M
4017 0 HVR001 : No HVDEF on NMOS50H
4018 0 HVR001 : Version of NMOS50T obsolete or missing
4019 0 HVR001 : Version of NMOS50M obsolete or missing
4020 0 HVR001 : Version of NMOS50H obsolete or missing
4021 0 HVR001 : HVDEF has illegal name on NMOS50T
4022 0 HVR001 : HVDEF has illegal name on NMOS50M
4023 0 HVR001 : HVDEF has illegal name on NMOS50H
4033 0 HVR001 : No HVDEF on NMOS20T
4034 0 HVR001 : No HVDEF on NMOS20M
4035 0 HVR001 : No HVDEF on NMOS20H
4036 0 HVR001 : Version of NMOS20T obsolete or missing
4037 0 HVR001 : Version of NMOS20M obsolete or missing
4038 0 HVR001 : Version of NMOS20H obsolete or missing
4039 0 HVR001 : HVDEF has illegal name on NMOS20T
4040 0 HVR001 : HVDEF has illegal name on NMOS20M
4041 0 HVR001 : HVDEF has illegal name on NMOS20H
4069 0 NMOSD20M_R1: NMOSD20M source/bulk met1 must be connected together
4072 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4073 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4077 0 HVR001 : Version of NMOSD20M obsolete or missing
4078 0 HVR001 : HVDEF has illegal name on NMOSD20M
4082 0 HVR001 : No HVDEF on NMOS50HS
4083 0 HVR001 : Version of NMOS50HS obsolete or missing
4084 0 HVR001 : HVDEF has illegal name on NMOS50HS
4088 0 HVR001 : No HVDEF on NMOS20HS
4089 0 HVR001 : Version of NMOS20HS obsolete or missing
4090 0 HVR001 : HVDEF has illegal name on NMOS20HS
4100 0 HVR001 : No HVDEF on NMOSI50T
4101 0 HVR001 : No HVDEF on NMOSI50M
4102 0 HVR001 : No HVDEF on NMOSI50H
4103 0 HVR001 : Version of NMOSI50T obsolete or missing
4104 0 HVR001 : Version of NMOSI50M obsolete or missing
4105 0 HVR001 : Version of NMOSI50H obsolete or missing
4106 0 HVR001 : HVDEF has illegal name on NMOSI50T
4107 0 HVR001 : HVDEF has illegal name on NMOSI50M
4108 0 HVR001 : HVDEF has illegal name on NMOSI50H
4112 0 HVR001 : No HVDEF on NMOSDI50H
4113 0 HVR001 : Version of NMOSDI50H obsolete or missing
4114 0 HVR001 : HVDEF has illegal name on NMOSDI50H
4121 0 HVR001 : No HVDEF on NMOSDI20M
4122 0 HVR001 : No HVDEF on NMOSDI20H
4123 0 HVR001 : Version of NMOSDI20M obsolete or missing
4124 0 HVR001 : Version of NMOSDI20H obsolete or missing
4125 0 HVR001 : HVDEF has illegal name on NMOSDI20M
4126 0 HVR001 : HVDEF has illegal name on NMOSDI20H
4136 0 HVR001 : No HVDEF on NMOSI20T
4137 0 HVR001 : No HVDEF on NMOSI20M
4138 0 HVR001 : No HVDEF on NMOSI20H
4139 0 HVR001 : Version of NMOSI20T obsolete or missing
4140 0 HVR001 : Version of NMOSI20M obsolete or missing
4141 0 HVR001 : Version of NMOSI20H obsolete or missing
4142 0 HVR001 : HVDEF has illegal name on NMOSI20T
4143 0 HVR001 : HVDEF has illegal name on NMOSI20M
4144 0 HVR001 : HVDEF has illegal name on NMOSI20H
4151 0 HVR001 : Version of NMOSD10MH obsolete or missing
4152 0 HVR001 : Version of NMOS10MH obsolete or missing
4159 0 HVR001 : No HVDEF on NMOSI120M
4160 0 HVR001 : No HVDEF on NMOSI120H
4161 0 HVR001 : Version of NMOSI120M obsolete or missing
4162 0 HVR001 : Version of NMOSI120H obsolete or missing
4163 0 HVR001 : HVDEF has illegal name on NMOSI120M
4164 0 HVR001 : HVDEF has illegal name on NMOSI120H
4168 0 HVR001 : Version of ESDPMOS18T obsolete or missing
4176 0 INFO: PMOS20H ESD DEVICE REV3 for peri cells only
4180 0 HVR001 : No HVDEF on PMOS20H
4181 0 HVR001 : No HVDEF on PMOS20M
4182 0 HVR001 : No HVDEF on PMOS20H
4183 0 HVR001 : Version of PMOS20T obsolete or missing
4184 0 HVR001 : Version of PMOS20M obsolete or missing
4185 0 HVR001 : Version of PMOS20H obsolete or missing
4186 0 HVR001 : HVDEF has illegal name on PMOS20H
4190 0 HVR001 : HVDEF has illegal name on PMOS20M/PMOSD20M
4192 0 HVR001 : No HVDEF on PMOSD20M
4193 0 HVR001 : Version of PMOSD20M obsolete or missing
4194 0 HVR001 : HVDEF has illegal name on PMOSD20M
4198 0 HVR001 : HVDEF has illegal name on PMOS20T/PMOSD20T
4200 0 HVR001 : No HVDEF on PMOSD20T
4201 0 HVR001 : Version of PMOSD20T obsolete or missing
4202 0 HVR001 : HVDEF has illegal name on PMOSD20T
4233 0 PMOSD20M_R1/PMOSD20T_R1 : PMOSD20 source/bulk met1 must be connected together
4236 0 PMOSD20_R2: source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4237 0 PMOSD20M_R2/PMOSD20T_R2 : source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4241 0 HVR001 : No HVDEF on PMOS20HS
4242 0 HVR001 : Version of PMOS20HS obsolete or missing
4243 0 HVR001 : HVDEF has illegal name on PMOS20HS
4250 0 HVR001 : Version of PMOSD10MH obsolete or missing
4251 0 HVR001 : Version of PMOS10MH obsolete or missing
4261 0 HVR001 : No HVDEF on PMOS50T
4262 0 HVR001 : No HVDEF on PMOS50M
4263 0 HVR001 : No HVDEF on PMOS50H
4264 0 HVR001 : Version of PMOS50T obsolete or missing
4265 0 HVR001 : Version of PMOS50M obsolete or missing
4266 0 HVR001 : Version of PMOS50H obsolete or missing
4267 0 HVR001 : HVDEF has illegal name on PMOS50T
4268 0 HVR001 : HVDEF has illegal name on PMOS50M
4269 0 HVR001 : HVDEF has illegal name on PMOS50H
4273 0 HVR001 : No HVDEF on PMOS50HS
4274 0 HVR001 : Version of PMOS50HS obsolete or missing
4275 0 HVR001 : HVDEF has illegal name on PMOS50HS
4282 0 HVR001 : No HVDEF on PMOS120M
4283 0 HVR001 : No HVDEF on PMOS120H
4284 0 HVR001 : Version of PMOS120M obsolete or missing
4285 0 HVR001 : Version of PMOS120H obsolete or missing
4286 0 HVR001 : HVDEF has illegal name on PMOS120M
4287 0 HVR001 : HVDEF has illegal name on PMOS120H
4297 0 HVR001 : No HVDEF on NMOSFI25T
4298 0 HVR001 : No HVDEF on NMOSFI25M
4299 0 HVR001 : No HVDEF on NMOSFI25H
4300 0 HVR001 : Version of NMOSFI25T obsolete or missing
4301 0 HVR001 : Version of NMOSFI25M obsolete or missing
4302 0 HVR001 : Version of NMOSFI25H obsolete or missing
4303 0 HVR001 : HVDEF has illegal name on NMOSFI25T
4304 0 HVR001 : HVDEF has illegal name on NMOSFI25M
4305 0 HVR001 : HVDEF has illegal name on NMOSFI25H
4315 0 HVR001 : No HVDEF on NMOSFI25TS
4316 0 HVR001 : No HVDEF on NMOSFI25MS
4317 0 HVR001 : No HVDEF on NMOSFI25HS
4318 0 HVR001 : Version of NMOSFI25TS obsolete or missing
4319 0 HVR001 : Version of NMOSFI25MS obsolete or missing
4320 0 HVR001 : Version of NMOSFI25HS obsolete or missing
4321 0 HVR001 : HVDEF has illegal name on NMOSFI25TS
4322 0 HVR001 : HVDEF has illegal name on NMOSFI25MS
4323 0 HVR001 : HVDEF has illegal name on NMOSFI25HS
4327 0 HVR001 : Version of ESDGCI3 obsolete or missing
4328 0 HVR001 : HVDEF has illegal name on ESDGCI3
4335 0 ESDGCI3 connectivity error : emitter diff and emitter gate (poly ring) must be connected , common terminal E
4336 0 ESDGCI3 connectivity error : emitter diff and emitter dntub must be connected, common terminal E
4339 0 ESDGCI3 connectivity error :  emitter gate ( poly ring) and emitter dntub must be connected,  common terminal E
4343 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter met1 to met2, missing met2 connection or recommended via density too small < 25%
4354 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter ring met1 to met2, missing met2 connection or recommended via density too small  < 10% 
4360 0 ESDGCI3 connectivity problem : COLLECTOR : use as many via1 as possble to connect collector met1 to met2, missing met2 connection or recommended via density too small < 25 %
4364 0 HVR001 : Version of ESDNPN_PN3 obsolete or missing
4365 0 HVR001 : HVDEF has illegal name on ESDNPN_PN3
4376 0 ESDNPN_PN3_Y2 width MET1, not over COLLECTOR 0.7 u
4378 0 ESDNPN_PN3_E3 MET1 enclosure of CONT 0.25 u
4381 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (>)
4383 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (<)
4384 0 ESDNPN_PN3_Y1 NDIFF right angle corner 0.4 u
4387 0 ESDNPN_PN3_X8_X10 COLLECTOR-NDIFF/EMITTER-NDIFF width 1.2 u
4392 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4394 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4396 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (<)
4398 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (>)
4411 0 ESDNPN_PN3_X6 COLLECTOR_NDIFF to EMITTER_NDIFF spacing ( projected edges) 0.05 u
4421 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (>)
4422 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (<)
4424 0 ESDNPN_PN3_X2 NDIFF width 1.95u (<)
4425 0 ESDNPN_PN3_X2 NDIFF width 1.95u (>)
4431 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (enc)
4433 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (straddle)
4435 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (outside)
4436 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u
4447 0 ESDNPN_PN3_X11 MET1 width 3. u
4451 0 HVR001 : Version of ESDGCNI5 obsolete or missing
4452 0 HVR001 : HVDEF has illegal name on ESDGCNI5
4456 0 HVR001 : Version of ESDGCI20 obsolete or missing
4457 0 HVR001 : HVDEF has illegal name on ESDGCI20
4461 0 HVR001 : Version of ESDFDI50 obsolete or missing
4462 0 HVR001 : HVDEF has illegal name on ESDFDI50
4466 0 HVR001 : Version of ESDTD20 obsolete or missing
4467 0 HVR001 : HVDEF has illegal name on ESDTD20
4471 0 HVR001 : Version of ESDTD50 obsolete or missing
4472 0 HVR001 : HVDEF has illegal name on ESDTD50
4476 0 HVR001 : Version of ESDTD40 obsolete or missing
4477 0 HVR001 : HVDEF has illegal name on ESDTD40
4481 0 HVR001 : Version of ESDTD42 obsolete or missing
4482 0 HVR001 : HVDEF has illegal name on ESDTD42
4486 0 HVR001 : Version of ESDTD45 obsolete or missing
4487 0 HVR001 : HVDEF has illegal name on ESDTD45
4491 0 HVR001 : Version of ESDTD60 obsolete or missing
4492 0 HVR001 : HVDEF has illegal name on ESDTD60
4496 0 HVR001 : Version of ESDPD10 obsolete or missing
4497 0 HVR001 : HVDEF has illegal name on ESDPD10
4501 0 HVR001 : Version of ESDPD26 obsolete or missing
4502 0 HVR001 : HVDEF has illegal name on ESDPD26
4506 0 DEVICE : ESDFDI120 not implemented yet
4510 0 UNSUPPORTED DEVICE : ESDPD12
4514 0 HVR001 : Version of ESDPD18 obsolete or missing
4515 0 HVR001 : HVDEF has illegal name on ESDPD18
4519 0 HVR001 : Version of ESDPD30 obsolete or missing
4520 0 HVR001 : HVDEF has illegal name on ESDPD30
4524 0 HVR001 : Version of ESDGCPI5 obsolete or missing
4525 0 HVR001 : HVDEF has illegal name on ESDGCPI5
4529 0 HVR001 : Version of ESDFDNI5 obsolete or missing
4530 0 HVR001 : HVDEF has illegal name on ESDFDNI5
4534 0 HVR001 : Version of ESDFDPI5 obsolete or missing
4535 0 HVR001 : HVDEF has illegal name on ESDFDPI5
4539 0 HVR001 : Version of ESDGCN5 obsolete or missing
4540 0 HVR001 : HVDEF has illegal name on ESDGCN5
4544 0 HVR001 : Version of ESDGCP5 obsolete or missing
4545 0 HVR001 : HVDEF has illegal name on ESDGCP5
4549 0 HVR001 : Version of ESDFDP5 obsolete or missing
4550 0 HVR001 : HVDEF has illegal name on ESDFDP5
4554 0 HVR001 : Version of ESDFDN5 obsolete or missing
4555 0 HVR001 : HVDEF has illegal name on ESDFDN5
4559 0 HVR001 : Version of ESDPNP40 obsolete or missing
4560 0 HVR001 : HVDEF has illegal name on ESDPNP40
4564 0 HVR001 : Version of ESDPNP42 obsolete or missing
4565 0 HVR001 : HVDEF has illegal name on ESDPNP42
4586 0 HVR001 : Version of ESDSCR14_SN obsolete or missing
4587 0 HVR001 : HVDEF has illegal name on ESDSCR14_SN
4609 0 HVR001 : Version of ESDSCR55_SN obsolete or missing
4610 0 HVR001 : HVDEF has illegal name on ESDSCR55_SN
4623 0 Illegal Device : This ESD device is not supported ( no ESD_01/02/03/04/05/06)
4873 0 HVR001 : HVDEF does not enclose a valid HV-device, bad HVDEF or bad device
4880 0 HVR003_NMOS50_sources_must_be_connected_together
4890 0 HVR003_NMOS20_sources_must_be_connected_together
4899 0 HVR003_NMOS10MH_sources_must_be_connected_together
4908 0 HVR003_NMOSI50_sources_must_be_connected_together
4917 0 HVR003_NMOSDI50_sources_must_be_connected_together
4929 0 HVR003_NMOSFI25_sources_must_be_connected_together
4939 0 HVR003_NMOSI20_sources_must_be_connected_together
4949 0 HVR003_NMOSDI20_sources_must_be_connected_together
4958 0 HVR003_NMOSI120_sources_must_be_connected_together
4967 0 HVR003_PMOS50_sources_must_be_connected_together
4976 0 HVR003_PMOS20_sources_must_be_connected_together
4986 0 HVR003_ESDPMOS18T_sources_must_be_connected_together
4995 0 HVR003_PMOS120_sources_must_be_connected_together
5004 0 HVR003_PMOS10MH_sources_must_be_connected_together
5021 0 NMOSI20T_R1/NMOSI20M_R1/NMOSI20H_R1: Bulk and source must be connected with met1
5035 0 NMOSI50T_R1/NMOSI50M_R1/NMOSI50H_R1: Bulk and source must be connected with met1
5049 0 NMOSI120M_R1/NMOSI120H_R1: Bulk and source must be connected with met1
5062 0 NMOSDI20M_R1/NMOSDI20H_R1: Bulk and source must be connected with met1
5072 0 NMOSDI50H_R1: Bulk and source must be connected with met1
5095 0 NMOSD10MH_R1: Bulk and source must be connected with met1
5117 0 PMOSD10MH_R1: Bulk and source must be connected with met1
5293 0 HVDEF_IsoVoltage : nmosi device must be inside iso volt definition layer
5297 0 HVDEF_IsoType : nmosi device must be inside iso type definition layer
5321 0 HVDEF_IsoVoltage : nmosi device must be inside iso volt definition layer
5325 0 HVDEF_IsoType : nmosi device must be inside iso type definition layer
5349 0 HVDEF_IsoVoltage : pmosi device must be inside iso volt definition layer
5353 0 HVDEF_IsoType : pmosi device must be inside iso type definition layer
5377 0 HVDEF_IsoVoltage : pmosi device must be inside iso volt definition layer
5381 0 HVDEF_IsoType : pmosi device must be inside iso type definition layer
6560 0 HVDEF_IsoVoltage : rdiffps device must be inside iso volt definition layer
6564 0 HVDEF_IsoType : rdiffps device must be inside iso type definition layer
7480 0 PDI1N01S002_cath_StampErrorFloat
7481 0 PDI1N01S002_cath_StampErrorMult
7482 0 PDI1N01S002_cath_StampErrorConnect
7514 0 PDI1N13S002_cath_StampErrorFloat
7515 0 PDI1N13S002_cath_StampErrorMult
7516 0 PDI1N13S002_cath_StampErrorConnect
7649 0 HVDEF_IsoVoltage : dn_ps device must be inside iso volt definition layer
7653 0 HVDEF_IsoType : dn_ps device must be inside iso type definition layer
8246 0 esdscr14_sn_vio_StampErrorFloat
8247 0 esdscr14_sn_vio_StampErrorMult
8248 0 esdscr14_sn_vio_StampErrorConnect
8267 0 esdscr55_sn_vio_StampErrorFloat
8268 0 esdscr55_sn_vio_StampErrorMult
8269 0 esdscr55_sn_vio_StampErrorConnect
10840 0 # INFO: Don't use -resimulate_extracted- Switch for standard LVS but only for QRC! #
10841 0 # H35B4 ENG - 243 (Last updated 28-Mar-2025 00:09) #
11397 0 malformed device NMOSI_device_hv
11398 0 malformed device NMOSI_device_not_hv
11399 0 malformed device NMOSIM_device_hv
11400 0 malformed device NMOSIM_device_not_hv
11401 0 malformed device poa_nmos_waffle_2x
11402 0 malformed device poa_nmos_waffle_3x
11403 0 malformed device poa_nmos_waffle_4x
11404 0 malformed device poa_nmos_midox_waffle_2x
11405 0 malformed device poa_nmos_midox_waffle_3x
11406 0 malformed device poa_nmos_midox_waffle_4x
11407 0 malformed device NMOSH_device
11408 0 malformed device NMOSMH_device
11409 0 malformed device RPWELLR_device
11410 0 malformed device RNWELL_device
11411 0 malformed device RNWELLS_device
11412 0 malformed device RDIFFP_device
11413 0 malformed device RDIFFPS_device_hv
11414 0 malformed device RDIFFPS_device_not_hv
11415 0 malformed device RDIFFN_device
11416 0 malformed device RDIFFNR_device
11417 0 malformed device RPOLY2_PSUB_device
11418 0 malformed device RPOLY2_NTUB_device
11419 0 malformed device RPOLY2_PTUB_device
11420 0 malformed device RPOLY2PH_PSUB_device
11421 0 malformed device RPOLY2PH_PTUB_device
11422 0 malformed device RPOLY2PH_NTUB_device
11423 0 malformed device RPOLYH_PSUB_device
11424 0 malformed device RPOLYH_NTUB_device
11425 0 malformed device RPOLYH_PTUB_device
11426 0 malformed device RPOLY1_PSUB_device
11427 0 malformed device RPOLY1_NTUB_device
11428 0 malformed device RPOLY1_PTUB_device
11429 0 malformed device PFUSE_device
11430 0 malformed device LAT2_device
11431 0 malformed device VERT10_device
11432 0 malformed device VERTN1_device
11433 0 malformed device VERTPH_device
11434 0 malformed device PJFET_device
11435 0 malformed device CPOLY_PSUB_device
11436 0 malformed device CPOLY_NTUB_device
11437 0 malformed device CWPM_device
11438 0 malformed device CPM_device
11439 0 malformed device PROBE_device
11440 0 malformed device PDI1N01S002_device
11441 0 malformed device PDI1N13S002_device
11442 0 malformed device DN_PS_device_hv
11443 0 malformed device DN_PS_device_not_hv
11444 0 malformed device ESDGCI3_device
11445 0 malformed device ESDGCNI5_device
11446 0 malformed device ESDGCI20_device
11447 0 malformed device ESDVSD_device
11448 0 malformed device ESDVSS_device
11449 0 malformed device ESDFDI50_device
11450 0 malformed device ESDTD20_device
11451 0 malformed device ESDTD50_device
11452 0 malformed device ESDTD40_device
11453 0 malformed device ESDTD42_device
11454 0 malformed device ESDTD45_device
11455 0 malformed device ESDTD60_device
11456 0 malformed device ESDPD10_device
11457 0 malformed device ESDGCPI5_device
11458 0 malformed device ESDFDPI5_device
11459 0 malformed device ESDFDNI5_device
11460 0 malformed device ESDFDN5_device
11461 0 malformed device ESDGCN5_device
11462 0 malformed device ESDFDP5_device
11463 0 malformed device ESDGCP5_device
11464 0 malformed device ESDPNP40_device
11465 0 malformed device ESDPNP42_device
11466 0 malformed device ESDNPN_PN3_device
11467 0 malformed device ESDSCR14_SN_device
11468 0 malformed device ESDSCR55_SN_device
11469 0 malformed device NMOS50T_device
11470 0 malformed device NMOS50M_device
11471 0 malformed device NMOS50H_device
11472 0 malformed device NMOS50HS_device
11473 0 malformed device NMOSI50T_device
11474 0 malformed device NMOSI50M_device
11475 0 malformed device NMOSI50H_device
11476 0 malformed device NMOSI20H_device
11477 0 malformed device NMOSI20T_device
11478 0 malformed device NMOSI20M_device
11479 0 malformed device NMOS10MH_device
11480 0 malformed device NMOSD10MH_device
11481 0 malformed device NMOS20T_device
11482 0 malformed device NMOS20M_device
11483 0 malformed device NMOSD20M_device
11484 0 malformed device NMOS20H_device
11485 0 malformed device NMOS20HS_device
11486 0 malformed device NMOSDI20M_device
11487 0 malformed device NMOSDI20T_device
11488 0 malformed device NMOSDI20H_device
11489 0 malformed device NMOSDI50H_device
11490 0 malformed device NMOSDI50T_device
11491 0 malformed device NMOSI120H_device
11492 0 malformed device NMOSI120M_device
11493 0 malformed device NMOSDIVST_device
11494 0 malformed device NMOSIVST_device
11495 0 malformed device PMOS50T_device
11496 0 malformed device PMOS50M_device
11497 0 malformed device PMOS50H_device
11498 0 malformed device PMOS50HS_device
11499 0 malformed device PMOS10MH_device
11500 0 malformed device PMOSD10MH_device
11501 0 malformed device PMOS20H_device_rev4
11502 0 malformed device PMOS20H_device_rev3
11503 0 malformed device PMOS20T_device
11504 0 malformed device ESDPMOS18T_device
11505 0 malformed device PMOSD20T_device
11506 0 malformed device PMOS20M_device
11507 0 malformed device PMOSD20M_device
11508 0 malformed device PMOS20HS_device
11509 0 malformed device PMOS120H_device
11510 0 malformed device PMOS120M_device
11511 0 malformed device PMOSVST_device
11512 0 malformed device PMOSDVST_device
11513 0 malformed device HALL_XY12x12_Zx2_LN_device
11514 0 malformed device HALL_XY12x12_Zx2_STD_device
11515 0 malformed device HALL_XY8x8_Zx2_LN_device
11516 0 malformed device HALL_XY8x8_Zx2_STD_device
11517 0 malformed device HALL_C1_H35_device
11518 0 malformed device HALL_C1_H35X2_device
11519 0 malformed device HALL_C1_H35X4_device
11520 0 malformed device HALL_C2_H35_device
11521 0 malformed device HALL_C2_H35X2_device
11522 0 malformed device HALL_C2_H35X4_device
13090 0 unstable device for HALL_C2_H35X4_device_Device_185
13091 0 unpreserved device HALL_C2_H35X4_device_Device_185
13092 0 unstable device for HALL_C2_H35X2_device_Device_184
13093 0 unpreserved device HALL_C2_H35X2_device_Device_184
13094 0 unstable device for HALL_C2_H35_device_Device_183
13095 0 unpreserved device HALL_C2_H35_device_Device_183
13096 0 unstable device for HALL_C1_H35X4_device_Device_182
13097 0 unpreserved device HALL_C1_H35X4_device_Device_182
13098 0 unstable device for HALL_C1_H35X2_device_Device_181
13099 0 unpreserved device HALL_C1_H35X2_device_Device_181
13100 0 unstable device for HALL_C1_H35_device_Device_180
13101 0 unpreserved device HALL_C1_H35_device_Device_180
13102 0 unstable device for HALL_XY8x8_Zx2_STD_device_Device_179
13103 0 unpreserved device HALL_XY8x8_Zx2_STD_device_Device_179
13104 0 unstable device for HALL_XY8x8_Zx2_LN_device_Device_178
13105 0 unpreserved device HALL_XY8x8_Zx2_LN_device_Device_178
13106 0 unstable device for HALL_XY12x12_Zx2_STD_device_Device_177
13107 0 unpreserved device HALL_XY12x12_Zx2_STD_device_Device_177
13108 0 unstable device for HALL_XY12x12_Zx2_LN_device_Device_176
13109 0 unpreserved device HALL_XY12x12_Zx2_LN_device_Device_176
13110 0 unstable device for PMOSDVST_device_Device_175
13111 0 unpreserved device PMOSDVST_device_Device_175
13112 0 unstable device for PMOSVST_device_Device_174
13113 0 unpreserved device PMOSVST_device_Device_174
13114 0 unstable device for PMOS120M_device_Device_173
13115 0 unpreserved device PMOS120M_device_Device_173
13116 0 unstable device for PMOS120H_device_Device_172
13117 0 unpreserved device PMOS120H_device_Device_172
13118 0 unstable device for PMOS20HS_device_Device_171
13119 0 unpreserved device PMOS20HS_device_Device_171
13120 0 unstable device for PMOSD20M_device_Device_170
13121 0 unpreserved device PMOSD20M_device_Device_170
13122 0 unstable device for PMOS20M_device_Device_169
13123 0 unpreserved device PMOS20M_device_Device_169
13124 0 unstable device for PMOSD20T_device_Device_168
13125 0 unpreserved device PMOSD20T_device_Device_168
13126 0 unstable device for ESDPMOS18T_device_Device_167
13127 0 unpreserved device ESDPMOS18T_device_Device_167
13128 0 unstable device for PMOS20T_device_Device_166
13129 0 unpreserved device PMOS20T_device_Device_166
13130 0 unstable device for PMOS20H_device_rev3_Device_165
13131 0 unpreserved device PMOS20H_device_rev3_Device_165
13132 0 unstable device for PMOS20H_device_rev4_Device_164
13133 0 unpreserved device PMOS20H_device_rev4_Device_164
13134 0 unstable device for PMOSD10MH_device_Device_163
13135 0 unpreserved device PMOSD10MH_device_Device_163
13136 0 unstable device for PMOS10MH_device_Device_162
13137 0 unpreserved device PMOS10MH_device_Device_162
13138 0 unstable device for PMOS50HS_device_Device_161
13139 0 unpreserved device PMOS50HS_device_Device_161
13140 0 unstable device for PMOS50H_device_Device_160
13141 0 unpreserved device PMOS50H_device_Device_160
13142 0 unstable device for PMOS50M_device_Device_159
13143 0 unpreserved device PMOS50M_device_Device_159
13144 0 unstable device for PMOS50T_device_Device_158
13145 0 unpreserved device PMOS50T_device_Device_158
13146 0 unstable device for NMOSIVST_device_Device_157
13147 0 unpreserved device NMOSIVST_device_Device_157
13148 0 unstable device for NMOSDIVST_device_Device_156
13149 0 unpreserved device NMOSDIVST_device_Device_156
13150 0 unstable device for NMOSFI25HS_device_Device_155
13151 0 unpreserved device NMOSFI25HS_device_Device_155
13152 0 unstable device for NMOSFI25H_device_Device_154
13153 0 unpreserved device NMOSFI25H_device_Device_154
13154 0 unstable device for NMOSI120M_device_Device_153
13155 0 unpreserved device NMOSI120M_device_Device_153
13156 0 unstable device for NMOSI120H_device_Device_152
13157 0 unpreserved device NMOSI120H_device_Device_152
13158 0 unstable device for NMOSDI50T_device_Device_151
13159 0 unpreserved device NMOSDI50T_device_Device_151
13160 0 unstable device for NMOSDI50H_device_Device_150
13161 0 unpreserved device NMOSDI50H_device_Device_150
13162 0 unstable device for NMOSDI20H_device_Device_149
13163 0 unpreserved device NMOSDI20H_device_Device_149
13164 0 unstable device for NMOSDI20T_device_Device_148
13165 0 unpreserved device NMOSDI20T_device_Device_148
13166 0 unstable device for NMOSDI20M_device_Device_147
13167 0 unpreserved device NMOSDI20M_device_Device_147
13168 0 unstable device for NMOS20HS_device_Device_146
13169 0 unpreserved device NMOS20HS_device_Device_146
13170 0 unstable device for NMOS20H_device_Device_145
13171 0 unpreserved device NMOS20H_device_Device_145
13172 0 unstable device for NMOSD20M_device_Device_144
13173 0 unpreserved device NMOSD20M_device_Device_144
13174 0 unstable device for NMOS20M_device_Device_143
13175 0 unpreserved device NMOS20M_device_Device_143
13176 0 unstable device for NMOS20T_device_Device_142
13177 0 unpreserved device NMOS20T_device_Device_142
13178 0 unstable device for NMOSD10MH_device_Device_141
13179 0 unpreserved device NMOSD10MH_device_Device_141
13180 0 unstable device for NMOS10MH_device_Device_140
13181 0 unpreserved device NMOS10MH_device_Device_140
13182 0 unstable device for NMOSI20M_device_Device_139
13183 0 unpreserved device NMOSI20M_device_Device_139
13184 0 unstable device for NMOSI20T_device_Device_138
13185 0 unpreserved device NMOSI20T_device_Device_138
13186 0 unstable device for NMOSI20H_device_Device_137
13187 0 unpreserved device NMOSI20H_device_Device_137
13188 0 unstable device for NMOSI50H_device_Device_136
13189 0 unpreserved device NMOSI50H_device_Device_136
13190 0 unstable device for NMOSI50M_device_Device_135
13191 0 unpreserved device NMOSI50M_device_Device_135
13192 0 unstable device for NMOSI50T_device_Device_134
13193 0 unpreserved device NMOSI50T_device_Device_134
13194 0 unstable device for NMOS50HS_device_Device_133
13195 0 unpreserved device NMOS50HS_device_Device_133
13196 0 unstable device for NMOS50H_device_Device_132
13197 0 unpreserved device NMOS50H_device_Device_132
13198 0 unstable device for NMOS50M_device_Device_131
13199 0 unpreserved device NMOS50M_device_Device_131
13200 0 unstable device for NMOS50T_device_Device_130
13201 0 unpreserved device NMOS50T_device_Device_130
13202 0 unstable device for ESDSCR55_SN_device_Device_129
13203 0 unpreserved device ESDSCR55_SN_device_Device_129
13204 0 unstable device for ESDSCR14_SN_device_Device_128
13205 0 unpreserved device ESDSCR14_SN_device_Device_128
13206 0 unstable device for ESDNPN_PN3_device_Device_127
13207 0 unpreserved device ESDNPN_PN3_device_Device_127
13208 0 unstable device for ESDPNP42_device_Device_126
13209 0 unpreserved device ESDPNP42_device_Device_126
13210 0 unstable device for ESDPNP40_device_Device_125
13211 0 unpreserved device ESDPNP40_device_Device_125
13212 0 unstable device for ESDGCP5_device_Device_124
13213 0 unpreserved device ESDGCP5_device_Device_124
13214 0 unstable device for ESDFDP5_device_Device_123
13215 0 unpreserved device ESDFDP5_device_Device_123
13216 0 unstable device for ESDGCN5_device_Device_122
13217 0 unpreserved device ESDGCN5_device_Device_122
13218 0 unstable device for ESDFDN5_device_Device_121
13219 0 unpreserved device ESDFDN5_device_Device_121
13220 0 unstable device for ESDFDNI5_device_Device_120
13221 0 unpreserved device ESDFDNI5_device_Device_120
13222 0 unstable device for ESDFDPI5_device_Device_119
13223 0 unpreserved device ESDFDPI5_device_Device_119
13224 0 unstable device for ESDGCPI5_device_Device_118
13225 0 unpreserved device ESDGCPI5_device_Device_118
13226 0 unstable device for ESDPD30_device_Device_117
13227 0 unpreserved device ESDPD30_device_Device_117
13228 0 unstable device for ESDPD26_device_Device_116
13229 0 unpreserved device ESDPD26_device_Device_116
13230 0 unstable device for ESDPD18_device_Device_115
13231 0 unpreserved device ESDPD18_device_Device_115
13232 0 unstable device for ESDPD10_device_Device_114
13233 0 unpreserved device ESDPD10_device_Device_114
13234 0 unstable device for ESDTD60_device_Device_113
13235 0 unpreserved device ESDTD60_device_Device_113
13236 0 unstable device for ESDTD45_device_Device_112
13237 0 unpreserved device ESDTD45_device_Device_112
13238 0 unstable device for ESDTD42_device_Device_111
13239 0 unpreserved device ESDTD42_device_Device_111
13240 0 unstable device for ESDTD40_device_Device_110
13241 0 unpreserved device ESDTD40_device_Device_110
13242 0 unstable device for ESDTD50_device_Device_109
13243 0 unpreserved device ESDTD50_device_Device_109
13244 0 unstable device for ESDTD20_device_Device_108
13245 0 unpreserved device ESDTD20_device_Device_108
13246 0 unstable device for ESDFDI50_device_Device_107
13247 0 unpreserved device ESDFDI50_device_Device_107
13248 0 unstable device for ESDVSS_device_Device_106
13249 0 unpreserved device ESDVSS_device_Device_106
13250 0 unstable device for ESDVSD_device_Device_105
13251 0 unpreserved device ESDVSD_device_Device_105
13252 0 unstable device for ESDGCI20_device_Device_104
13253 0 unpreserved device ESDGCI20_device_Device_104
13254 0 unstable device for ESDGCNI5_device_Device_103
13255 0 unpreserved device ESDGCNI5_device_Device_103
13256 0 unstable device for ESDGCI3_device_Device_102
13257 0 unpreserved device ESDGCI3_device_Device_102
13258 0 unstable device for P_SN_PS_device_Device_101
13259 0 unpreserved device P_SN_PS_device_Device_101
13260 0 unstable device for SN_PS_device_Device_100
13261 0 unpreserved device SN_PS_device_Device_100
13262 0 unstable device for P_DN_PS_device_DIODE_99
13263 0 unpreserved device P_DN_PS_device_DIODE_99
13264 0 unstable device for DN_PS_device_not_hv_DIODE_98
13265 0 unpreserved device DN_PS_device_not_hv_DIODE_98
13266 0 unstable device for DN_PS_device_hv_DIODE_97
13267 0 unpreserved device DN_PS_device_hv_DIODE_97
13268 0 unstable device for P_DP_DN_device_DIODE_96
13269 0 unpreserved device P_DP_DN_device_DIODE_96
13270 0 unstable device for DP_DN_device_DIODE_95
13271 0 unpreserved device DP_DN_device_DIODE_95
13272 0 unstable device for P_PD_SN_device_DIODE_94
13273 0 unpreserved device P_PD_SN_device_DIODE_94
13274 0 unstable device for PD_SN_device_DIODE_93
13275 0 unpreserved device PD_SN_device_DIODE_93
13276 0 unstable device for P_ND_SP_device_DIODE_92
13277 0 unpreserved device P_ND_SP_device_DIODE_92
13278 0 unstable device for ND_SP_device_DIODE_91
13279 0 unpreserved device ND_SP_device_DIODE_91
13280 0 unstable device for PDI1N13S002_device_Device_90
13281 0 unpreserved device PDI1N13S002_device_Device_90
13282 0 unstable device for PDI1N01S002_device_Device_89
13283 0 unpreserved device PDI1N01S002_device_Device_89
13284 0 unstable device for PHDPINB750_device_Device_88
13285 0 unpreserved device PHDPINB750_device_Device_88
13286 0 unstable device for ZD2SM24_device_Device_87
13287 0 unpreserved device ZD2SM24_device_Device_87
13288 0 unstable device for P_NWD_device_DIODE_86
13289 0 unpreserved device P_NWD_device_DIODE_86
13290 0 unstable device for NWD_device_DIODE_85
13291 0 unpreserved device NWD_device_DIODE_85
13292 0 unstable device for P_PD_device_DIODE_84
13293 0 unpreserved device P_PD_device_DIODE_84
13294 0 unstable device for PD_device_DIODE_83
13295 0 unpreserved device PD_device_DIODE_83
13296 0 unstable device for P_ND_device_DIODE_82
13297 0 unpreserved device P_ND_device_DIODE_82
13298 0 unstable device for ND_device_DIODE_81
13299 0 unpreserved device ND_device_DIODE_81
13300 0 unstable device for CVARIM_device_Device_80
13301 0 unpreserved device CVARIM_device_Device_80
13302 0 unstable device for CVARM_device_Device_79
13303 0 unpreserved device CVARM_device_Device_79
13304 0 unstable device for CVART_device_Device_78
13305 0 unpreserved device CVART_device_Device_78
13306 0 unstable device for PROBE_device_Device_77
13307 0 unpreserved device PROBE_device_Device_77
13308 0 unstable device for CMIM20_device_Device_76
13309 0 unpreserved device CMIM20_device_Device_76
13310 0 unstable device for CMIM_device_Device_75
13311 0 unpreserved device CMIM_device_Device_75
13312 0 unstable device for CPM_device_CAP_74
13313 0 unpreserved device CPM_device_CAP_74
13314 0 unstable device for CWPM_device_CAP_73
13315 0 unpreserved device CWPM_device_CAP_73
13316 0 unstable device for CPOLY_NTUB_device_CAP_72
13317 0 unpreserved device CPOLY_NTUB_device_CAP_72
13318 0 unstable device for CPOLY_PSUB_device_CAP_71
13319 0 unpreserved device CPOLY_PSUB_device_CAP_71
13320 0 unstable device for PJFET_device_Device_70
13321 0 unpreserved device PJFET_device_Device_70
13322 0 unstable device for VERTPH_device_BJT_69
13323 0 unpreserved device VERTPH_device_BJT_69
13324 0 unstable device for VERTN1_device_BJT_68
13325 0 unpreserved device VERTN1_device_BJT_68
13326 0 unstable device for VERT10_device_BJT_67
13327 0 unpreserved device VERT10_device_BJT_67
13328 0 unstable device for LAT2_device_Device_66
13329 0 unpreserved device LAT2_device_Device_66
13330 0 unstable device for RVIA_PIN_PDIFF_Device_65
13331 0 unpreserved device RVIA_PIN_PDIFF_Device_65
13332 0 unstable device for RVIA_PIN_NDIFF_Device_64
13333 0 unpreserved device RVIA_PIN_NDIFF_Device_64
13334 0 unstable device for RVIA3_device_RES_63
13335 0 unpreserved device RVIA3_device_RES_63
13336 0 unstable device for RVIA2_device_RES_62
13337 0 unpreserved device RVIA2_device_RES_62
13338 0 unstable device for RVIA1_device_RES_61
13339 0 unpreserved device RVIA1_device_RES_61
13340 0 unstable device for RMET4_device_RES_60
13341 0 unpreserved device RMET4_device_RES_60
13342 0 unstable device for RMET3_device_RES_59
13343 0 unpreserved device RMET3_device_RES_59
13344 0 unstable device for RMET2_device_RES_58
13345 0 unpreserved device RMET2_device_RES_58
13346 0 unstable device for RMET1_device_RES_57
13347 0 unpreserved device RMET1_device_RES_57
13348 0 unstable device for PFUSE_device_RES_56
13349 0 unpreserved device PFUSE_device_RES_56
13350 0 unstable device for RPOLY1_PTUB_device_RES_55
13351 0 unpreserved device RPOLY1_PTUB_device_RES_55
13352 0 unstable device for RPOLY1_NTUB_device_RES_54
13353 0 unpreserved device RPOLY1_NTUB_device_RES_54
13354 0 unstable device for RPOLY1_PSUB_device_RES_53
13355 0 unpreserved device RPOLY1_PSUB_device_RES_53
13356 0 unstable device for RPOLYH_PTUB_device_RES_52
13357 0 unpreserved device RPOLYH_PTUB_device_RES_52
13358 0 unstable device for RPOLYH_NTUB_device_RES_51
13359 0 unpreserved device RPOLYH_NTUB_device_RES_51
13360 0 unstable device for RPOLYH_PSUB_device_RES_50
13361 0 unpreserved device RPOLYH_PSUB_device_RES_50
13362 0 unstable device for RPOLY2PH_NTUB_device_RES_49
13363 0 unpreserved device RPOLY2PH_NTUB_device_RES_49
13364 0 unstable device for RPOLY2PH_PTUB_device_RES_48
13365 0 unpreserved device RPOLY2PH_PTUB_device_RES_48
13366 0 unstable device for RPOLY2PH_PSUB_device_RES_47
13367 0 unpreserved device RPOLY2PH_PSUB_device_RES_47
13368 0 unstable device for RPOLY2P_NTUB_device_Device_46
13369 0 unpreserved device RPOLY2P_NTUB_device_Device_46
13370 0 unstable device for RPOLY2P_PTUB_device_Device_45
13371 0 unpreserved device RPOLY2P_PTUB_device_Device_45
13372 0 unstable device for RPOLY2P_PSUB_device_Device_44
13373 0 unpreserved device RPOLY2P_PSUB_device_Device_44
13374 0 unstable device for RPOLY2_PTUB_device_RES_43
13375 0 unpreserved device RPOLY2_PTUB_device_RES_43
13376 0 unstable device for RPOLY2_NTUB_device_RES_42
13377 0 unpreserved device RPOLY2_NTUB_device_RES_42
13378 0 unstable device for RPOLY2_PSUB_device_RES_41
13379 0 unpreserved device RPOLY2_PSUB_device_RES_41
13380 0 unstable device for RDIFFNR_device_Device_40
13381 0 unpreserved device RDIFFNR_device_Device_40
13382 0 unstable device for RDIFFN_device_RES_39
13383 0 unpreserved device RDIFFN_device_RES_39
13384 0 unstable device for RDIFFPS_device_not_hv_RES_38
13385 0 unpreserved device RDIFFPS_device_not_hv_RES_38
13386 0 unstable device for RDIFFPS_device_hv_RES_37
13387 0 unpreserved device RDIFFPS_device_hv_RES_37
13388 0 unstable device for RDIFFP_device_RES_36
13389 0 unpreserved device RDIFFP_device_RES_36
13390 0 unstable device for RNWELLS_device_RES_35
13391 0 unpreserved device RNWELLS_device_RES_35
13392 0 unstable device for RNWELL_device_RES_34
13393 0 unpreserved device RNWELL_device_RES_34
13394 0 unstable device for RPWELLR_device_RES_33
13395 0 unpreserved device RPWELLR_device_RES_33
13396 0 unstable device for NMOSMH_device_Device_32
13397 0 unpreserved device NMOSMH_device_Device_32
13398 0 unstable device for NMOSH_device_Device_31
13399 0 unpreserved device NMOSH_device_Device_31
13400 0 unstable device for poa_pmos_midox_waffle_4x_Device_30
13401 0 unpreserved device poa_pmos_midox_waffle_4x_Device_30
13402 0 unstable device for poa_pmos_midox_waffle_3x_Device_29
13403 0 unpreserved device poa_pmos_midox_waffle_3x_Device_29
13404 0 unstable device for poa_pmos_midox_waffle_2x_Device_28
13405 0 unpreserved device poa_pmos_midox_waffle_2x_Device_28
13406 0 unstable device for poa_pmos_waffle_4x_Device_27
13407 0 unpreserved device poa_pmos_waffle_4x_Device_27
13408 0 unstable device for poa_pmos_waffle_3x_Device_26
13409 0 unpreserved device poa_pmos_waffle_3x_Device_26
13410 0 unstable device for poa_pmos_waffle_2x_Device_25
13411 0 unpreserved device poa_pmos_waffle_2x_Device_25
13412 0 unstable device for poa_nmos_midox_waffle_4x_Device_24
13413 0 unpreserved device poa_nmos_midox_waffle_4x_Device_24
13414 0 unstable device for poa_nmos_midox_waffle_3x_Device_23
13415 0 unpreserved device poa_nmos_midox_waffle_3x_Device_23
13416 0 unstable device for poa_nmos_midox_waffle_2x_Device_22
13417 0 unpreserved device poa_nmos_midox_waffle_2x_Device_22
13418 0 unstable device for poa_nmos_waffle_4x_Device_21
13419 0 unpreserved device poa_nmos_waffle_4x_Device_21
13420 0 unstable device for poa_nmos_waffle_3x_Device_20
13421 0 unpreserved device poa_nmos_waffle_3x_Device_20
13422 0 unstable device for poa_nmos_waffle_2x_Device_19
13423 0 unpreserved device poa_nmos_waffle_2x_Device_19
13424 0 unstable device for PMOSSL_device_Device_18
13425 0 unpreserved device PMOSSL_device_Device_18
13426 0 unstable device for PMOSSML_device_Device_17
13427 0 unpreserved device PMOSSML_device_Device_17
13428 0 unstable device for PMOSIML_device_Device_16
13429 0 unpreserved device PMOSIML_device_Device_16
13430 0 unstable device for PMOSIM_device_not_hv_MOS_15
13431 0 unpreserved device PMOSIM_device_not_hv_MOS_15
13432 0 unstable device for PMOSIM_device_hv_MOS_14
13433 0 unpreserved device PMOSIM_device_hv_MOS_14
13434 0 unstable device for PMOSIL_device_Device_13
13435 0 unpreserved device PMOSIL_device_Device_13
13436 0 unstable device for PMOSI_device_not_hv_MOS_12
13437 0 unpreserved device PMOSI_device_not_hv_MOS_12
13438 0 unstable device for PMOSI_device_hv_MOS_11
13439 0 unpreserved device PMOSI_device_hv_MOS_11
13440 0 unstable device for NMOSIML_device_Device_10
13441 0 unpreserved device NMOSIML_device_Device_10
13442 0 unstable device for NMOSIM_device_not_hv_Device_9
13443 0 unpreserved device NMOSIM_device_not_hv_Device_9
13444 0 unstable device for NMOSIM_device_hv_Device_8
13445 0 unpreserved device NMOSIM_device_hv_Device_8
13446 0 unstable device for NMOSIL_device_Device_7
13447 0 unpreserved device NMOSIL_device_Device_7
13448 0 unstable device for NMOSI_device_not_hv_Device_6
13449 0 unpreserved device NMOSI_device_not_hv_Device_6
13450 0 unstable device for NMOSI_device_hv_Device_5
13451 0 unpreserved device NMOSI_device_hv_Device_5
13452 0 unstable device for PMOSM_device_MOS_4
13453 0 unpreserved device PMOSM_device_MOS_4
13454 0 unstable device for PMOS_device_MOS_3
13455 0 unpreserved device PMOS_device_MOS_3
13456 0 unstable device for NMOSM_device_MOS_2
13457 0 unpreserved device NMOSM_device_MOS_2
13458 0 unstable device for NMOS_device_MOS_1
13459 0 unpreserved device NMOS_device_MOS_1
