
// Generated by Cadence Genus(TM) Synthesis Solution 23.15-s099_1
// Generated on: Sep  2 2026 07:07:48 UTC (Sep  2 2026 07:07:48 UTC)

// Verification Directory fv/counter 

module counter(out, enable, clk, reset);
  input enable, clk, reset;
  output [7:0] out;
  wire enable, clk, reset;
  wire [7:0] out;
  wire n_1, n_3, n_4, n_5, n_6, n_8, n_9, n_10;
  wire n_11, n_13, n_14, n_15, n_16, n_18, n_19, n_20;
  wire n_21, n_23, n_24, n_25, n_26, n_28, n_29, n_30;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_43, n_49;
  wire n_55, n_61, n_67, n_73, n_79, n_85, \out[0]_58 , \out[1]_59 ;
  wire \out[2]_60 , \out[3]_61 , \out[4]_62 , \out[5]_63 , \out[6]_64 ,
       \out[7]_65 ;
  DFX1_DCV_HV \out_reg[7] (.CP (clk), .D (n_37), .Q (\out[7]_65 ), .QN
       (n_73));
  NOR2X4_DCV_HV g191__2398(.A (n_36), .B (reset), .Q (n_37));
  DFX1_DCV_HV \out_reg[6] (.CP (clk), .D (n_35), .Q (\out[6]_64 ), .QN
       (n_55));
  AOI22X4_DCV_HV g193__5107(.A1 (enable), .A2 (n_32), .B1 (n_33), .B2
       (\out[7]_65 ), .Q (n_36));
  NOR2X4_DCV_HV g194__6260(.A (n_34), .B (reset), .Q (n_35));
  DFX1_DCV_HV \out_reg[5] (.CP (clk), .D (n_30), .Q (\out[5]_63 ), .QN
       (n_61));
  AOI22X4_DCV_HV g195__4319(.A1 (enable), .A2 (n_29), .B1 (n_33), .B2
       (\out[6]_64 ), .Q (n_34));
  XOR2X1_DCV_HV g196__8428(.A (n_28), .B (\out[7]_65 ), .Q (n_32));
  NOR2X4_DCV_HV g199__5526(.A (n_26), .B (reset), .Q (n_30));
  HAX3_DCV_HV g198__6783(.A (\out[6]_64 ), .B (n_23), .CO (n_28), .SUM
       (n_29));
  DFX1_DCV_HV \out_reg[4] (.CP (clk), .D (n_25), .Q (\out[4]_62 ), .QN
       (n_67));
  AOI22X4_DCV_HV g200__3680(.A1 (enable), .A2 (n_24), .B1 (n_33), .B2
       (\out[5]_63 ), .Q (n_26));
  NOR2X4_DCV_HV g203__1617(.A (n_21), .B (reset), .Q (n_25));
  HAX3_DCV_HV g202__2802(.A (\out[5]_63 ), .B (n_18), .CO (n_23), .SUM
       (n_24));
  DFX1_DCV_HV \out_reg[3] (.CP (clk), .D (n_20), .Q (\out[3]_61 ), .QN
       (n_49));
  AOI22X4_DCV_HV g204__1705(.A1 (enable), .A2 (n_19), .B1 (n_33), .B2
       (\out[4]_62 ), .Q (n_21));
  NOR2X4_DCV_HV g207__5122(.A (n_16), .B (reset), .Q (n_20));
  HAX3_DCV_HV g206__8246(.A (\out[4]_62 ), .B (n_13), .CO (n_18), .SUM
       (n_19));
  AOI22X4_DCV_HV g208__7098(.A1 (enable), .A2 (n_14), .B1 (n_33), .B2
       (\out[3]_61 ), .Q (n_16));
  DFX1_DCV_HV \out_reg[2] (.CP (clk), .D (n_15), .Q (\out[2]_60 ), .QN
       (n_79));
  NOR2X4_DCV_HV g211__6131(.A (n_11), .B (reset), .Q (n_15));
  HAX3_DCV_HV g210__1881(.A (\out[3]_61 ), .B (n_8), .CO (n_13), .SUM
       (n_14));
  DFX1_DCV_HV \out_reg[1] (.CP (clk), .D (n_10), .Q (\out[1]_59 ), .QN
       (n_85));
  AOI22X4_DCV_HV g212__5115(.A1 (enable), .A2 (n_9), .B1 (n_33), .B2
       (\out[2]_60 ), .Q (n_11));
  NOR2X4_DCV_HV g215__7482(.A (n_6), .B (reset), .Q (n_10));
  HAX3_DCV_HV g214__4733(.A (\out[2]_60 ), .B (n_3), .CO (n_8), .SUM
       (n_9));
  DFX1_DCV_HV \out_reg[0] (.CP (clk), .D (n_5), .Q (\out[0]_58 ), .QN
       (n_43));
  AOI22X4_DCV_HV g216__6161(.A1 (enable), .A2 (n_4), .B1 (n_33), .B2
       (\out[1]_59 ), .Q (n_6));
  NOR2X4_DCV_HV g219__9315(.A (n_1), .B (reset), .Q (n_5));
  HAX3_DCV_HV g218__9945(.A (\out[1]_59 ), .B (\out[0]_58 ), .CO (n_3),
       .SUM (n_4));
  XNOR2X2_DCV_HV g220__2883(.A (\out[0]_58 ), .B (enable), .Q (n_1));
  INVX4_DCV_HV g229(.A (enable), .Q (n_33));
  INVX12_DCV_HV drc_bufs238(.A (n_43), .Q (out[0]));
  INVX12_DCV_HV drc_bufs244(.A (n_49), .Q (out[3]));
  INVX12_DCV_HV drc_bufs250(.A (n_55), .Q (out[6]));
  INVX12_DCV_HV drc_bufs256(.A (n_61), .Q (out[5]));
  INVX12_DCV_HV drc_bufs262(.A (n_67), .Q (out[4]));
  INVX12_DCV_HV drc_bufs268(.A (n_73), .Q (out[7]));
  INVX12_DCV_HV drc_bufs274(.A (n_79), .Q (out[2]));
  INVX12_DCV_HV drc_bufs280(.A (n_85), .Q (out[1]));
endmodule

