0 0 dataAuditErrors
268 0 ILL_ELEMENT_RPOLY2P Process Modules: RPOLY2P is not available
427 0 DEVICE Error: Illegal nmosh device
447 0 ILL_LAYER_LVTDEF Process Modules: LVTDEF is not available
511 0 ILL_LAYER_METCAP Process Modules: METCAP is not available
519 0 Not Qualified CPMIM device
531 0 DEVICE Error illegal element : CVAR_device RF not supported for this technology
590 0 INFO: Test or Probe pad < 70 * 70 U
628 0  INFO : standard pad met3 3 stack
630 0  INFO : standard pad met4 4 stack
635 0  INFO : POA pad met3 stack
637 0  INFO : POA pad met4 stack
877 0 INFO: unidentified diffusion = diff without implant, outside hv devices
919 0 ILL_ELEMENT_CMIM Process Modules: CMIM is not available
921 0 ILL_ELEMENT_CMIM20 Process Modules: CMIM20 is not available
965 0 Process Modules : PHDPINB750 not available for this process module
1355 0 Illegal Device : nmos50ts not supported
1356 0 Illegal Device : nmos50ms not supported
1396 0 Illegal Device : nmos20ts not supported
1397 0 Illegal Device : nmos20ms not supported
1741 0 PMOSD20M INFO only : large device w > 200  gate split up
1742 0 PMOSD20T INFO only : large device w > 200  gate split up
1747 0 PMOSD20M INFO only : this device is identical with pmos20m with m-factor 1 , but with text pmosd20m on HVDEF layer
1752 0 PMOSD20T INFO only : this device is identical with pmos20t with m-factor 1 , but with text pmosd20t on HVDEF layer
1774 0 Illegal Device : pmos20ts not supported
1775 0 Illegal Device : pmos20ms not supported
1876 0 Illegal Device : pmos50ts not supported
1877 0 Illegal Device : pmos50ms not supported
1906 0 Illegal Device : pmos120t not supported
2000 0 Unsupported Device PMOSVS with HVOX
2002 0 Unsupported Device PMOSVS with MIDOX
2098 0 Unsupported Device PMOSDVS with HVOX
2100 0 Unsupported Device PMOSDVS with MIDOX
2358 0 NMOSDI20H INFO only : large device w > 200  gate split up
2359 0 NMOSDI20M INFO only : large device w > 200  gate split up
2551 0 Unsupported Device NMOSDIVS with MIDOX
2586 0 Unsupported Device NMOSDIVS with HVOX
2718 0 Unsupported Device NMOSIVS with MIDOX
2753 0 Unsupported Device NMOSIVS with HVOX
2797 0 Illegal Device: NMOSFI25T not supported
2798 0 Illegal Device: NMOSFI25M not supported
2832 0 Illegal Device: NMOSFI25MS not supported
2834 0 Illegal Device: NMOSFI25TS not supported
3842 0 Error: MET1 resistors (shorts) must be rectangular
3844 0 Error: Number of MET1 resistor terminals != 2
3846 0 Error: MET1 resistor def layer METRES touches CONT OR VIA1
3864 0 Error: MET2 resistors (shorts) must be rectangular
3866 0 Error: Number of MET2 resistor terminals != 2
3868 0 Error: MET2 resistor def layer METRES touches VIA1 or VIA2
3886 0 Error: MET3 resistors (shorts) must be rectangular
3888 0 Error: Number of MET3 resistor terminals != 2
3890 0 Error: MET3 resistor def layer METRES touches VIA2 or VIA3
3906 0 Error: MET4 resistors (shorts) must be rectangular
3908 0 Error: Number of MET4 resistor terminals != 2
3909 0 Error: MET4 resistor def layer METRES touches VIA3
3919 0 RVIA1 Definition layer: does not open all via connection, is shorted
3922 0 RVIA1 Definition layer: truncates via1, device shorted
3923 0 RVIA1 Definition layer: does not define a device
3927 0 RVIA1 Definition layer: over METRES
3934 0 RVIA2 Definition layer: does not open all via connection, is shorted
3937 0 RVIA2 Definition layer: truncates via2, device shorted
3938 0 RVIA2 Definition layer : does not define a device
3942 0 RVIA2 Definition layer: over METRES
3950 0 RVIA3 Definition layer: does not open all via connection, is shorted
3953 0 RVIA3 Definition layer: truncates via3, device shorted
3954 0 RVIA3 Definition layer : does not define a device
3958 0 RVIA3 Definition layer: over METRES
3959 0 rmet1 INFO : rmet1 does not open met1 for drc
3960 0 rmet2 INFO : rmet2 does not open met2 for drc
3961 0 rmet3 INFO : rmet3 does not open met3 for drc
3962 0 rvia1 INFO : rvia1 does not open met1/2 for drc
3963 0 rvia2 INFO : rvia2 does not open met2/3 for drc
3964 0 rmet4 INFO : rmet4 does not open met4 for drc
3965 0 rvia3 INFO : rvia3 does not open met3/4 for drc
3982 0 ERROR : POLY1 pin outside poly1
3983 0 ERROR : MET1 pin outside met1
3984 0 ERROR : MET2 pin outside met2
3987 0 ERROR : MET3 pin outside met3
3989 0 ERROR : MET4 pin outside met4
3990 0 ERROR : PAD pin outside pad metal
4036 0 HVDEF_isoVoltage layer does not have any isoVoltage text
4039 0 HVDEF_isoType layer does not have any isoType text
4040 0 INFO : isotype_definition_type1
4041 0 INFO : isotype_definition_type2
4042 0 INFO : isovolt_definition_volt5
4043 0 INFO : isovolt_definition_volt20
4044 0 INFO : isovolt_definition_volt50
4045 0 INFO : isovolt_definition_volt120
4048 0  IsoVolt 50/120 overlaps definition layer for ISOVOLT
4049 0  IsoVolt 20/120 overlaps definition layer for ISOVOLT
4050 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
4051 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
4052 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
4053 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
4054 0  IsoType 1/2  overlaps definition layer for ISOTYPE
4075 0 BAD_NWELL_WELLTAP_FLOAT_ERC
4076 0 BAD_NWELL_WELLTAP_MULTCONN_ERC
4081 0 BAD_PWELL_WELLTAP_FLOAT_ERC
4082 0 BAD_PWELL_WELLTAP_MULTCONN_ERC
4091 0 BAD_SUBSTR_SUBTAP_FLOAT_ERC
4092 0 BAD_SUBSTR_SUBTAP_MULTCONN_ERC
4115 0 CPMIM Error: cpmim must be totally inside POLY2
4116 0 CPMIM Error: cpoly must enclose cmim
4119 0 CPMIM Error: met3/poly1 plates of CPMIM not connected correctly
4122 0 CPMIM Error: met2/poly2 plates of CPMIM not connected correctly
4125 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
4128 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
4129 0 INFO: any HVDEF used as isolation
4131 0 INFO: CWPM HVDEF
4133 0 HVR001 : No HVDEF on CWPM
4134 0 HVR001 : Version of CWPM obsolete or missing
4135 0 HVR001 : HVDEF has illegal name on CWPM
4137 0 INFO: VERTN1 HVDEF
4139 0 HVR001 : No HVDEF on VERTN1
4140 0 HVR001 : Version of VERTN1 obsolete or missing
4141 0 HVR001 : HVDEF has illegal name on VERTN1
4143 0 INFO: VERTPH HVDEF
4145 0 HVR001 : No HVDEF on VERTPH
4146 0 HVR001 : Version of VERTPH obsolete or missing
4147 0 HVR001 : HVDEF has illegal name on VERTPH
4149 0 INFO: RPWELLR HVDEF
4151 0 HVR001 : No HVDEF on RPWELLR
4152 0 HVR001 : Version of RPWELLR obsolete or missing
4153 0 HVR001 : HVDEF has illegal name on RPWELLR
4155 0 INFO: RNWELLS HVDEF
4157 0 HVR001 : No HVDEF on RNWELLS
4158 0 HVR001 : Version of RNWELLS obsolete or missing
4159 0 HVR001 : HVDEF has illegal name on RNWELLS
4161 0 INFO: PJFET HVDEF
4163 0 HVR001 : No HVDEF on PJFET
4164 0 HVR001 : Version of PJFET obsolete or missing
4165 0 HVR001 : HVDEF has illegal name on PJFET
4167 0 INFO: NMOS50T HVDEF
4169 0 INFO: NMOS50M HVDEF
4171 0 INFO: NMOS50H HVDEF
4175 0 HVR001 : No HVDEF on NMOS50T
4176 0 HVR001 : No HVDEF on NMOS50M
4177 0 HVR001 : No HVDEF on NMOS50H
4178 0 HVR001 : Version of NMOS50T obsolete or missing
4179 0 HVR001 : Version of NMOS50M obsolete or missing
4180 0 HVR001 : Version of NMOS50H obsolete or missing
4181 0 HVR001 : HVDEF has illegal name on NMOS50T
4182 0 HVR001 : HVDEF has illegal name on NMOS50M
4183 0 HVR001 : HVDEF has illegal name on NMOS50H
4185 0 INFO: NMOS20T HVDEF
4187 0 INFO: NMOS20M HVDEF
4189 0 INFO: NMOS20H HVDEF
4193 0 HVR001 : No HVDEF on NMOS20T
4194 0 HVR001 : No HVDEF on NMOS20M
4195 0 HVR001 : No HVDEF on NMOS20H
4196 0 HVR001 : Version of NMOS20T obsolete or missing
4197 0 HVR001 : Version of NMOS20M obsolete or missing
4198 0 HVR001 : Version of NMOS20H obsolete or missing
4199 0 HVR001 : HVDEF has illegal name on NMOS20T
4200 0 HVR001 : HVDEF has illegal name on NMOS20M
4201 0 HVR001 : HVDEF has illegal name on NMOS20H
4233 0 NMOSD20M_R1: NMOSD20M source/bulk met1 must be connected together
4236 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4237 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4239 0 INFO: NMOSD20M HVDEF
4241 0 HVR001 : Version of NMOSD20M obsolete or missing
4242 0 HVR001 : HVDEF has illegal name on NMOSD20M
4244 0 INFO: NMOS50HS HVDEF
4246 0 HVR001 : No HVDEF on NMOS50HS
4247 0 HVR001 : Version of NMOS50HS obsolete or missing
4248 0 HVR001 : HVDEF has illegal name on NMOS50HS
4250 0 INFO: NMOS20HS HVDEF
4252 0 HVR001 : No HVDEF on NMOS20HS
4253 0 HVR001 : Version of NMOS20HS obsolete or missing
4254 0 HVR001 : HVDEF has illegal name on NMOS20HS
4256 0 INFO: NMOSI50T HVDEF
4258 0 INFO: NMOSI50M HVDEF
4260 0 INFO: NMOSI50H HVDEF
4264 0 HVR001 : No HVDEF on NMOSI50T
4265 0 HVR001 : No HVDEF on NMOSI50M
4266 0 HVR001 : No HVDEF on NMOSI50H
4267 0 HVR001 : Version of NMOSI50T obsolete or missing
4268 0 HVR001 : Version of NMOSI50M obsolete or missing
4269 0 HVR001 : Version of NMOSI50H obsolete or missing
4270 0 HVR001 : HVDEF has illegal name on NMOSI50T
4271 0 HVR001 : HVDEF has illegal name on NMOSI50M
4272 0 HVR001 : HVDEF has illegal name on NMOSI50H
4274 0 INFO: NMOSDI50H HVDEF
4276 0 HVR001 : No HVDEF on NMOSDI50H
4277 0 HVR001 : Version of NMOSDI50H obsolete or missing
4278 0 HVR001 : HVDEF has illegal name on NMOSDI50H
4280 0 INFO: NMOSDI20M HVDEF
4282 0 INFO: NMOSDI20H HVDEF
4285 0 HVR001 : No HVDEF on NMOSDI20M
4286 0 HVR001 : No HVDEF on NMOSDI20H
4287 0 HVR001 : Version of NMOSDI20M obsolete or missing
4288 0 HVR001 : Version of NMOSDI20H obsolete or missing
4289 0 HVR001 : HVDEF has illegal name on NMOSDI20M
4290 0 HVR001 : HVDEF has illegal name on NMOSDI20H
4292 0 INFO: NMOSI20T HVDEF
4294 0 INFO: NMOSI20M HVDEF
4296 0 INFO: NMOSI20H HVDEF
4300 0 HVR001 : No HVDEF on NMOSI20T
4301 0 HVR001 : No HVDEF on NMOSI20M
4302 0 HVR001 : No HVDEF on NMOSI20H
4303 0 HVR001 : Version of NMOSI20T obsolete or missing
4304 0 HVR001 : Version of NMOSI20M obsolete or missing
4305 0 HVR001 : Version of NMOSI20H obsolete or missing
4306 0 HVR001 : HVDEF has illegal name on NMOSI20T
4307 0 HVR001 : HVDEF has illegal name on NMOSI20M
4308 0 HVR001 : HVDEF has illegal name on NMOSI20H
4310 0 INFO: NMOSD10MH HVDEF
4312 0 INFO: NMOS10MH HVDEF
4315 0 HVR001 : Version of NMOSD10MH obsolete or missing
4316 0 HVR001 : Version of NMOS10MH obsolete or missing
4318 0 INFO: NMOSI120M HVDEF
4320 0 INFO: NMOSI120H HVDEF
4323 0 HVR001 : No HVDEF on NMOSI120M
4324 0 HVR001 : No HVDEF on NMOSI120H
4325 0 HVR001 : Version of NMOSI120M obsolete or missing
4326 0 HVR001 : Version of NMOSI120H obsolete or missing
4327 0 HVR001 : HVDEF has illegal name on NMOSI120M
4328 0 HVR001 : HVDEF has illegal name on NMOSI120H
4330 0 INFO: ESDPMOS18T HVDEF
4332 0 HVR001 : Version of ESDPMOS18T obsolete or missing
4334 0 INFO: PMOS20T HVDEF
4336 0 INFO: PMOS20M HVDEF
4338 0 INFO: PMOS20H HVDEF
4340 0 INFO: PMOS20H ESD DEVICE REV3 for peri cells only
4344 0 HVR001 : No HVDEF on PMOS20H
4345 0 HVR001 : No HVDEF on PMOS20M
4346 0 HVR001 : No HVDEF on PMOS20H
4347 0 HVR001 : Version of PMOS20T obsolete or missing
4348 0 HVR001 : Version of PMOS20M obsolete or missing
4349 0 HVR001 : Version of PMOS20H obsolete or missing
4350 0 HVR001 : HVDEF has illegal name on PMOS20H
4352 0 INFO: PMOSD20M HVDEF
4354 0 HVR001 : HVDEF has illegal name on PMOS20M/PMOSD20M
4356 0 HVR001 : No HVDEF on PMOSD20M
4357 0 HVR001 : Version of PMOSD20M obsolete or missing
4358 0 HVR001 : HVDEF has illegal name on PMOSD20M
4360 0 INFO: PMOSD20T HVDEF
4362 0 HVR001 : HVDEF has illegal name on PMOS20T/PMOSD20T
4364 0 HVR001 : No HVDEF on PMOSD20T
4365 0 HVR001 : Version of PMOSD20T obsolete or missing
4366 0 HVR001 : HVDEF has illegal name on PMOSD20T
4401 0 PMOSD20M_R1/PMOSD20T_R1 : PMOSD20 source/bulk met1 must be connected together
4404 0 PMOSD20_R2: source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4405 0 PMOSD20M_R2/PMOSD20T_R2 : source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4407 0 INFO: PMOS20HS HVDEF
4409 0 HVR001 : No HVDEF on PMOS20HS
4410 0 HVR001 : Version of PMOS20HS obsolete or missing
4411 0 HVR001 : HVDEF has illegal name on PMOS20HS
4413 0 INFO: PMOSD10MH HVDEF
4415 0 INFO: PMOS10MH HVDEF
4418 0 HVR001 : Version of PMOSD10MH obsolete or missing
4419 0 HVR001 : Version of PMOS10MH obsolete or missing
4421 0 INFO: PMOS50T HVDEF
4423 0 INFO: PMOS50M HVDEF
4425 0 INFO: PMOS50H HVDEF
4429 0 HVR001 : No HVDEF on PMOS50T
4430 0 HVR001 : No HVDEF on PMOS50M
4431 0 HVR001 : No HVDEF on PMOS50H
4432 0 HVR001 : Version of PMOS50T obsolete or missing
4433 0 HVR001 : Version of PMOS50M obsolete or missing
4434 0 HVR001 : Version of PMOS50H obsolete or missing
4435 0 HVR001 : HVDEF has illegal name on PMOS50T
4436 0 HVR001 : HVDEF has illegal name on PMOS50M
4437 0 HVR001 : HVDEF has illegal name on PMOS50H
4439 0 INFO: PMOS50HS HVDEF
4441 0 HVR001 : No HVDEF on PMOS50HS
4442 0 HVR001 : Version of PMOS50HS obsolete or missing
4443 0 HVR001 : HVDEF has illegal name on PMOS50HS
4445 0 INFO: PMOS120M HVDEF
4447 0 INFO: PMOS120H HVDEF
4450 0 HVR001 : No HVDEF on PMOS120M
4451 0 HVR001 : No HVDEF on PMOS120H
4452 0 HVR001 : Version of PMOS120M obsolete or missing
4453 0 HVR001 : Version of PMOS120H obsolete or missing
4454 0 HVR001 : HVDEF has illegal name on PMOS120M
4455 0 HVR001 : HVDEF has illegal name on PMOS120H
4461 0 INFO: NMOSFI25H HVDEF
4465 0 HVR001 : No HVDEF on NMOSFI25T
4466 0 HVR001 : No HVDEF on NMOSFI25M
4467 0 HVR001 : No HVDEF on NMOSFI25H
4468 0 HVR001 : Version of NMOSFI25T obsolete or missing
4469 0 HVR001 : Version of NMOSFI25M obsolete or missing
4470 0 HVR001 : Version of NMOSFI25H obsolete or missing
4471 0 HVR001 : HVDEF has illegal name on NMOSFI25T
4472 0 HVR001 : HVDEF has illegal name on NMOSFI25M
4473 0 HVR001 : HVDEF has illegal name on NMOSFI25H
4479 0 INFO: NMOSFI25HS HVDEF
4483 0 HVR001 : No HVDEF on NMOSFI25TS
4484 0 HVR001 : No HVDEF on NMOSFI25MS
4485 0 HVR001 : No HVDEF on NMOSFI25HS
4486 0 HVR001 : Version of NMOSFI25TS obsolete or missing
4487 0 HVR001 : Version of NMOSFI25MS obsolete or missing
4488 0 HVR001 : Version of NMOSFI25HS obsolete or missing
4489 0 HVR001 : HVDEF has illegal name on NMOSFI25TS
4490 0 HVR001 : HVDEF has illegal name on NMOSFI25MS
4491 0 HVR001 : HVDEF has illegal name on NMOSFI25HS
4493 0 INFO: ESDGCI3 HVDEF
4495 0 HVR001 : Version of ESDGCI3 obsolete or missing
4496 0 HVR001 : HVDEF has illegal name on ESDGCI3
4503 0 ESDGCI3 connectivity error : emitter diff and emitter gate (poly ring) must be connected , common terminal E
4504 0 ESDGCI3 connectivity error : emitter diff and emitter dntub must be connected, common terminal E
4507 0 ESDGCI3 connectivity error :  emitter gate ( poly ring) and emitter dntub must be connected,  common terminal E
4511 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter met1 to met2, missing met2 connection or recommended via density too small < 25%
4523 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter ring met1 to met2, missing met2 connection or recommended via density too small  < 10% 
4530 0 ESDGCI3 connectivity problem : COLLECTOR : use as many via1 as possble to connect collector met1 to met2, missing met2 connection or recommended via density too small < 25 %
4532 0 INFO: ESDNPN_PN3 HVDEF
4534 0 HVR001 : Version of ESDNPN_PN3 obsolete or missing
4535 0 HVR001 : HVDEF has illegal name on ESDNPN_PN3
4553 0 ESDNPN_PN3_Y2 width MET1, not over COLLECTOR 0.7 u
4556 0 ESDNPN_PN3_E3 MET1 enclosure of CONT 0.25 u
4560 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (>)
4563 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (<)
4564 0 ESDNPN_PN3_Y1 NDIFF right angle corner 0.4 u
4568 0 ESDNPN_PN3_X8_X10 COLLECTOR-NDIFF/EMITTER-NDIFF width 1.2 u
4574 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4577 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4580 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (<)
4583 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (>)
4605 0 ESDNPN_PN3_X6 COLLECTOR_NDIFF to EMITTER_NDIFF spacing ( projected edges) 0.05 u
4619 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (>)
4621 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (<)
4624 0 ESDNPN_PN3_X2 NDIFF width 1.95u (<)
4626 0 ESDNPN_PN3_X2 NDIFF width 1.95u (>)
4633 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (enc)
4635 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (straddle)
4637 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (outside)
4638 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u
4654 0 ESDNPN_PN3_X11 MET1 width 3. u
4656 0 INFO: ESDGCNI5 HVDEF
4658 0 HVR001 : Version of ESDGCNI5 obsolete or missing
4659 0 HVR001 : HVDEF has illegal name on ESDGCNI5
4661 0 INFO: ESDGCI20 HVDEF
4663 0 HVR001 : Version of ESDGCI20 obsolete or missing
4664 0 HVR001 : HVDEF has illegal name on ESDGCI20
4666 0 INFO: ESDFDI50 HVDEF
4668 0 HVR001 : Version of ESDFDI50 obsolete or missing
4669 0 HVR001 : HVDEF has illegal name on ESDFDI50
4671 0 INFO: ESDTD20 HVDEF
4673 0 HVR001 : Version of ESDTD20 obsolete or missing
4674 0 HVR001 : HVDEF has illegal name on ESDTD20
4676 0 INFO: ESDTD50 HVDEF
4678 0 HVR001 : Version of ESDTD50 obsolete or missing
4679 0 HVR001 : HVDEF has illegal name on ESDTD50
4681 0 INFO: ESDTD40 HVDEF
4683 0 HVR001 : Version of ESDTD40 obsolete or missing
4684 0 HVR001 : HVDEF has illegal name on ESDTD40
4686 0 INFO: ESDTD42 HVDEF
4688 0 HVR001 : Version of ESDTD42 obsolete or missing
4689 0 HVR001 : HVDEF has illegal name on ESDTD42
4691 0 INFO: ESDTD45 HVDEF
4693 0 HVR001 : Version of ESDTD45 obsolete or missing
4694 0 HVR001 : HVDEF has illegal name on ESDTD45
4696 0 INFO: ESDTD60 HVDEF
4698 0 HVR001 : Version of ESDTD60 obsolete or missing
4699 0 HVR001 : HVDEF has illegal name on ESDTD60
4701 0 INFO: ESDPD10 HVDEF
4703 0 HVR001 : Version of ESDPD10 obsolete or missing
4704 0 HVR001 : HVDEF has illegal name on ESDPD10
4706 0 INFO: ESDPD26 HVDEF
4708 0 HVR001 : Version of ESDPD26 obsolete or missing
4709 0 HVR001 : HVDEF has illegal name on ESDPD26
4711 0 INFO: ESDFDI120 HVDEF .. Device not implemented
4713 0 DEVICE : ESDFDI120 not implemented yet
4715 0 INFO UNSUPPORTED : ESDPD12 HVDEF
4717 0 UNSUPPORTED DEVICE : ESDPD12
4719 0 INFO: ESDPD18 HVDEF
4721 0 HVR001 : Version of ESDPD18 obsolete or missing
4722 0 HVR001 : HVDEF has illegal name on ESDPD18
4724 0 INFO: ESDPD30 HVDEF
4726 0 HVR001 : Version of ESDPD30 obsolete or missing
4727 0 HVR001 : HVDEF has illegal name on ESDPD30
4729 0 INFO: ESDGCPI5 HVDEF
4731 0 HVR001 : Version of ESDGCPI5 obsolete or missing
4732 0 HVR001 : HVDEF has illegal name on ESDGCPI5
4734 0 INFO: ESDFDNI5 HVDEF
4736 0 HVR001 : Version of ESDFDNI5 obsolete or missing
4737 0 HVR001 : HVDEF has illegal name on ESDFDNI5
4739 0 INFO: ESDFDPI5 HVDEF
4741 0 HVR001 : Version of ESDFDPI5 obsolete or missing
4742 0 HVR001 : HVDEF has illegal name on ESDFDPI5
4744 0 INFO: ESDGCN5 HVDEF
4746 0 HVR001 : Version of ESDGCN5 obsolete or missing
4747 0 HVR001 : HVDEF has illegal name on ESDGCN5
4749 0 INFO: ESDGCP5 HVDEF
4751 0 HVR001 : Version of ESDGCP5 obsolete or missing
4752 0 HVR001 : HVDEF has illegal name on ESDGCP5
4754 0 INFO: ESDFDP5 HVDEF
4756 0 HVR001 : Version of ESDFDP5 obsolete or missing
4757 0 HVR001 : HVDEF has illegal name on ESDFDP5
4759 0 INFO: ESDFDN5 HVDEF
4761 0 HVR001 : Version of ESDFDN5 obsolete or missing
4762 0 HVR001 : HVDEF has illegal name on ESDFDN5
4764 0 INFO: ESDPNP40 HVDEF
4766 0 HVR001 : Version of ESDPNP40 obsolete or missing
4767 0 HVR001 : HVDEF has illegal name on ESDPNP40
4769 0 INFO: ESDPNP42 HVDEF
4771 0 HVR001 : Version of ESDPNP42 obsolete or missing
4772 0 HVR001 : HVDEF has illegal name on ESDPNP42
4795 0 INFO: ESDSCR14_SN HVDEF
4797 0 HVR001 : Version of ESDSCR14_SN obsolete or missing
4798 0 HVR001 : HVDEF has illegal name on ESDSCR14_SN
4821 0 INFO: ESDSCR55_SN HVDEF
4823 0 HVR001 : Version of ESDSCR55_SN obsolete or missing
4824 0 HVR001 : HVDEF has illegal name on ESDSCR55_SN
4825 0 INFO : HVDEF for ESD Device 01 (device not extracted)
4826 0 INFO : HVDEF for ESD Device 02 (device not extracted)
4827 0 INFO : HVDEF for ESD Device 03 (device not extracted)
4828 0 INFO : HVDEF for ESD Device 04 (device not extracted)
4829 0 INFO : HVDEF for ESD Device 05 (device not extracted)
4830 0 INFO : HVDEF for ESD Device 06 (device not extracted)
4837 0 Illegal Device : This ESD device is not supported ( no ESD_01/02/03/04/05/06)
5083 0 HVR001 : HVDEF does not enclose a valid HV-device, bad HVDEF or bad device
5092 0 HVR003_NMOS50_sources_must_be_connected_together
5104 0 HVR003_NMOS20_sources_must_be_connected_together
5115 0 HVR003_NMOS10MH_sources_must_be_connected_together
5126 0 HVR003_NMOSI50_sources_must_be_connected_together
5137 0 HVR003_NMOSDI50_sources_must_be_connected_together
5151 0 HVR003_NMOSFI25_sources_must_be_connected_together
5163 0 HVR003_NMOSI20_sources_must_be_connected_together
5175 0 HVR003_NMOSDI20_sources_must_be_connected_together
5186 0 HVR003_NMOSI120_sources_must_be_connected_together
5197 0 HVR003_PMOS50_sources_must_be_connected_together
5208 0 HVR003_PMOS20_sources_must_be_connected_together
5220 0 HVR003_ESDPMOS18T_sources_must_be_connected_together
5231 0 HVR003_PMOS120_sources_must_be_connected_together
5242 0 HVR003_PMOS10MH_sources_must_be_connected_together
5260 0 NMOSI20T_R1/NMOSI20M_R1/NMOSI20H_R1: Bulk and source must be connected with met1
5275 0 NMOSI50T_R1/NMOSI50M_R1/NMOSI50H_R1: Bulk and source must be connected with met1
5290 0 NMOSI120M_R1/NMOSI120H_R1: Bulk and source must be connected with met1
5304 0 NMOSDI20M_R1/NMOSDI20H_R1: Bulk and source must be connected with met1
5315 0 NMOSDI50H_R1: Bulk and source must be connected with met1
5319 0 ERC Warning: NMOS50 iso pwell not connected to source of nmos50
5323 0 ERC Warning: NMOS20 iso pwell not connected to source of nmos20
5327 0 ERC Warning: NMOS10MH iso pwell not connected to source of nmos10mh20
5354 0 NMOSD10MH_R1: Bulk and source must be connected with met1
5380 0 PMOSD10MH_R1: Bulk and source must be connected with met1
5450 0 NMOS50T/NMOS50M L Element Rule : Min gate length = 0.5 U
5451 0 NMOS50H L Element Rule : Min gate length = 1 U
5452 0 NMOS50T/M/H W2 Element Rule : Min gate width/2 = 5 U
5461 0 NMOS50T/M/H X1/Y1 Element Rule : drain sntub ovlp of drain diff 0.4 U fixed
5468 0 NMOS50T/M/H  X2 Element Rule : ntub stripe spacing to drain diff 0.45 U fixed
5480 0 NMOS50T/NMOS50M X4 Element Rule : ntub stripe width 1.5 U fixed
5487 0 NMOS50H X4 Element Rule : ntub stripe width 1.9 U fixed
5498 0 NMOS50T/M/H X5 Element Rule : drain ndiff to source diff spacing  3.6 U fixed
5505 0 NMOS50T/M/H X3 Element Rule : poly1 to drain diff spacing 0.8 U fixed
5516 0 NMOS50T/NMOS50M X6 Element Rule : source diff ovlp of rptub = 1.2 
5525 0 NMOS50H X6 Element Rule : source diff ovlp of rptub = 1.7 
5529 0 NMOS50T/M/H X7 Element Rule : rptub enclosure of pdiff guard ring 1
5532 0 NMOS50T/M/H X8 Element Rule : rptub width guard ring 2.7
5553 0 NMOS50H X9 Element Rule : dptub ovlp of sptub = 0.5 
5571 0 NMOS50T/M/H Y2 Element Rule : ntub stripe ovlp of drain diff = 4
5578 0 NMOS50T/M/H Y3 Element Rule : poly1 to drain diff spacing 1 U fixed
5584 0 NMOS50T/M/H Y4 Element Rule : poly width of gate connect = 3
5591 0 NMOS50T/M/H Y5 Element Rule : spacing rptub to drain diff = 6.8
5592 0 NMOS50T/M/H  Element Rule : nmos50 must have 2 ntub stripes
5601 0 NMOS50T/NMOS50M  Y8 Element Rule : rptub ovlp of source diff = 1.55
5610 0 NMOS50H Y8 Element Rule : rptub ovlp of source diff = 2.05
5615 0 NMOS50T/M/H Y6 Element Rule : 45 degree poly must have length 0.4
5617 0 NMOS50T/M/H Y7 Element Rule : 45 degree poly must have length 2.5
5619 0 NMOS50T/M/H Y7 Element Rule : poly must be angled
5621 0 NMOS50H Y10 Element Rule : rptub edge length = NMOS50H_Y10 * sqrt(2)
5623 0 NMOS50T/M/H Y9 Element Rule : rptub edge length = NMOS50T_Y9 * sqrt(2)
5656 0 NMOS50HS L Element Rule : Min gate length = 4 U
5657 0 NMOS50HS W Element Rule : Min gate width/2 = 20 U
5666 0 NMOS50HS X1/Y1 Element Rule : drain sntub ovlp of drain diff 0.4 U fixed
5673 0 NMOS50HS X2 Element Rule : ntub stripe spacing to drain diff 0.45 U fixed
5681 0 NMOS50HS X4 X10 Element Rule : ntub stripe width 1.9 U fixed
5694 0 NMOS50HS X5 Element Rule : drain ndiff to source diff spacing  3.6 U fixed
5703 0 NMOS50HS X6 Element Rule : channel diff ovlp of dptub = 1.2 
5708 0 NMOS50HS X7 Element Rule : rptub enclosure of pdiff guard ring 1
5711 0 NMOS50HS X8 Element Rule : rptub width guard ring 2.7
5718 0 NMOS50HS X3 X9 Element Rule : poly1 to drain diff spacing 0.8 U fixed
5725 0 NMOS50HS X11 Element Rule : poly width outside = 4.5
5732 0 NMOS50HS X12 Element Rule : spacing rptub to drain diff = 5.85
5748 0 NMOS50HS X13 Element Rule : poly width = 4.5
5757 0 NMOS50HS X14 Element Rule : dptub ovlp sptub =  0.5
5775 0 NMOS50HS Y2 Element Rule : ntub stripe ovlp of drain diff = 4
5782 0 NMOS50HS Y3 Element Rule : poly1 to drain diff spacing 1 U fixed
5788 0 NMOS50HS Y4 Element Rule : poly width of gate connect = 3
5795 0 NMOS50HS Y5 Element Rule : spacing rptub to drain diff = 6.8
5796 0 NMOS50HS Element Rule : nmos50hs must have ntub stripes
5801 0 NMOS50HS Y6 Y13 Element Rule : 45 degree poly must have length 0.4
5803 0 NMOS50HS Y7 Y12 Element Rule : 45 degree poly must have length 1.5 1.5
5805 0 NMOS50HS Y8  Element Rule : 45 degree sptub must have length 1.4
5821 0 NMOS50HS Y6/Y7 Element Rule : poly shape not correct, or bad connection
5870 0 NMOS20T/NMOS20M L Element Rule : Min gate length = 0.5 U
5871 0 NMOS20H L Element Rule : Min gate length = 0.5 U
5872 0 NMOS20T/M/H W2 Element Rule : Min gate width/2 = 5 U
5885 0 NMOS20T/M Element Rule X1 : poly1 to drain diff spacing 0.3 fixed
5892 0 NMOS20H Element Rule X1 : poly1 to drain diff spacing 0.5 fixed
5897 0 NMOS20T/M/H X3 Element Rule : drain ndiff to source diff spacing  1.2 U fixed
5906 0 NMOS20T/M Element Rule X2 : poly1 to drain diff spacing 1.8 fixed
5915 0 NMOS20H Element Rule X2 : poly1 to drain diff spacing 2 fixed
5938 0 NMOS20T/M Element Rule X4 : dptub ovlp of sntub 0.5 fixed
5947 0 NMOS20H Element Rule X4 : dptub ovlp of sntub 0.3 fixed
5956 0  NMOS20T/M Element Rule X5 : dptub extension of sptub 1 
5965 0  NMOS20H Element Rule X5 : dptub extension of sptub 0.8 
5972 0 NMOS20T/M/H Element Rule Y1 : poly1 to drain diff spacing 1 fixed
5981 0 NMOS20T/M/H Element Rule Y2 :  sntub ovlp drain diff 2 U fixed
5991 0 NMOS20T/M/H Y3 Element Rule : poly width of gate connect = 1.6
6000 0 NMOS20T/M/H Element Rule Y4 : poly to bulk pdiff spacing 0.7 fixed
6005 0 NMOS20T/M/H Y5 Element Rule : 45 degree poly must have length 1
6007 0 NMOS20T/M/H Y7 Element Rule : 45 degree poly must have length 0.4
6009 0 NMOS20T/M Y6 Element Rule : 45 degree sntub must have length 1.2
6011 0 NMOS20H Y6 Element Rule : 45 degree sntub must have length 0.9
6037 0 NMOSD20M L Element Rule : Min gate length = 0.5 U
6038 0 NMOSD20M W2 Element Rule : Min gate width/2 = 5 U
6039 0 NMOSD20M W3 Element Rule : Max gate width/2 = 200 U
6052 0 NMOSD20M Element Rule X1 : poly1 to drain diff spacing 0.3 fixed
6057 0 NMOSD20M X3 Element Rule : drain ndiff to source diff spacing  1.2 U fixed
6066 0 NMOSD20M Element Rule X2 : poly1 to drain diff spacing 1.8 fixed
6083 0 NMOSD20M Element Rule X4 : dptub ovlp of sntub 0.5 fixed
6092 0  NMOSD20M Element Rule X5 : dptub extension of sptub 1 
6099 0 NMOSD20M Element Rule Y1 : poly1 to drain diff spacing 1 fixed
6108 0 NMOSD20M Element Rule Y2 :  sntub ovlp drain diff 2 U fixed
6118 0 NMOSD20M Y3 Element Rule : poly width of gate connect = 1.6
6123 0 NMOSD20M Y5 Element Rule : 45 degree poly must have length 1
6125 0 NMOSD20M Y7 Element Rule : 45 degree poly must have length 0.4
6127 0 NMOSD20M Y6 Element Rule : 45 degree sntub must have length 1.2
6150 0 NMOSD20M Element Rule Y4 : poly to bulk pdiff spacing 0.7 fixed
6157 0 NMOSD20M Element Rule X6 :  poly1 to PPLUS spacing 0.3 U fixed
6165 0 NMOSD20M Element Rule X7 :  poly1 to CONT spacing 0.55 U fixed
6171 0 NMOSD20M Element Rule Y9 : Minimum NPLUS enclosure of NDIFFCON = 0.2 
6174 0 NMOSD20M Element Rule Y8 : Minimum NDIFF enclosure of NDIFFCON = 0.2 
6176 0 NMOSD20M Element Rule Y9 : fixed size of butting pdiff square
6179 0 NMOSD20M Element Rule Y10: min spacing of butting pdiff to butting pdiff 1.6 U
6236 0 PMOS50T/M L Element Rule : Min gate length = 1 U
6237 0 PMOS50H L Element Rule : Min gate length = 1.4 U
6238 0 PMOS50T/M W2 Element Rule : Min gate width/2 = 5 U
6239 0 PMOS50H W2 Element Rule : Min gate width/2 = 5 U
6248 0 PMOS50T/M/H X1 Y1 Element Rule : drain sptub ovlp of drain diff 0.15 U fixed
6264 0 PMOS50T/PMOS50M X4 Element Rule : drain diff to source diff spacing  3.3 U
6268 0 PMOS50H X4 Element Rule : drain diff to source diff spacing  3.6 U
6277 0 PMOS50T/PMOS50M X2 Element Rule : poly1 to drain diff spacing 1.2 U fixed
6284 0 PMOS50H X2 Element Rule : poly1 to drain diff spacing 1.35 U fixed
6295 0 PMOS50T/PMOS50M X3 Element Rule : dptub ovlp of drain diff = 3.5
6304 0 PMOS50H X3 Element Rule : dptub ovlp of drain diff = 3.6
6313 0 PMOS50T/M/H X5 Element Rule : source diff ovlp of sntub = 0.8
6321 0 PMOS50H X5 Element Rule : pplus ovlp of sdiff = 0.5 0.5
6328 0 PMOS50H X6 Element Rule :  pplus ovlp of poly =  0.3 0.3
6331 0 PMOS50T/M/H X7 Element Rule : dntub ovlp of source sntub = 1.65
6347 0 PMOS50T/M/H X8 Element Rule : rptub iso to dntub spacing = 4.5 U to 7.0 U
6348 0 PMOS50T/M/H X8 Y10 Element Rule : rptub iso is missing
6351 0 PMOS50T/M/H X9 Element Rule : rptub width of iso guard ring 4.5
6354 0 PMOS50T/M/H X10 Element Rule : RPTUB iso ovlp of pdiff = 1
6361 0 PMOS50T/M/H Y2 Element Rule : poly1 to drain diff spacing 1.15 U fixed
6370 0 PMOS50 Element Rule : dptub ovlp of drain diff       = 4
6376 0 PMOS50T/M/H Y4 Element Rule : poly width of gate connect =4.3 
6378 0 PMOS50T/M/H Y5 Element Rule : poly must be angled
6380 0 PMOS50T/M/H Y5 Element Rule : 45 degree poly must have length 1.9 * sqrt(2)
6381 0 PMOS50T/M/H X8 Y10 Element Rule : rptub iso is missing
6390 0 PMOS50T/M Y7 Element Rule : sntub ovlp of source diff = 1.2
6401 0 PMOS50T/M/H Y9 Element Rule : bulk ndiff to drain pdiff spacing 5.65 U fixed
6403 0 PMOS50T/M/H Y6 Element Rule : dptub must be angled
6405 0 PMOS50T/M/H Y6 Element Rule : rptub edge length = PMOS50T_Y10 * sqrt(2)
6407 0 PMOS50T/M Y8 Element Rule : sntub must be angled
6409 0 PMOS50H Y8 Element Rule : sntub must be angled
6411 0 PMOS50T/M/H Y8 Element Rule : sptub edge length = PMOS50T_Y8 * sqrt(2)
6413 0 PMOS50TM Element Rule : pplus must be closed over device
6414 0 PMOS50H Element Rule : pplus must NOT be closed over device
6423 0 PMOS50H Y7 Element Rule : sntub ovlp of source diff = 1.2
6428 0 PMOS50H Y11 Element Rule : met1 ovlp of source diff 1.5
6432 0 PMOS50H X13 Element Rule : met1 ovlp of source diff 1.5
6433 0 PMOS50H Element Rule X13/Y11: met1 must cover channel
6443 0 PMOS50H X11 Element Rule : pplus to sntub spacing 0.5 0.5
6452 0 PMOS50H X12 Element Rule : poly to sntub spacing   0.6 0.6
6489 0 PMOS50HS L Element Rule : Min gate length = 2.8 U
6490 0 PMOS50HS W Element Rule : Min gate width/2 = 5 U
6491 0 PMOS50HS Element Rule : pplus must be open over device
6500 0 PMOS50HS X1 Y1 Element Rule : drain sptub ovlp of drain diff 0.15 U fixed
6513 0 PMOS50HS X4 Element Rule : drain diff to gate diff spacing  3.6 U
6520 0 PMOS50HS X2 X11 Element Rule : poly1 to drain diff spacing 1.35 U fixed
6529 0 PMOS50HS X3 X12 Element Rule : dptub ovlp of drain diff = 3.6
6539 0 PMOS50HS X8 Y10 Element Rule : rptub iso to dntub spacing = 4.5
6540 0 PMOS50HS X8 Y10 Element Rule : rptub iso is missing
6543 0 PMOS50HS X9 Element Rule : rptub width of iso guard ring 4.5
6546 0 PMOS50HS X10 Element Rule : RPTUB iso ovlp of pdiff = 1
6554 0 PMOS50HS X13 Element Rule : poly width (outside) = 3.35
6561 0 PMOS50HS X14 Element Rule : spacing bulk-ndiff s/d-pdiff = 4.9
6574 0 PMOS50HS X15 Element Rule : poly width = 3.05
6581 0 PMOS50HS Y2 Element Rule : poly1 to s/d diff spacing 1.15 U fixed
6590 0 PMOS50HS Y3 Element Rule : dptub ovlp of drain diff = 4
6596 0 PMOS50HS Y4 Element Rule : poly width of gate connect =4.3 
6599 0 PMOS50HS Y5 Y11 Element Rule : 45 degree poly must have length 1.4 or 2
6601 0 PMOS50HS Y6 Y12 Element Rule : 45 degree dptub must have length 1.25 * sqrt(2)
6617 0 PMOS50HS Y5/Y11 Element Rule : poly shape not correct, or bad connection
6622 0 PMOS50HS X17 Y13 Element Rule : met1 ovlp of diff 1.5 U
6623 0 PMOS50H Element Rule X17 Y13: met1 must cover channel
6625 0 PMOS50HS Element Rule X13/Y17: met1 not touching drain diff
6626 0 PMOS50HS Element Rule X13/Y17: met1 touching 2 drain diffs, short
6635 0 PMOS50HS Element Rule : pplus to sntub spacing 0.5 U
6662 0 ESDPMOS18T REV1 L Element Rule : Fixed gate length = 0.8 U
6663 0 ESDPMOS18T REV1 W2 Element Rule : Min gate width/2 = 5 U
6672 0 ESDPMOS18H X1 Y1 Element Rule : drain sptub ovlp of drain diff 0.15 U fixed
6685 0 ESDPMOS18T X4 Element Rule : drain diff to source diff spacing  0.6 U
6693 0 ESDPMOS18T X2 Element Rule : poly1 to drain diff spacing 0.2 U fixed
6703 0 ESDPMOS18T X3 Element Rule : dptub ovlp of drain diff = 0.6
6712 0 ESDPMOS18T X5 Element Rule : source diff ovlp of sntub = 0.4
6718 0 ESDPMOS18T X7 Element Rule : dntub ovlp of source sntub = 2.8
6727 0 ESDPMOS18T X11 Element Rule : bulk ndiff to source pdiff spacing = 0.8
6734 0 ESDPMOS18T Y2 Element Rule : poly1 to drain diff spacing 0.3 U fixed
6743 0 ESDPMOS18T Y3 Element Rule : dptub ovlp of drain diff       = 1.5
6749 0 ESDPMOS18T Y4 Element Rule : poly width of gate connect =1.7 
6751 0 ESDPMOS18T Y5 Element Rule : poly must be angled
6753 0 ESDPMOS18T Y5 Element Rule : 45 degree poly must have length 1.9 * sqrt(2)
6755 0 ESDPMOS18T Y6 Element Rule : dptub must be angled
6757 0 ESDPMOS18T Y6 Element Rule : dptub edge length = 0.5 * sqrt(2)
6759 0 ESDPMOS18T Y8 Element Rule : sntub must be angled
6761 0 ESDPMOS18T Y8 Element Rule : sptub edge length = ESDPMOS18T_Y8 * sqrt(2)
6770 0 ESDPMOS18T Y7 Element Rule : sntub ovlp of source diff = 1.2
6781 0 ESDPMOS18T Y10 Element Rule : bulk ndiff to drain pdiff spacing 2.5 U fixed
6833 0 PMOS20H REV3 L Element Rule : Min gate length = 1.5 U
6836 0 PMOS20H REV3 W2 Element Rule : Min gate width/2 = 5 U
6837 0 PMOS20H REV4 L Element Rule : Min gate length = 1.1  U
6838 0 PMOS20H REV4 W2 Element Rule : Min gate width/2 = 5 U
6863 0 PMOS20T/M L Element Rule : Min gate length = 0.6  U
6864 0 PMOS20T/M W2 Element Rule : Min gate width/2 = 5 U
6875 0 PMOS20H X1 Y1 Element Rule : drain sptub ovlp of drain diff 0.15 U fixed
6888 0 PMOS20H X4 Element Rule : drain diff to source diff spacing  0.6 U
6896 0 PMOS20H X2 Element Rule : poly1 to drain diff spacing 0.2 U fixed
6910 0 PMOS20H X3 Element Rule : dptub ovlp of drain diff = 0.6
6919 0 PMOS20TM X3 Element Rule : dptub ovlp of drain diff = 1
6923 0 PMOS20H X8 Y11 Element Rule : min rptub iso to dntub spacing = 4.5
6924 0 PMOS20H X8 Y11 Element Rule : rptub iso is missing
6927 0 PMOS20H X9 Element Rule : rptub width of iso guard ring 4.5
6930 0 PMOS20H X10 Element Rule : RPTUB iso ovlp of pdiff = 1
6937 0 PMOS20H Y2 Element Rule : poly1 to drain diff spacing 0.3 U fixed
6946 0 PMOS20H Y3 Element Rule : dptub ovlp of drain diff       = 1.5
6952 0 PMOS20H Y4 Element Rule : poly width of gate connect =1.7 
6954 0 PMOS20H Y5 Element Rule : poly must be angled
6956 0 PMOS20H Y5 Element Rule : 45 degree poly must have length 1.9 * sqrt(2)
6957 0 PMOS20H X9 Y11 Element Rule : rptub iso is missing
6966 0 PMOS20H Y7 Element Rule : sntub ovlp of source diff = 1.2
6977 0 PMOS20H Y10 Element Rule : bulk ndiff to drain pdiff spacing 2.5 U fixed
6979 0 PMOS20H Y6 Element Rule : dptub must be angled
6981 0 PMOS20H Y6 Element Rule : dptub edge length = PMOS20H_Y6 * sqrt(2)
6983 0 PMOS20H Y8 Element Rule : sntub must be angled
6985 0 PMOS20H Y8 Element Rule : sntub must be angled
6987 0 PMOS20H Y8 Element Rule : sptub edge length = PMOS20H_Y8 * sqrt(2)
6997 0 PMOS20H Y9 Element Rule : dntub ovlp of source sntub = 0.6
7001 0 PMOS20H X7 Element Rule : dntub ovlp of source sntub = 1.65
7010 0 PMOS20H REV4 X5 Element Rule : pplus ovlp of source diff  = 0.5
7019 0 PMOS20H REV3 X5 Element Rule : source diff ovlp of sntub = 0.4
7026 0 PMOS20H REV4 X6 Element Rule : pplus ovlp of poly = 0.3
7033 0 PMOS20H Element Rule : met1 ovlp of source diff y direction 0.35
7037 0 PMOS20H Element Rule : source diff x direction ext of met1 0.3 U
7038 0 PMOS20H Element Rule X13/Y12: met1 must cover channel
7048 0 PMOS20H X11 Element Rule : pplus to sntub spacing 0.5 0.1
7058 0 PMOS20H X12 Element Rule : poly to sntub spacing   0.6 0.6
7062 0 PMOSD20M W2 Element Rule :  Minimum CHANNEL width/2 = 5 U
7063 0 PMOSD20M W3 Element Rule : Maximum CHANNEL width/2 = 200 U
7073 0 PMOSD20M X6 Element Rule : nplus to pgate spacing 0.3 
7078 0 PMOSD20M Y12 : Minimum PPLUS enclosure of PDIFFCON = 0.2
7084 0 PMOSD20M Y11 : Minimum PDIFF enclosure of PDIFFCON = 0.2
7088 0 PMOSD20T W2 Element Rule :  Minimum CHANNEL width/2 = 5 U
7089 0 PMOSD20T W3 Element Rule : Maximum CHANNEL width/2 = 200 U
7099 0 PMOSD20T X6 Element Rule : nplus to pgate spacing 0.3 
7104 0 PMOSD20T Y12 : Minimum PPLUS enclosure of PDIFFCON = 0.2
7110 0 PMOSD20T Y11 : Minimum PDIFF enclosure of PDIFFCON = 0.2
7146 0 PMOS120H L Element  Rule : Min gate length = 1.2  U
7147 0 PMOS120H W2 Element Rule : Min gate width/2 = 5 U
7166 0 PMOS120M L Element  Rule : Min gate length = 1  U
7167 0 PMOS120M W2 Element Rule : Min gate width/2 = 5 U
7176 0 PMOS120M/H X1 Element Rule : drain sptub ovlp of drain diff 0.2 U fixed
7187 0 PMOS120M/H X3 Element Rule : drain diff to source diff spacing  9.35 U
7194 0 PMOS120H X7 Element Rule : poly ovlp of source diff 4.3 U fixed
7201 0 PMOS120M X7 Element Rule : poly ovlp of source diff 3.5 U fixed
7223 0 PMOS120H/M X2 Element Rule : drain diff to met1 spacing 1.5 U fixed
7233 0 PMOS120M X8 Element Rule : poly ovlp of met1 0.75 U fixed
7240 0 PMOS120H/M X9 Element Rule : dptub ovlp of source diff 0.4 U fixed
7243 0 PMOS120H/M X11/X14/Y10 Element Rule :  dntub ovlp of sntub 2.8 U fixed
7251 0 PMOS120H X10 Element Rule : pplus ovlp of sdiff 0.5 fixed
7260 0 PMOS120H X11 Element Rule : pplus to sntub spacing 0.5 0.5 fixed
7267 0 PMOS120H X12 Element Rule : pplus ovlp of poly 0.3 fixed
7276 0 PMOS120H X13 Element Rule : pplus ovlp of poly 0.6 fixed
7283 0 PMOS120H Y1 Element Rule :  width of met1 hole is 2 * 1.85 U fixed 1.85 fixed
7290 0 PMOS120H Y4 Element Rule : width of poly hole is 2 * 5.4 U fixed 5.4 fixed
7297 0 PMOS120M Y4 Element Rule : width of poly hole is 2 * 6.2 U fixed 6.2 fixed
7304 0 PMOS120H Y6 Element Rule :  outer width of met1 is 2 * 6.15 U fixed 6.15 fixed
7311 0 PMOS120M Y6 Element Rule : outer width of met1 is 2 * 6.95 U fixed 6.95 fixed
7318 0 PMOS120M Y7 Element Rule : width of dptub  2 * 10.1 U fixed 10.1 fixed
7327 0 PMOS120H Y12 Element Rule : sntub ovlp of source diff fixed 1 fixed
7336 0 PMOS120M Y12 Element Rule : sntub ovlp of source diff fixed 0.5 fixed
7350 0 PMOS120M Y9  Element Rule : spacing poly bulk ndiff fixed 1.5  fixed
7363 0 PMOS120M Y8  Element Rule : outer radius of poly1  11.5 U  fixed PMOS120M Y8  fixed
7372 0 PMOS120H Y8  Element Rule : outer radius of poly1  11.7 U  fixed 11.7  fixed
7374 0 PMOS120M/H Y11 Element Rule : 45 degree sntub must have length 0.5 * sqrt(2)
7382 0 PMOS120H X15  Element Rule :  met1 ovlp of source diff 1.5 U  1.5  fixed
7385 0 PMOS120H Y13  Element Rule :  met1 ovlp of source diff 1.5 U  1.5  fixed
7386 0  PMOSVST bad device : no valid device found under correct HVDEF
7387 0 INFO: PMOSVST HVDEF
7389 0 PMOSVST_REV HVR001 : Version of PMOSVST obsolete or missing
7398 0 HVR003_PMOSVST_sources_must_be_connected_together
7431 0 PMOSVST L Element  Rule : Fix gate length = 0.6  U
7432 0 PMOSVST W2 Element Rule : Min gate width/2 = 10 U
7439 0 PMOSVST_X1 Element Rule : drain sptub ovlp of drain diff 0.2
7450 0 PMOSVST_Y1 Element Rule : drain sptub ovlp of drain diff 0.25
7459 0 PMOSVST_Y2   Element Rule : spac poly bulk ndiff 0.2 U
7466 0 PMOSVST_D Element Rule : dptub ovlp of source  diff 0.15
7478 0 PMOSVST_X2 Element Rule : met1 field plate ovlp of poly1 0.8
7490 0 PMOSVST_Y3 Element Rule : dntub ovlp of ndiff diff 2.0
7498 0 PMOSVST_X3 Element Rule : dntub ovlp of ndiff diff 3.0
7530 0 PMOSVST_R1 : DNTUB voltage must be specified with MET1 text must have +5/+20/+50 on met1 conn to ntap in DNTUB
7532 0 PMOSVST_R1 : HVDEF2 text isoVoltage=XX on gate missing
7561 0 PMOSVST_R2 : Minimum PMOSVST BULK_NTAP hole To NTAP hole spacing = 8.7
7577 0 PMOSVST_F : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = scalable 1575
7584 0 PMOSVST_F : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = scalable 8225
7591 0 PMOSVST_F : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = scalable 9625
7601 0 PMOSVST_E Element Rule : spacing sntub to dptub scaleable 1575
7609 0 PMOSVST_E Element Rule : spacing sntub to dptub scaleable 8225
7617 0 PMOSVST_E Element Rule : spacing sntub to dptub scaleable 9625
7625 0 PMOSVST_G Element Rule : ovlp poly source pdiff function 1575
7633 0 PMOSVST_G Element Rule : ovlp poly source pdiff function 8225
7641 0 PMOSVST_G Element Rule : ovlp poly source pdiff function 9625
7663 0 PMOSVST_H Element Rule : semi circle center to drain pdiff spacing 1575
7673 0 PMOSVST_H Element Rule : semi circle center to drain pdiff spacing 8225
7683 0 PMOSVST_H Element Rule : semi circle center to drain pdiff spacing 9625
7684 0  PMOSDVST bad device : no valid device found under correct HVDEF
7685 0 INFO: PMOSDVST HVDEF
7687 0 PMOSDVST_REV : HVR001 : Version of PMOSDVST obsolete or missing
7696 0 HVR003_PMOSDVST_sources_must_be_connected_together
7729 0 PMOSDVST L Element  Rule : Min gate length = 0.6  U
7730 0 PMOSDVST W2 Element Rule : Min gate width/2 = 10 U
7737 0 PMOSDVST_X1 Element Rule : drain sptub ovlp of drain diff 0.15
7748 0 PMOSDVST_Y1 Element Rule : drain sptub ovlp of drain diff 0.25
7757 0 PMOSDVST_Y2   Element Rule : spac poly bulk ndiff 0.2 U
7764 0 PMOSDVST_D Element Rule : dptub ovlp of source  diff 0.15
7776 0 PMOSDVST_X2 Element Rule : met1 field plate ovlp of poly1 0.8
7788 0 PMOSDVST_Y3 Element Rule : dntub ovlp of ndiff diff 2.0
7802 0 PMOSDVST_R1 : DNTUB voltage must be specified with MET1 text must have +5/+20/+50 on met1 conn to ntap in DNTUB
7804 0 PMOSDVST_R1 : HVDEF2 text isoVoltage=XX on gate missing
7819 0 PMOSDVST_Y4 Element Rule :  fixed size of butting ndiff square
7824 0 PMOSDVST_Y4 Element Rule :   Minimum PDIFF enclosure of PDIFFCON = 0.2
7838 0 PMOSDVST_R3 : source/bulk met1  must be connected together
7845 0 PMOSDVST_Y5 Element Rule :  Minimum PPLUS enclosure of PDIFFCON = 0.2
7848 0 PMOSDVST_R4: source pdiff cannot be abutted with BULK NDIFF ring
7849 0 PMOSDVST_R4: source pdiff cannot be abutted with BULK NDIFF ring
7875 0 PMOSDVST_R2 : Minimum PMOSDVST BULK_NTAP hole To NTAP hole spacing = 8.7
7877 0 PMOSDVST_R2/PMOSVST_R2 : Minimum PMOSDVST BULK_NTAP hole to PMOSVST BULK_NTAP hole 8.7
7879 0 Error : PMOSDVST without butting diff
7885 0 PMOSVST/PMOSIVST topology : missing pplus/nplus over diff
7894 0 PMOSVST/PMOSDVST topology : bad diff in device gap
7896 0 PMOSVST/PMOSDVST topology : bad poly
7898 0 PMOSVST/PMOSDVST topology: bad implant
7903 0 PMOSVST/PMOSDVST : bad drain diff missing pplus/sptub/dptub
7905 0 PMOSVST/PMOSDVST topology : bad dptub
7906 0 PMOSVST/NMOSDVST topology : bad dntub, missing dntub
7908 0 PMOSVST/PMOSDVST topology : bad sntub inside device, sntub only over source
7909 0 PMOSVST/PMOSDVST topology : bad layer over device
7910 0 PMOSVST/PMOSDVST topology : bad layer over device
7911 0 PMOSVST/PMOSDVST topology : bad layer over device
7943 0 PMOS20HS L Element Rule : Min gate length = 2.8 U
7944 0 PMOS20HS W Element Rule : Min gate width/2 = 5 U
7953 0 PMOS20HS X1 Y1 Element Rule : drain sptub ovlp of drain diff 0.2 U fixed
7966 0 PMOS20HS X4 Element Rule : drain diff to gate diff spacing 0.6 U
7973 0 PMOS20HS X2 Element Rule : poly1 to drain diff spacing ( inside) 0.2  U fixed
7980 0 PMOS20HS X6 Element Rule : poly1 to drain diff spacing (outside)  0.2  U fixed
7989 0 PMOS20HS X3 Element Rule : dptub ovlp of drain diff (inside) = 0.6
7998 0 PMOS20HS X7 Element Rule : dptub ovlp of drain diff (outside) = 0.6
8005 0 PMOS20HS X5 Element Rule : pplus ovlp of gate diff = 0.5
8013 0 PMOS20HS X8  Element Rule : poly width (outside) = 0.9 
8020 0 PMOS20HS X9  Element Rule : spacing bulk-ndiff s/d-pdiff = 1.6 
8035 0 PMOS20HS X10 Y9 Element Rule : dntub ovlp of sntub = 0.6 0.1 U
8044 0 PMOS20HS X12 Element Rule : pplus to sntub spacing 0.2 U
8051 0 PMOS20HS Y2 Element Rule : poly1 to s/d diff spacing 0.3 U fixed
8060 0 PMOS20HS Y3 Element Rule : dptub ovlp of drain diff = 1.5
8066 0 PMOS20HS Y4 Element Rule : poly width of gate connect = PMOS20HS_Y4
8069 0 PMOS20HS Y5 Y7 Element Rule : 45 degree poly must have length 0.6 or 0.8
8071 0 PMOS20HS Y6 Y8 Element Rule : 45 degree dptub must have length 0.5 * sqrt(2)
8076 0 PMOS20HS X13 Element Rule : diff ovlp of gate met1  0.3 U
8079 0 PMOS20HS Y11 Element Rule : gate met1 ovlp of diff  0.35 U
8080 0 PMOS20HS Element Rule X13 Y11: met1 must cover channel
8082 0 PMOS20HS Element Rule X13/Y11: met1 not touching drain diff
8083 0 PMOS20HS Element Rule X13/Y11: met1 touching 2 drain diffs, short
8123 0 NMOSI50 L Element Rule : Min gate length = 0.5 U
8124 0 NMOSI50 W2 Element Rule : Min gate width/2 = 5 U
8131 0 NMOSI50T/M/H X1 Element Rule : source ndiff to bulk pdiff = 0.65 U fixed
8139 0 NMOSI50T/M/H X2 Element Rule : source ndiff ovlp of poly = 0.85 U fixed
8154 0 NMOSI50T/M/H X3 Y4 Element Rule : sntub to sptub spacing = 0.4 U fixed
8163 0 NMOSI50T/M/H X4 Element Rule : source diff ovlp of sptub = 1
8172 0 NMOSI50T/M/H X5 Element Rule : ovlp dptub sptub = 3.7 U fixed
8187 0 NMOSI50T/M X6 Element Rule : ovlp poly source ndiff = 3.1 U
8196 0 NMOSI50H X6 Element Rule : ovlp poly source ndiff = 3.1 U
8205 0 NMOSI50T/M/H X7 Element Rule : ovlp sntub source ndiff = 3.2 U fixed
8218 0 NMOSI50T/M X8 Element Rule : source ndiff spacing to drain ndiff = 4 U
8225 0 NMOSI50H X8 Element Rule : source ndiff spacing to drain ndiff = 4 U
8228 0 NMOSI50T/M/H X9 Element Rule : dntub ovlp of source sntub = 1.4
8244 0 NMOSI50T/M/H X10 Y14 Element Rule : rptub iso to dntub spacing = 4.5 to 7.0 U
8245 0 NMOSI50T/M/H X10  Element Rule : rptub iso is missing
8248 0 NMOSI50T/M/H X11 Element Rule : rptub width of iso guard ring = 4.5
8251 0 NMOSI50T/M/H X12 Element Rule : RPTUB iso ovlp of pdiff = 1
8266 0 NMOSI50T/M/H Y1 Element Rule : sptub ovlp of bulk pdiff = 0.6 U fixed
8273 0 NMOSI50T/M/H Y2 Element Rule : poly to bulk pdiff spacing = 1.3 U fixed
8282 0 NMOSI50T/M/H Y3 Element Rule : ovlp dptub bulk pdiff = 5.2 U fixed
8287 0 NMOSI50T/M/H Y5 Element Rule : poly width of gate connect = 4.3
8290 0 NMOSI50T/M/H Y6 Element Rule : width of sntub ring = 4.2 U fixed
8297 0 NMOSI50T/M/H Y13 Element Rule : bulk pdiff to drain ndiff spacing 6.7 U
8299 0 NMOSI50T/M/H Y7 Element Rule : 45 degree poly must have length 0.65
8301 0 NMOSI50T/M/H Y11 Element Rule : 45 degree poly must have length 2.2
8303 0 NMOSI50T/M/H Y11 Element Rule : poly must be angled
8305 0 NMOSI50 Element Rule : sptub must be angled
8307 0 NMOSI50T/M/H Y8 Element Rule : 45 degree sptub must have length 0.3 * sqrt(2)
8309 0 NMOSI50 Element Rule :sntub ring must be angled
8314 0 NMOSI50T/M/H Y9 Element Rule : 45 degree sntub ring must have length 0.7
8316 0 NMOSI50T/M/H Y12 Element Rule : 45 degree sntub ring must have length 2.25
8318 0 NMOSI50T/M/H Y10 Element Rule : dptub must be angle
8320 0 NMOSI50T/M/H Y10 Element Rule : 45 degree dptub must have length 2 * sqrt(2)
8372 0 NMOSI120M/H L Element Rule : Min gate length = 0.5 U
8373 0 NMOSI120M/H W2 Element Rule : Min gate width/2 = 5 U
8380 0 NMOSI120H/M X1 Element Rule : source ndiff to bulk pdiff = 0.65 U fixed
8394 0 NMOSI120H/M X2 Element Rule : source ndiff ovlp of poly = 0.85 U fixed
8406 0 NMOSI120H X3/Y3 Element Rule : ovlp dptub sptub = 1 U fixed
8409 0 NMOSI120M X3/Y3 Element Rule : ovlp dptub sptub = 0 U fixed
8418 0 NMOSI120 H X5 Element Rule : source diff ovlp of sptub = 2
8427 0 NMOSI120 M X5 Element Rule : source diff ovlp of sptub = 1
8436 0 NMOSI120H/M X6 Element Rule : ovlp poly source ndiff = 2.5 U
8443 0 NMOSI120H/M X7 Element Rule : spac source drain ndiff = 9 U
8458 0 NMOSI120H X8 Element Rule : ovlp dntub sntub  = 2.9 U
8461 0 NMOSI120M X8 Element Rule : min ovlp dntub sntub  = 2.5 U
8470 0 NMOSI120H/M X9 Element Rule : ovlp sntub drain ndiff = 0.25 U
8485 0 NMOSI120H/M X10 Element Rule : spac met1 drain ndiff = 1.7 U
8510 0 NMOSI120H/M Y1 Element Rule : poly to bulk pdiff spacing = 0.6 U fixed
8513 0 NMOSI120M Y2 Element Rule : sptub enc bulk pdiff = 2.4 U fixed
8516 0 NMOSI120H Y2 Element Rule : sptub enc bulk pdiff = 1.4 U fixed
8530 0 NMOSI120H/M Y5 Element Rule : ovlp poly dptub = 3.5 U
8543 0 NMOSI120M Y4 Element Rule : spac dptub drain diff = 11.5 U
8550 0 NMOSI120H Y4 Element Rule : spac dptub drain diff = 11.5 U
8552 0 NMOSI120H Y7 Element Rule : sptub must be angled
8554 0 NMOSI120H Y7 Element Rule : 45 degree sptub must have length 0.65 * sqrt(2)
8556 0 NMOSI120M Y7 Element Rule : sptub must be angled
8558 0 NMOSI120M Y7 Element Rule : 45 degree sptub must have length 1.2 * sqrt(2)
8560 0 NMOSI120H Y8 Element Rule : dptub must be angle
8562 0 NMOSI120M/H Y8 Element Rule : 45 degree dptub must have length 1.2 * sqrt(2)
8564 0 NMOSI20H Y10 Element Rule : poly must be angled
8566 0 NMOSI120H/M Y10 Element Rule : 45 degree poly must have length 2.2
8568 0 NMOSI20H/M Y12 Element Rule : met1 must be angled
8573 0 NMOSI120M Y12 Element Rule : 45 degree poly must have length 2
8578 0 NMOSI120H Y12 Element Rule : 45 degree poly must have length 2
8642 0 NMOSI20T L Element Rule : Min gate length = Minimum CHANNEL length = 0.7 U
8648 0 NMOSI20MH L Element Rule : Min gate length = Minimum CHANNEL length = 0.5 U
8649 0 NMOSI20H W2 Element Rule : Min gate width/2 = Minimum CHANNEL width / 2 = 5 U
8656 0 NMOSI20H X1 Element Rule : source ndiff to bulk pdiff = 0.65 U fixed
8676 0 NMOSI20H X2 Element Rule : source ndiff ovlp of poly = 0.85 U fixed
8688 0 NMOSI20T/M X3 Element Rule : source diff ovlp of sptub = 1.1
8697 0 NMOSI20H X4 Element Rule : source diff ovlp of sptub = 1.8
8709 0 NMOSI20H X5 Element Rule : ovlp dptub sptub = 0.5 U fixed
8727 0 NMOSI20T X4 Element Rule : ovlp dptub sptub = 1.8 U fixed
8739 0 NMOSI20M X4 Element Rule : ovlp dptub sptub = 1.5 U fixed
8751 0 NMOSI20H X6 Element Rule : ovlp poly source ndiff = 1.5 U
8760 0 NMOSI20T/M X5 Element Rule : ovlp poly source ndiff = 0.7 U
8770 0 NMOSI20H X8 Element Rule : source ndiff spacing to drain ndiff = 2 U
8777 0 NMOSI20T/M X6 Element Rule : source ndiff spacing to drain ndiff = 1.2 U
8780 0 NMOSI20T/M/H X9 Element Rule : min dntub ovlp of source sntub = 1.4
8784 0 NMOSI20H X10 Y14 Element Rule : rptub iso to dntub spacing = 4.5
8785 0 NMOSI20H X11 Element Rule : rptub iso is missing
8788 0 NMOSI20H X11 Element Rule : rptub width of iso guard ring = 4.5
8791 0 NMOSI20H X12 Element Rule : RPTUB iso ovlp of pdiff = 1
8806 0 NMOSI20H Y1 Element Rule : sptub ovlp of bulk pdiff = 1.8 U fixed
8813 0 NMOSI20H Y2 Element Rule : poly to bulk pdiff spacing = 1.3 U fixed
8822 0 NMOSI20H Y3 Element Rule : ovlp dptub bulk pdiff = 1.8 U fixed
8827 0 NMOSI20H Y5 Element Rule : poly width of gate connect = 2.25
8830 0 NMOSI20T/M Y5 Element Rule : poly width of gate connect = 2.25
8839 0 NMOSI20T/M Y3 Element Rule : ovlp sptub bulk pdiff = 1.3 U fixed
8848 0 NMOSI20T Y4 Element Rule : ovlp dptub sptub = 0.4 U fixed
8859 0 NMOSI20T/M Y5 Element Rule : poly to drain ndiff spac = 0.55
8866 0 NMOSI20H Y13 Element Rule : bulk pdiff to drain ndiff spacing 4.1 U
8871 0 NMOSI20H Y7 Element Rule : 45 degree poly must have length 0.65
8873 0 NMOSI20H Y11 Element Rule : 45 degree poly must have length 1.35
8875 0 NMOSI20H Y11 Element Rule : poly must be angled
8877 0 NMOSI20 Y8 Element Rule : sptub must be angled
8879 0 NMOSI20H Y8 Element Rule : 45 degree sptub must have length 0.75 * sqrt(2)
8881 0 NMOSI20H Y11 Element Rule : dptub must be angle
8883 0 NMOSI20M/H Y10 Element Rule : 45 degree dptub must have length 0.75 * sqrt(2)
8885 0 NMOSI20T/M Y11 Element Rule : dptub must be angle
8887 0 NMOSI20T Y8 Element Rule : 45 degree dptub must have length 0.9 * sqrt(2)
8926 0 NMOSDI20H/M L Element Rule : Minimum channel length = 0.5 U
8927 0 NMOSDI20H/M W2 Element Rule :  Minimum CHANNEL width/2 = 5 U
8928 0 NMOSDI20H/M W3 Element Rule : Maximum CHANNEL width/2 = 200 U
8937 0 NMOSDI20H/M X2 : DIFFCON spacing to GATE = 0.55
8948 0 NMOSDI20H/M X3 : SOURCE-NDIFF extension of SPTUB = 1.3
8959 0 NMOSDI20M X3 : 1.3
8966 0 NMOSDI20H X8 Element Rule : source ndiff spacing to drain ndiff = 1.2 U
8980 0 NMOSDI20H X4 Element Rule : ovlp dptub sptub =  1.6 U fixed
8994 0 NMOSDI20M X4 Element Rule : ovlp dptub sptub =  1.5 U fixed
9003 0 NMOSI20H/M X5 Element Rule : ovlp poly source ndiff = 0.7 U
9016 0 NMOSDI20M X7 Element Rule : ovlp sntub drain ndiff = 1.8 U
9027 0 NMOSDI20H X7 Element Rule : ovlp sntub drain ndiff = 1.8 U
9036 0 NMOSDI20H/M X8 Element Rule : dntub ovlp of source sntub = 1.4
9039 0 NMOSDI20 Y11 : Minimum NPLUS enclosure of NDIFFCON = 0.2
9046 0 NMOSDI20H/M Y1 Element Rule : poly to bulk pdiff spacing = 1.3 U fixed
9055 0 NMOSDI20H Y2 Element Rule : sptub ovlp of bulk pdiff = 1.8 U fixed
9058 0 NMOSDI20H/M Y11 : Minimum NPLUS enclosure of NDIFFCON = 0.2
9067 0 NMOSDI20H/M Y11 Element Rule extra check : pplus ovlp diffcon = 0.25 U fixed
9076 0 NMOSDI20H/M Y10 Element Rule : nplus ovlp ndiffcon = 0.25 U fixed
9088 0 NMOSDI20H/M Y3 Element Rule : poly width of gate connect = 2.25
9097 0 NMOSDI20H/M Y5 Element Rule : poly to drain diff spacing == 0.55 U fixed
9100 0 NMOSDI20H/M Y4 Element Rule : sptub ovlp of dptub = 0 U fixed, too small
9102 0 NMOSDI20H/M Y4 Element Rule : sptub ovlp of dptub = 0 U fixed, too large
9104 0 NMOSDI20 Y6 Element Rule : 45 degree poly must have length 0.65
9106 0 NMOSDI20 Y9 Element Rule : 45 degree poly must have length 1.35
9108 0 NMOSDI20 Y7  Element Rule : 45 degree sptub must have length 0.75
9110 0 NMOSDI20 Y8  Element Rule : 45 degree dptub must have length 0.75
9147 0 NMOSDI50H L Element Rule : Minimum channel length = 0.5 U
9148 0 NMOSDI50H W2 Element Rule :  Minimum CHANNEL width/2 = 5 U
9157 0 NMOSDI50H X2 : DIFFCON spacing to GATE = 0.55
9172 0 NMOSDI50H X3 Element Rule : spacing sntub sptub = 0.4 0.9 U fixed
9181 0 NMOSDI50H X4 : SOURCE-NDIFF extension of SPTUB = 1
9193 0 NMOSDI50H X5 Element Rule : ovlp dptub sptub =  3.7 U fixed
9202 0 NMOSI20H X6 Element Rule : ovlp poly source ndiff = 3.1 U
9211 0 NMOSDI50H X7 Element Rule : ovlp sntub source ndiff = 3.2 U
9218 0 NMOSDI50H X8 Element Rule : source ndiff spacing to drain ndiff = 4 U
9221 0 NMOSDI50H X9 Element Rule : dntub ovlp of source sntub = 1.4
9228 0 NMOSDI50H Y2 Element Rule : poly to bulk pdiff spacing = 1.3 U fixed
9237 0 NMOSDI50H Y1 Element Rule : sptub ovlp of bulk pdiff = 0.6 U fixed
9246 0 NMOSDI50H Y3 Element Rule : ovlp dptub bulk/source diff = 5.2 U fixed
9265 0 NMOSDI50H Y6 Element Rule : width of sntub ring = 4.2 U fixed
9272 0 NMOSDI50H Y5 Element Rule : poly width of gate connection 4.3 U fixed
9274 0 NMOSDI50H Y7 Element Rule : 45 degree poly must have length 0.65
9276 0 NMOSDI50H Y9 Element Rule : 45 degree poly must have length 2.2 
9278 0 NMOSDI50H Y8  Element Rule : 45 degree sptub must have length 0.3
9280 0 NMOSDI50H Y10  Element Rule : 45 degree dptub must have length 2.0
9282 0 NMOSDI50H Y9  Element Rule : 45 degree sntub must have length 0.7
9284 0 NMOSDI50H Y12  Element Rule : 45 degree sntub must have length 2.25
9291 0 NMOSDI50H Y13 Element Rule : bulk pdiff to drain ndiff spacing 6.7 U
9294 0 NMOSDI50H Y14 : Minimum NDIFF enclosure of NDIFFCON = 0.2
9303 0 NMOSDI50H Y15 Element Rule : nplus ovlp ndiffcon = 0.2 U fixed
9304 0 NMOSDIVST : no valid device found under correct HVDEF
9309 0 NMOSDIVST : Device shares common dntub with other HV devices, not supported
9310 0 INFO: NMOSDIVST HVDEF
9312 0 NMOSDIVST_REV : HVR001 : Version of NMOSDIVST obsolete or missing
9340 0 NMOSDIVST L Element  Rule : Min gate length = 0.6  U
9343 0 NMOSDIVST W2 Element Rule : Min gate width/2 = 10 U
9352 0  NMOSDIVST_X1 Element Rule : diffcon spacing to gate = 0.55
9361 0 NMOSDIVST_X2 Element Rule : MET1 (field plate) overlap of POLY1 = 0.8
9368 0 NMOSDIVST_AMET Element Rule : MET1 (field plate) to DRAIN-NDIFF spacing = 1.25
9375 0 NMOSDIVST_X4 Element Rule : ndiff width outside = 0.7 fixed
9388 0 NMOSDIVST_X5 Element Rule : sntub ovlp drain diff outside 0.2 fixed
9395 0 NMOSDIVST_X3 Element Rule : sntub ovlp drain diff inside 0.05 fixed
9402 0 NMOSDIVST_Y1 Element Rule :  poly to bulk diff spacing = 0.6 U fixed
9411 0 NMOSDIVST_Y2 Element Rule :  ovlp sptub bulk/source diff = 2.0 U fixed
9420 0 NMOSDIVST_Y3 Element Rule :  ovlp dptub bulk/source diff = 3.0 U fixed
9424 0 NMOSDIVST Y4 Element Rule : 45 degree poly must have length 0.2 * sqrt(2)
9426 0 NMOSDIVST Y4 Element Rule : poly1 hole must be angled
9428 0 NMOSDIVST Y6 Element Rule : dptub must be angled
9430 0 NMOSDIVST Y6 Element Rule : 45 degree dptub must have length 0.5 * sqrt(2)
9432 0 NMOSDIVST Y5 Element Rule : sptub must be angled
9434 0 NMOSDIVST Y5 Element Rule : 45 degree sptub must have length 0.8 * sqrt(2)
9437 0 NMOSDIVST_Y7 Element Rule :  min ndiff ovlp of diffcon =  0.2
9440 0 NMOSDIVST_Y8 Element Rule : min NPLUS ovlp of diffcon = 0.2
9448 0 NMOSDIVST_Y8 Element Rule :  fixed size of butting pdiff square
9455 0 NMOSDIVST Element Rule : min spacing of butting pdiff to butting pdiff
9471 0 NMOSDIVST_R1 : source/bulk met1  must be connected together
9477 0 NMOSDIVST_R2 : DNTUB voltage must be specified with MET1 text must have +5/+20/+50 on met1 conn to ntap in DNTUB
9479 0 NMOSDIVST_R2 : HVDEF2 text isoVoltage=XX on gate missing
9489 0 NMOSDIVST_F : f = 7.45  DRAIN-NDIFF to SOURCE-DIFF spacing (field plate) = scalable 7450
9500 0 NMOSDIVST_E : f = 7.45 DIFF extension of RPTUB = scalable 1.2
9510 0 NMOSDIVST_G : f = 7.45 POLY1 extension of SOURCE-DIFF = function 2.525
9524 0 NMOSDIVST_GY : f = 7.45 POLY1 Y extension of SOURCE-DIFF = function 7.85
9536 0 NMOSDIVST_DNX : f = 7.45 DNTUB enclosure of NDIFF = function 1.45 fixed, no common DNTUB allowed
9545 0 NMOSDIVST_FY : f = 7.45 DRAIN-NDIFF to DIFF spacing = function 14.025
9548 0 NMOSDIVST_P1B : f = 7.45 45 degree poly must have length 2.4 * sqrt(2)
9551 0 NMOSDIVST_M1B : f = 7.45 45 degree met1 must have length 2.525 * sqrt(2)
9558 0 INFO: NMOSIVST HVDEF
9560 0 HVR001 : Version of NMOSIVST obsolete or missing
9561 0 NMOSIVST : no valid device found under correct HVDEF
9566 0 NMOSIVST : Device shares common dntub with other HV devices, not supported
9605 0 NMOSIVST L Element  Rule : Min gate length = 0.6  U
9608 0 NMOSIVST W2 Element Rule : Min gate width/2 = 10 U
9615 0  NMOSIVST_X1 Element Rule : source_ndiff to bulk_pdiff spacing  = 0.65
9624 0 NMOSIVST_X2 Element Rule : MET1 (field plate) overlap of POLY1 = 0.8
9633 0 NMOSIVST_AMET Element Rule : MET1 (field plate) to DRAIN-NDIFF spacing = 1.25
9640 0 NMOSIVST_X4 Element Rule : ndiff width outside = 0.7 fixed
9653 0 NMOSIVST_X5 Element Rule : sntub ovlp drain diff outside 0.2 fixed
9660 0 NMOSIVST_X3 Element Rule : sntub ovlp drain diff inside 0.05 fixed
9667 0 NMOSIVST_Y1 Element Rule :  poly to bulk diff spacing = 0.6 U fixed
9676 0 NMOSIVST_Y2 Element Rule :  ovlp sptub bulk/source diff = 2.0 U fixed
9685 0 NMOSIVST_Y3 Element Rule :  ovlp dptub bulk/source diff = 3.0 U fixed
9689 0 NMOSIVST Y4 Element Rule : 45 degree poly must have length 0.2 * sqrt(2)
9691 0 NMOSIVST Y4 Element Rule : poly1 hole must be angled
9693 0 NMOSIVST Y5 Element Rule : sptub must be angled
9695 0 NMOSIVST Y5 Element Rule : 45 degree sptub must have length 0.8 * sqrt(2)
9697 0 NMOSIVST Y6 Element Rule : dptub must be angled
9699 0 NMOSIVST Y6 Element Rule : 45 degree dptub must have length 0.5 * sqrt(2)
9701 0 NMOSIVST_R1 : source/bulk met1  must be connected together
9707 0 NMOSIVST_R2 : DNTUB voltage must be specified with MET1 text must have +5/+20/+50 on met1 conn to ntap in DNTUB
9709 0 NMOSIVST_R2 : HVDEF2 text isoVoltage=XX on gate missing
9719 0 NMOSIVST_F : f = 7.45  DRAIN-NDIFF to SOURCE-DIFF spacing (field plate) = scalable 7450
9730 0 NMOSIVST_E : f = 7.45 DIFF extension of RPTUB = scalable 1.2
9740 0 NMOSIVST_G : f = 7.45 POLY1 extension of SOURCE-DIFF = function 2.525
9754 0 NMOSIVST_GY : f = 7.45 POLY1 Y extension of SOURCE-DIFF = function 7.85
9766 0 NMOSIVST_DNX : f = 7.45 DNTUB enclosure of NDIFF = function 1.45 fixed, no common DNTUB allowed
9775 0 NMOSIVST_FY : f = 7.45 DRAIN-NDIFF to DIFF spacing = function 14.025
9778 0 NMOSIVST_P1B : f = 7.45 45 degree poly must have length 2.4 * sqrt(2)
9781 0 NMOSIVST_M1B : f = 7.45 45 degree met1 must have length 2.525 * sqrt(2)
9793 0 NMOSIVST/NMOSDIVST topology : missing pplus/nplus over diff
9796 0 NMOSIVST topology : bad butting diff
9805 0 NMOSIVST/NMOSDIVST topology : bad diff in device gap
9808 0 NMOSIVST/NMOSDIVST topology : bad implant in device gap
9811 0 NMOSIVST/NMOSDIVST topology : bad implant in device gap
9813 0 NMOSIVST/NMOSDIVST topology : bad poly
9815 0 NMOSIVST/NMOSDIVST topology : bad implant
9818 0 NMOSIVST/NMOSDIVST topology : bad source diff
9821 0 NMOSIVST/NMOSDIVST topology : bad source diff
9823 0 NMOSIVST/NMOSDIVST topology : bad dptub, dptub not in source/bulk area
9825 0 NMOSIVST/NMOSDIVST topology : bad dptub, dptub not in source/bulk area
9827 0 NMOSIVST/NMOSDIVST topology : bad sptub, sptub not in source/bulk area
9829 0 NMOSIVST/NMOSDIVST  topology: bad sptub, sptub not in source/bulk area
9830 0 NMOSIVST/NMOSDIVST  topology: bad dntub, missing dntub
9834 0 NMOSIVST/NMOSDIVST topology : bad sntub inside device, sntub only over drain
9835 0 NMOSIVST/NMOSDIVST topology: bad layer over device
9836 0 NMOSIVST/NMOSDIVST topology: bad layer over device
9837 0 NMOSIVST/NMOSDIVST topology: bad layer over device
9870 0 NMOS20HS L Element Rule : Min gate length = 1.8 U
9871 0 NMOS20HS W Element Rule : Min gate width/2 = 5 U
9886 0 NMOS20HS X3 Element Rule : drain ndiff to source diff spacing 0.6 U fixed
9893 0 NMOS20HS X4 Element Rule : drain ndiff to source diff spacing 0.9 U fixed
9900 0 NMOS20HS X2 Element Rule : poly1 to drain diff spacing 0.6 U fixed
9909 0 NMOS20HS X1 Element Rule : drain nplus ovlp of drain diff 0.45 U fixed
9918 0 NMOS20HS X5 Element Rule : drain sntub ovlp of drain diff 1.4 U fixed
9927 0 NMOS20HS X7 Element Rule : drain sntub ovlp of drain diff outside 0.7 U fixed
9936 0 NMOS20HS X8 Element Rule : rptub spacing to drain diff outside 1.7 U fixed
9945 0 NMOS20HS Y1 Element Rule : sntub encl of drain diff 1.65 U fixed
9954 0 NMOS20HS Y2 Element Rule : rptub spacing to drain diff 2.65 U fixed
9963 0 NMOS20HS Y3 Element Rule : poly1 overlap of channel diff 1 U fixed
9965 0 NMOS20HS Y4 Element Rule : 45 degree poly must have length 0.5
9968 0 NMOS20HS Y5 Y6 Element Rule : 45 degree poly must have length 1.65 or 0.65
9970 0 NMOS20HS Y7 Element Rule : 45 degree poly must have length 2.25
10010 0 PMOS10MH_L Element Rule : Min gate length =  0.5 U
10011 0 PMOS10MH_L Element Rule : Min gate length =  0.5 U
10012 0 PMOS10MH_W2 Element Rule : Min gate width =  1.5 U
10013 0 PMOS10MH_W2 Element Rule : Min gate width =  2.5 U
10014 0 PMOS10MH_W3 Element Rule : Max gate width =  200 U
10023 0 PMOS10MH/PMOSD10MH Element Rule X1 : poly1 to drain diff cont spacing 0.3 U fixed
10032 0 PMOS10MH/PMOSD10MH Element Rule X2 : hvox ovlp drain diff cont  0.6 U fixed
10041 0 PMOS10MH/PMOSD10MH Element Rule X3 : dptub ovlp drain diff cont  0.6 U fixed
10048 0 PMOS10MH/PMOSD10MH Element Rule X4 : dptub ovlp drain diff cont  0.6 U fixed
10057 0 PMOS10MH/PMOSD10MH Element Rule X5 : sptub ovlp drain diff cont  0.15 U fixed
10060 0 PMOS10MH/PMOSD10MH Element Rule X6 Y10 : min dntub ovlp sntub 1.8
10067 0 PMOSD10MH Element Rule X7 : spacing gate nplus  0.3 U fixed
10076 0  PMOS10MH/PMOSD10MH Element Rule Y1 : spacing poly drain diff 0.2
10085 0 PMOS10MH/PMOSD10MH Element Rule Y2 : ovlp hvox  drain diff 0.6
10094 0 PMOS10MH/PMOSD10MH Element Rule Y3 : ovlp dptub drain diff 0.6
10101 0 PMOS10MH Y4 Element Rule : poly width of gate connect = 1
10108 0 PMOS10MH/PMOSD10MH Element Rule Y5 : spac drain diff to bulk ndiff  1.8
10121 0 PMOS10MH/PMOSD10MH Element Rule Y6 : spac dptub to sntub  1.15
10128 0 PMOS10MH/PMOSD10MH Element Rule Y7 : ovlp sptub drain diff 0.25
10130 0 PMOS10MH/PMOSD10MH Y8 Element Rule : poly must be angled
10132 0 PMOS10MH/PMOSD10MH Y8 Element Rule : 45 degree poly must have length 0.3 * sqrt(2)
10134 0 PMOS10MH_Y9 Element Rule : dptub must be angled
10136 0 PMOS10MH/PMOSD10MH Y9 Element Rule : 45 degree dptub must have length 0.3 * sqrt(2)
10151 0 PMOSD10MH Y11 : Minimum PDIFF enclosure of PDIFFCON = 0.2
10156 0 PMOSD10MH Y12 : Minimum PPLUS enclosure of PDIFFCON = 0.2
10158 0 PMOSD10MH Element Rule Y12 : fixed size of butting ndiff square 0.9x0.9
10161 0 PMOSD10MH INFO : min spacing of butting ndiff to ndiff 1.6
10162 0 PMOSD10MH/PMOS10MH missing or bad HVOX on device
10163 0 PMOSD10MH/PMOS10MH missing or bad MIDOX on device
10203 0 NMOS10MH_L Element Rule : Min gate length =  0.4 U
10204 0 NMOS10MH_L Element Rule : Min gate length =  0.4 U
10205 0 NMOS10MH_W2 Element Rule : Min gate width =  1.5 U
10206 0 NMOS10MH_W2 Element Rule : Min gate width =  2.5 U
10207 0 NMOS10MH_W3 Element Rule : Max gate width =  200 U
10216 0 NMOS10MH/NMOSD10MH Element Rule X1 : poly1 to drain diff cont spacing 0.3 U fixed
10225 0 NMOS10MH/NMOSD10MH Element Rule X2 : hvox ovlp drain diff cont  0.6 U fixed
10234 0 NMOS10MH/NMOSD10MH Element Rule X3 : sntub ovlp drain diff cont  0.6 U fixed
10241 0 NMOS10MH/NMOSD10MH Element Rule X4 : sptub dntub spacing 0.2 U fixed
10248 0 NMOS10MH/NMOSD10MH Element Rule X5 : sptub sntub spacing 0.2 U fixed
10255 0 NMOSD10MH Element Rule X6 : spacing gate pplus  0.3 U fixed
10264 0 NMOS10MH/NMOSD10MH Element Rule Y1 : spacing poly drain diff 0.2
10273 0 NMOS10MH/NMOSD10MH Element Rule Y2 : ovlp hvox  drain diff 0.6
10282 0 NMOS10MH/NMOSD10MH Element Rule Y3 : ovlp sntub drain diff 0.75
10289 0 NMOS10MH Y4 Element Rule : poly width of gate connect = 1.3
10296 0 NMOS10MH/NMOSD10MH Element Rule Y5 : spac drain diff to bulk ndiff  1.8
10311 0 NMOS10MH/NMOSD10MH Element Rule Y6 : spac dptub to sntub  0.2
10318 0 NMOS10MH/NMOSD10MH Element Rule Y7 : spac sptub to sntub  0.2
10320 0 NMOS10MH/NMOSD10MH Y8 Element Rule : poly must be angled
10322 0 NMOS10MH/NMOSD10MH Y8 Element Rule : 45 degree poly must have length 0.4 * sqrt(2)
10324 0 NMOS10MH_Y9 Element Rule : sntub must be angled
10326 0 NMOS10MH/NMOSD10MH Y9 Element Rule : 45 degree sntub must have length 0.4 * sqrt(2)
10342 0 NMOSD10MH Y10 : Minimum NDIFF enclosure of NDIFFCON = 0.2
10347 0 NMOSD10MH Y11 : Minimum PPLUS enclosure of NDIFFCON = 0.2
10349 0 NMOSD10MH Element Rule Y12 : fixed size of butting pdiff square 9.9 x 0.9
10352 0 NMOSD10MH INFO : min spacing of butting pdiff to pdiff 1.6 U
10353 0 NMOSD10MH/NMOS10MH missing or bad HVOX on device
10354 0 NMOSD10MH/NMOS10MH missing or bad MIDOX on device
10372 0  L3R001: NLD20V outside HVDEF is not allowed
10373 0 NMOSFI25H illegal device : NLD20V must be drawn on device !!!!
10407 0 NMOSFI25H L Element Rule : Min gate length = Minimum CHANNEL length = 0.6 U
10410 0 NMOSFI25H W2 Element Rule : Min gate width/2 = Minimum CHANNEL width/2 = 5 U
10417 0 NMOSFI25H X1 Element Rule : drain nplus width = 1 U fixed
10426 0 NMOSFI25H X2 Element Rule : poly1 spacing to drain ndiff = 1.0 U
10435 0 NMOSFI25H X3 Element Rule : nld20v enc of drain ndiff = 2.5 U
10439 0 NMOSFI25H X4  Element Rule : RPTUB to DIFF vertex spacing = 0.4
10451 0 NMOSFI25H X5 Element Rule : nld20v to rptub spacing = 0.4 U
10458 0 NMOSFI25H X6 Element Rule : NPLUS overlap of POLY1 = 0.45
10474 0 NMOSFI25H X7 Element Rule : rptub enc of bulk pdiff = 0.8/0.2 U
10483 0 NMOSFI25H X8 Element Rule : DPTUB enclosure of RPTUB = 1.1 
10485 0 NMOSFI25H X9 Element Rule :  SNTUB to DPTUB spacing = 0
10492 0 NMOSFI25H X10 Y8Element Rule :  NDIFF width = 1.8  (ntap in sntub)
10501 0 NMOSFI25H Y1 Element Rule :  DIFF enclosure of DRAIN-NPLUS = 2.5
10510 0 NMOSFI25H Y2 Element Rule : NLD20V enclosure of DRAIN-NPLUS = 2.5
10515 0 NMOSFI25H Y3 Element Rule :POLY1 width of gate connection = 0.8
10522 0 NMOSFI25H Y4 Element Rule : RPTUB to DIFF spacing = 1.1
10534 0 NMOSFI25H X11 Y12 Element Rule : rptub iso to dntub spacing = 4.5
10535 0 NMOSFI25H X11 Element Rule : rptub iso is missing
10538 0 NMOSFI25H X12 Element Rule : rptub width of iso guard ring = 4.5
10541 0 NMOSFI25H X13 Element Rule : RPTUB iso ovlp of pdiff = 1
10543 0 NMOSFI25H Y11 Element Rule : poly must be angled
10545 0 NMOSFI25H Y11 Element Rule : 45 degree poly must have length 0.1
10547 0 NMOSFI25H Y10 Element Rule : nld20v must be angled
10549 0 NMOSFI25H Y10 Element Rule : 45 degree nld20v must have length 1.7
10551 0 NMOSFI25H Y9 Element Rule : 45 degree drain diff must have length 1.7
10596 0 NMOSFI25H illegal device : NLD20V must be drawn on device !!!!
10599 0 NMOSFI25H L Element Rule : Minimum CHANNEL length = 1.4 U
10602 0 NMOSFI25H W Element Rule : Minimum CHANNEL width/2 = 5 U
10609 0 NMOSFI25HS X1 Element Rule : drain nplus width = 1 U fixed
10618 0 NMOSFI25HS X2 Element Rule : POLY1 to DRAIN-NPLUS spacing = 1.0 U fixed
10627 0 NMOSFI25HS X3 Element Rule : nld20v enc of drain ndiff = 2.5 U
10636 0 NMOSFI25HS Y1 Element Rule :  DIFF enclosure of DRAIN-NPLUS = 2.5
10645 0 NMOSFI25H Y2 Element Rule : NLD20V enclosure of DRAIN-NPLUS = 2.5
10647 0 NMOSFI25HS Y11 Element Rule : poly hole must be rectangle 1 U
10654 0 NMOSFI25HS Y12 Element Rule : poly hole must must fixed spacing 4 U
10665 0 CWPM W Element Rule : Minimum CWPM width 10
10672 0 CWPM X1 Element Rule : ovlp rptub poly 1
10673 0 CWPM X1 Element Rule : missing rptub
10675 0 CWPM Element Rule : CWPM rptub iso is missing
10691 0 CWPM Element check: met3/met1 plates of CWPM not connected correctly
10692 0 CWPM Element check: met2/poly1 plates of CWPM not connected correctly
10693 0 CWPM Element check : ptub/dntub of CWPM not connected correctly
10710 0 CPM Element check: met3/met1 plates of CPM not connected correctly
10711 0 CPM Element check: met2/poly1 plates of CPM not connected correctly
10737 0 VERTN1_P1 Element Rule : EMITTER-NDIFF perimeter / 4 = 1.5
10748 0 VERTN1_P2 Element Rule : BASE-RPTUB perimeter / 4 = 6.7
10750 0 VERTN1_P3 Element Rule : COLLECTOR-DNTUB perimeter / 4 = 15.7
10752 0 VERTN1_P4 Element Rule : SUBSTRATE-RPTUB ring inside perimeter / 4 = 24.7
10759 0 VERTN1_X1 Element Rule : EMITTER-NDIFF to BASE-PDIFF spacing = 0.65
10766 0 VERTN1_X2 Element Rule : BASE-RPTUB to COLLECTOR-NDIFF spacing = 1.2
10773 0 VERTN1_X3 Element Rule : COLLECTOR-NDIFF width = 1.8
10774 0 VERTN1 X4 Element Rule : VERTN1 rptub iso is missing
10777 0 VERTN1 X4 Element Rule : rptub width of iso guard ring 4.5
10787 0 VERTN1 X5 Element Rule : RPTUB iso ovlp of pdiff = 1
10803 0 VERTPH_X1 Element Rule : EMITTER-SPTUB edge = 3.5
10805 0 VERTPH_Y1 Element Rule : EMITTER-SPTUB edge = 46
10812 0 VERTPH_X2 Element Rule : EMITTER-DPTUB edge = 7.5
10814 0 VERTPH_Y2 Element Rule : EMITTER-DPTUB edge = 50
10821 0 VERTPH_X3 Element Rule : BASE-DNTUB edge = 12.7
10823 0 VERTPH_Y3 Element Rule : BASE-DNTUB edge = 55.2
10830 0 VERTPH_X4 Element Rule : COLLECTOR-RPTUB edge = 21.7
10832 0 VERTPH_Y4 Element Rule : COLLECTOR-RPTUB edge = 64.2
10833 0 VERTPH X5 Element Rule : VERTPH rptub iso is missing
10835 0 VERTPH X5 Element Rule : rptub width of iso guard ring 4.5
10845 0 VERTPH X6 Element Rule : RPTUB iso ovlp of pdiff = 1
10866 0 PJFET_ERC_Warning__PJFET_source_must_be_connected_together
10871 0 PJFET_W Element Rule : Minimum DPTUB width = 9
10878 0 PJFET X1 Element Rule : DPTUB to SNTUB spacing = 1.5
10887 0 PJFET X2 Element Rule : DPTUB enclosure of SPTUB = 2
10894 0 PJFET_X3 Element Rule : SPTUB width = 1.1
10901 0 PJFET X4 Element Rule : SPTUB to SNTUB spacing = 2
10908 0 PJFET X5 Element Rule : SNTUB width = 2.5
10918 0 PJFET Y1 Element Rule : NDIFF spacing = 9.3
10927 0 RNWELLS W Element Rule : min width = 4
10930 0 RNWELLS X1 Element Rule : nplus enclosure of cont = 0.4
10933 0 RNWELLS Y1 Element Rule : sntub enclosure of nplus = 0.5
10942 0 RNWELLS Y2 Element Rule : diff enclosure of sntub = 1
10944 0 RNWELLS Y2 Element Rule : missing or bad diff 
10947 0 RNWELLS_R1 MET1 and (RNWELLS and not NPLUS) is not allowed
10957 0 RPWELLR W Element Rule : min width = 2
10966 0 RPWELLR Element Rule : DPTUB ovlp SPTUB = 1.5
10974 0 RPWELLR Y1 Element Rule : bad dptub ovlp
10976 0 RPWELLR Y2 Element Rule : DIFF must be on res body
10979 0 RPWELLR_R1 MET1 and (RPWELLR and not PPLUS) is not allowed
10985 0 CMIM20_R1 Maximum total area on design [mm2] = 0.5
10991 0 ESDGCI3_L Element Rule : Inner EMITTER-NDIFF length = 1
10992 0 ESDGCI3_W1 Element Rule : Minimum inner EMITTER-NDIFF width = 10
10993 0 ESDGCI3_W2 Element Rule : Maximum inner EMITTER-NDIFF width = 200
11009 0 ESDGCI3_X1 Element Rule : GATE length = 1
11016 0 ESDGCI3_X2 Element Rule : COLLECTOR-NDIFF length = 0.85
11030 0 ESDGCI3_X3 Element Rule : SPTUB enclosure of NDIFF = 1.5
11037 0 ESDGCI3_X4 Element Rule : SPTUB to SNTUB spacing = 0.2
11044 0 ESDGCI3_X5 Element Rule : SNTUB width = 1.1
11047 0 ESDGCI3_X6 Element Rule : Minimum DNTUB extension of SNTUB = 2.55
11054 0 ESDGCNI5_L Element Rule : CATHODE-NDIFF length = 0.7
11058 0 ESDGCNI5_W2 Element Rule : Maximum CATHODE-NDIFF width = 100
11065 0 ESDGCNI5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
11072 0 ESDGCNI5_X3 Element Rule : PDIFF width = 0.7
11081 0 ESDGCNI5_X4 Element Rule : RPTUB enclosure of PDIFF = 0.3
11091 0 ESDGCNI5_X5 Element Rule : RPTUB to SNTUB spacing = 0.1
11098 0 ESDGCNI5_X6 Element Rule : SNTUB width = 1.1
11101 0 ESDGCNI5_X7 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.8
11106 0 ESDFDI50_L Element Rule : DPTUB length = 7.6
11107 0 ESDFDI50_W1 Element Rule : Minimum DPTUB width = 10
11108 0 ESDFDI50_W2 Element Rule : Maximum DPTUB width = 200
11117 0 ESDFDI50_X1 ESDFDI50_X2 Element Rule : SPTUB enclosure of PDIFF = 0.7
11126 0 ESDFDI50_Y1 ESDFDI50_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.2
11135 0 ESDFDI50_X2 Element Rule : DPTUB enclosure of SPTUB = 1.3
11144 0 ESDFDI50_Y2 Element Rule : DPTUB enclosure of SPTUB = 1.8
11151 0 ESDFDI50_X3 Element Rule : SNTUB to DPTUB spacing = 2
11158 0 ESDFDI50_Y3 Element Rule : SNTUB to DPTUB spacing = 3
11168 0 ESDFDI50_X4 Element Rule : SNTUB width = 1.1
11171 0 ESDFDI50_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.1
11174 0 ESDFDI50_X6 Element Rule :  Minimum CATHODE-MET1 width = 2
11190 0 ESDTD20 Element Rule : SPTUB/DPTUB not identical over device
11195 0 ESDTD20_W1 Element Rule : Minimum RPTUB width = 10
11196 0 ESDTD20_W2 Element Rule : Maximum RPTUB width = 200
11199 0 ESDTD20_X1 Element Rule : Minimum PDIFF enclosure of CONT = 3.6
11208 0 ESDTD20_X2 Element Rule : RPTUB enclosure of PDIFF = 0.5
11215 0 ESDTD20_X3  Element Rule : SNTUB to RPTUB spacing = 0.2
11217 0 ESDTD20_X4 Element Rule : Minimum SNTUB width = 1.1
11220 0 ESDTD20_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.8
11225 0 ESDTD50_L Element Rule : DPTUB length = 8.6
11226 0 ESDTD50_W1 Element Rule : Minimum DPTUB width = 10
11227 0 ESDTD50_W2 Element Rule : Maximum DPTUB width = 200
11236 0 ESDTD50_X1 ESDTD50_X2 Element Rule : SPTUB enclosure of PDIFF = 1
11245 0 ESDTD50_Y1 ESDTD50_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.5
11254 0 ESDTD50_X2 Element Rule : DPTUB enclosure of SPTUB = 1
11263 0 ESDTD50_Y2 Element Rule : DPTUB enclosure of SPTUB = 2
11270 0 ESDTD50_X3 Element Rule : SNTUB to DPTUB spacing = 1.5
11277 0 ESDTD50_Y3 Element Rule : SNTUB to DPTUB spacing = 2.5
11283 0 ESDTD50_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.05
11288 0 ESDTD40_L Element Rule : DPTUB length = 8.6
11289 0 ESDTD40_W1 Element Rule : Minimum DPTUB width = 10
11290 0 ESDTD40_W2 Element Rule : Maximum DPTUB width = 200
11299 0 ESDTD40_X1 ESDTD40_X2 Element Rule : SPTUB enclosure of PDIFF = 1
11308 0 ESDTD40_Y1 ESDTD40_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.5
11317 0 ESDTD40_X2 Element Rule : DPTUB enclosure of SPTUB = 1
11326 0 ESDTD40_Y2 Element Rule : DPTUB enclosure of SPTUB = 2
11333 0 ESDTD40_X3 Element Rule : SNTUB to DPTUB spacing = 1.5
11340 0 ESDTD40_Y3 Element Rule : SNTUB to DPTUB spacing = 2.5
11346 0 ESDTD40_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.05
11351 0 ESDTD42_L Element Rule : DPTUB length = 8.6
11352 0 ESDTD42_W1 Element Rule : Minimum DPTUB width = 10
11353 0 ESDTD42_W2 Element Rule : Maximum DPTUB width = 200
11362 0 ESDTD42_X1 ESDTD42_X2 Element Rule : SPTUB enclosure of PDIFF = 1
11371 0 ESDTD42_Y1 ESDTD42_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.5
11380 0 ESDTD42_X2 Element Rule : DPTUB enclosure of SPTUB = 1
11389 0 ESDTD42_Y2 Element Rule : DPTUB enclosure of SPTUB = 2
11396 0 ESDTD42_X3 Element Rule : SNTUB to DPTUB spacing = 1.5
11403 0 ESDTD42_Y3 Element Rule : SNTUB to DPTUB spacing = 2.5
11409 0 ESDTD42_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.05
11414 0 ESDTD45_L Element Rule : DPTUB length = 8.6
11415 0 ESDTD45_W1 Element Rule : Minimum DPTUB width = 10
11416 0 ESDTD45_W2 Element Rule : Maximum DPTUB width = 200
11425 0 ESDTD45_X1 ESDTD45_X2 Element Rule : SPTUB enclosure of PDIFF = 1
11434 0 ESDTD45_Y1 ESDTD45_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.5
11443 0 ESDTD45_X2 Element Rule : DPTUB enclosure of SPTUB = 1
11452 0 ESDTD45_Y2 Element Rule : DPTUB enclosure of SPTUB = 2
11459 0 ESDTD45_X3 Element Rule : SNTUB to DPTUB spacing = 1.5
11466 0 ESDTD45_Y3 Element Rule : SNTUB to DPTUB spacing = 2.5
11472 0 ESDTD45_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.05
11477 0 ESDTD60_L Element Rule : DPTUB length = 8.6
11478 0 ESDTD60_W1 Element Rule : Minimum DPTUB width = 10
11479 0 ESDTD60_W2 Element Rule : Maximum DPTUB width = 200
11488 0 ESDTD60_X1 ESDTD60_X2 Element Rule : SPTUB enclosure of PDIFF = 1
11497 0 ESDTD60_Y1 ESDTD60_Y2 Element Rule : SPTUB enclosure of PDIFF = 1.5
11506 0 ESDTD60_X2 Element Rule : DPTUB enclosure of SPTUB = 1
11515 0 ESDTD60_Y2 Element Rule : DPTUB enclosure of SPTUB = 2
11522 0 ESDTD60_X3 Element Rule : SNTUB to DPTUB spacing = 1.5
11529 0 ESDTD60_Y3 Element Rule : SNTUB to DPTUB spacing = 2.5
11535 0 ESDTD60_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 3.05
11546 0 ESDPD10_L Element Rule : SPTUB hole length = 1.5
11547 0 ESDPD10_W1 Element Rule : Minimum SPTUB hole width = 10
11548 0 ESDPD10_W2 Element Rule : Maximum SPTUB hole width = 200
11555 0 ESDPD10_X1 Element Rule : SPTUB width = 1.1
11564 0 ESDPD10_X2 Element Rule : SPTUB extension of PDIFF = 0.5
11571 0 ESDPD10_X3 Element Rule : NDIFF to SPTUB spacing = 0.5
11574 0 ESDPD10_X4 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.1
11589 0 ESDPD10 Element Rule X5 : Minimum CATHODE-MET1 width = 1.4
11599 0 ESDPNP40_L Element Rule : DPTUB length = 8.6
11600 0 ESDPNP40_W1 Element Rule : Minimum DPTUB width = 50
11601 0 ESDPNP40_W2 Element Rule : Maximum DPTUB width = 300
11610 0 ESDPNP40 Element Rule X1 : SPTUB enclosure of PDIFF = 1
11619 0 ESDPNP40 Element Rule X2 : DPTUB enclosure of SPTUB = 1
11626 0 ESDPNP40 Element Rule X3 : SNTUB to DPTUB spacing = 1.5
11628 0 ESDPNP40 Element Rule X4 : Minimum SNTUB width = 1.2
11631 0 ESDPNP40 Element Rule X5 : Minimum DNTUB enclosure of SNTUB = 3
11643 0 ESDPNP40 Element Rule X6 : SNTUB enclosure of NDIFF (inside) = 0.3
11646 0 ESDPNP40 Element Rule X7 : Minimum BASE-MET1 width = 2
11655 0 ESDPNP40 Element Rule X8 : COLLECTOR-EMITTER DPTUB spacing = 4.3
11665 0 ESDPNP42_L Element Rule : DPTUB length = 8.6
11666 0 ESDPNP42_W1 Element Rule : Minimum DPTUB width = 50
11667 0 ESDPNP42_W2 Element Rule : Maximum DPTUB width = 300
11676 0 ESDPNP42 Element Rule X1 : SPTUB enclosure of PDIFF = 1
11685 0 ESDPNP42 Element Rule X2 : DPTUB enclosure of SPTUB = 1
11692 0 ESDPNP42 Element Rule X3 : SNTUB to DPTUB spacing = 1.5
11694 0 ESDPNP42 Element Rule X4 : Minimum SNTUB width = 1.2
11697 0 ESDPNP42 Element Rule X5 : Minimum DNTUB enclosure of SNTUB = 3
11709 0 ESDPNP42 Element Rule X6 : SNTUB enclosure of NDIFF (inside) = 0.3
11712 0 ESDPNP42 Element Rule X7 : Minimum BASE-MET1 width = 2
11721 0 ESDPNP42 Element Rule X8 : COLLECTOR-EMITTER DPTUB spacing = 4.3
11736 0 ESDPD18_L Element Rule : CATHODE-NTUB length = 1.7
11737 0 ESDPD18_W1 Element Rule : Minimum CATHODE-NTUB width = 10
11738 0 ESDPD18_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
11747 0 ESDPD18_X2 Element Rule : NTUB enclosure of NDIFF = 0.5
11756 0 ESDPD18_Y2 Element Rule : NTUB enclosure of NDIFF = 1.5
11763 0 ESDPD18_X3 Element Rule : PDIFF to NTUB spacing = 0.5
11770 0 ESDPD18_Y3 Element Rule : PDIFF to NTUB spacing = 2
11777 0 ESDPD18_X4 Element Rule : PDIFF width = 0.7
11780 0 ESDPD18_X5 Element Rule : Minimum CATHODE-MET1 width = 1.6
11797 0 ESDPD26_L Element Rule : CATHODE-NTUB length = 2.1
11798 0 ESDPD26_W1 Element Rule : Minimum CATHODE-NTUB width = 10
11799 0 ESDPD26_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
11808 0 ESDPD26_X2 Element Rule : NTUB enclosure of NDIFF = 0.7
11817 0 ESDPD26_Y2 Element Rule : NTUB enclosure of NDIFF = 1.7
11824 0 ESDPD26_X3 Element Rule : PDIFF to NTUB spacing = 1
11831 0 ESDPD26_Y3 Element Rule : PDIFF to NTUB spacing = 2
11838 0 ESDPD26_X4 Element Rule : PDIFF width = 0.7
11841 0 ESDPD26_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
11858 0 ESDPD30_L Element Rule : CATHODE-NTUB length = 2.3
11859 0 ESDPD30_W1 Element Rule : Minimum CATHODE-NTUB width = 10
11860 0 ESDPD30_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
11869 0 ESDPD30_X2 Element Rule : NTUB enclosure of NDIFF = 0.8
11878 0 ESDPD30_Y2 Element Rule : NTUB enclosure of NDIFF = 1.8
11885 0 ESDPD30_X3 Element Rule : PDIFF to NTUB spacing = 1.5
11892 0 ESDPD30_Y3 Element Rule : PDIFF to NTUB spacing = 2
11899 0 ESDPD30_X4 Element Rule : PDIFF width = 0.7
11902 0 ESDPD30_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
11920 0 ESDFDPI5_L Element Rule : ANODE-PDIFF length = 0.7
11921 0 ESDFDPI5_W1 Element Rule : Minimum ANODE-PDIFF width = 10
11922 0 ESDFDPI5_W2 Element Rule : Maximum ANODE-PDIFF width = 200
11929 0 ESDFDPI5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
11936 0 ESDFDPI5_X3 Element Rule : NDIFF width = 0.7
11945 0 ESDFDPI5_X4 Element Rule : SNTUB enclosure of NDIFF = 0.2
11948 0 ESDFDPI5_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.8
11979 0 ESDGCPI5_L Element Rule : ANODE-PDIFF length = 0.7
11980 0 ESDGCPI5_W1 Element Rule : Minimum ANODE-PDIFF width = 0.7
11981 0 ESDGCPI5_W2 Element Rule : Maximum ANODE-PDIFF width = 100
11988 0 ESDGCPI5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
11995 0 ESDGCPI5_X3 Element Rule : NDIFF width = 0.7
12004 0 ESDGCPI5_X4 Element Rule : SNTUB enclosure of NDIFF = 0.2
12007 0 ESDGCPI5_X5 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.8
12034 0 ESDFDNI5_L Element Rule : CATHODE-NDIFF length = 0.7
12035 0 ESDFDNI5_W1 Element Rule : Minimum CATHODE-NDIFF width = 10
12036 0 ESDFDNI5_W2 Element Rule : Maximum CATHODE-NDIFF width = 200
12043 0 ESDFDNI5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
12050 0 ESDFDNI5_X3 Element Rule : PDIFF width = 0.7
12059 0 ESDFDNI5_X4 Element Rule : RPTUB enclosure of PDIFF = 0.3
12066 0 ESDFDNI5_X5 Element Rule : RPTUB to SNTUB spacing = 0.1
12073 0 ESDFDNI5_X6 Element Rule : SNTUB width = 1.1
12076 0 ESDFDNI5_X7 Element Rule : Minimum DNTUB enclosure of SNTUB = 2.8
12091 0 ESDFDP5_L Element Rule : ANODE-PDIFF length = 0.7
12092 0 ESDFDP5_W1 Element Rule : Minimum ANODE-PDIFF width = 10
12093 0 ESDFDP5_W2 Element Rule : Maximum ANODE-PDIFF width = 200
12100 0 ESDFDP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
12107 0 ESDFDP5_X3 Element Rule : NDIFF width = 0.7
12120 0 ESDFDN5_L Element Rule : CATHODE-NDIFF length = 0.7
12121 0 ESDFDN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 10
12122 0 ESDFDN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 200
12129 0 ESDFDN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
12136 0 ESDFDN5_X3 Element Rule : PDIFF width = 0.7
12162 0 ESDGCN5_L Element Rule : CATHODE-NDIFF length = 0.7
12163 0 ESDGCN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 0.7
12164 0 ESDGCN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 100
12171 0 ESDGCN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
12178 0 ESDGCN5_X3 Element Rule : PDIFF width = 0.7
12206 0 ESDGCP5_L Element Rule : ANODE-PDIFF length = 0.7
12207 0 ESDGCP5_W1 Element Rule : Minimum ANODE-PDIFF width = 0.7
12208 0 ESDGCP5_W2 Element Rule : Maximum ANODE-PDIFF width = 100
12215 0 ESDGCP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
12222 0 ESDGCP5_X3 Element Rule : NDIFF width = 0.7
12224 0 ESDGCI20_L ESDGCI20_W1 Element Rule : SNTUB length = 5
12231 0 ESDGCI20_L Element Rule : SNTUB length = 5
12232 0 ESDGCI20_W2 Element Rule : Maximum SNTUB width = 100
12241 0 ESDGCI20_X1 Element Rule : SNTUB enclosure of NDIFF = 0.3
12250 0 ESDGCI20_Y1 Element Rule : SNTUB enclosure of NDIFF = 0.75
12254 0 ESDGCI20 X2 Element Rule : RPTUB to SNTUB spacing = 0
12264 0 ESDGCI20_X3 Element Rule : RPTUB width = 2.9
12273 0 ESDGCI20_Y3 Element Rule : RPTUB width = 2.7
12280 0 ESDGCI20_X4 Element Rule : RPTUB enclosure of PDIFF = 1.2
12287 0 ESDGCI20_Y4 Element Rule : RPTUB enclosure of PDIFF = 1
12294 0 ESDGCI20_X5 Element Rule : SNTUB to RPTUB spacing = 0.5
12304 0 ESDGCI20_X6 Element Rule : SNTUB width = 1.1
12307 0 ESDGCI20_X7 Element Rule : Minimum DNTUB enclosure of SNTUB = 3
12308 0 INFO: ESDVSD HVDEF
12312 0 ESDVSD_REV : HVR001 : Version of ESDVSD obsolete or missing
12317 0 ESDVSD_L Element Rule : Min pdiff length = 4.6 U
12318 0 ESDVSD_W1 Element Rule : Min pdiff width = 25.0 U
12319 0 ESDVSD_W2 Element Rule : Max pdiff width = 199.0 U
12328 0 ESDVSD_X1 Element Rule : SPTUB enc pdiff 0.5 U
12337 0 ESDVSD_Y1 Element Rule : SPTUB enc pdiff 0.75 U
12344 0 ESDVSD_X2 Element Rule : SNTUB width 1.2 U
12347 0 ESDVSD_X3 Element Rule X3 : min DNTUB ovlp SNTUB  3.05
12348 0 INFO: ESDVSS HVDEF
12352 0 ESDVSS_REV : HVR001 : Version of ESDVSS obsolete or missing
12357 0 ESDVSS_L Element Rule : Min pdiff length = 4.6 U
12358 0 ESDVSS_W1 Element Rule : Min pdiff width = 25.0 U
12359 0 ESDVSS_W2 Element Rule : Max pdiff width = 199.0 U
12368 0 ESDVSS_X1 Element Rule : SPTUB enc pdiff 0.5 U
12377 0 ESDVSS_Y1 Element Rule : SPTUB enc pdiff 0.75 U
12384 0 ESDVSS_X2 Element Rule : SNTUB width 1.2 U
12387 0 ESDVSS_X3 Element Rule X3 : min DNTUB ovlp SNTUB  3.05
12389 0 W1PO Minimum TRENCH_POM width = 14
12392 0 S1POPO Minimum TRENCH_POM spacing = 13.5
12395 0 E1PODP Minimum TRENCH_POM enclosure of PHD_GUARD = 12
12398 0 E1PODP TRENCH_POM must only be drawn over diode or PHD_GUARD
12400 0 S1DNPO Minimum DNTUB to TRENCH_POM spacing = 50
12401 0 S1DNPO Minimum DNTUB to TRENCH_POM spacing = 50
12403 0 S1PORP Minimum RPTUB to TRENCH_POM spacing = 2
12405 0 S1PORP TRENCH_POM must not be drawn over rptub
12406 0 TRENCH_POM not over phd device
12407 0 DNR009 DNTUB overlapping TRENCH_POM is not allowed
12413 0 S4DNDN Minimum DNTUB spacing = 22 sep notch
12414 0 SPR004 SPTUB overlapping TRENCH_POM is not allowed
12422 0 DPR004 PHD_GUARD must be fully enclosed with RPTUB
12429 0  W3DP Minimum (RPTUB enclosing PHD_GUARD) width = 45
12435 0 PHR001 PHDPINB750 : Illegal layer on photo diode OPTDEF  poly1/poly2/met1/met2/met3/met4
12436 0 PHR001 PHDPINB750 : Illegal layer on photo diode  OPTDEF : met4
12447 0 PHDPINB750  : ndiff must not enclose any other data
12449 0 PHDPINB750 : text label for light terminal (P) missing on top level of hierarchie , please add label with terminal name on layer DEVDEF opto for correct extraction
12455 0 BRR001 PHDPINB750 : Illegal layer on photo diode PAD_BARC  poly1/poly2/met1/met2/met3/met4
12456 0 BRR001 PHDPINB750 : Illegal layer on photo diode PAD_BARC : met4
12458 0 W1BR PHDPIN750 : Fixed PAD_BARC width = 27.9
12460 0 Fixed PAD_BARC width = 27.9
12463 0 S1BRBR : Fixed PAD_BARC spacing = 7.5
12465 0 ILL_LAYER_CHIPEDGE chipedge is only used for testing purposes
12477 0 S1BRBR  Fixed PAD_BARC spacing = 7.5
12479 0 S1BRM1 : Minimum MET1 to PAD_BARC spacing = 1.1
12481 0 S1BRM2 : Minimum MET2 to PAD_BARC spacing = 1.4
12483 0 S1BRM3 : Minimum MET3 to PAD_BARC spacing = 1.6
12485 0 S1BRM4 : Minimum MET4 to PAD_BARC spacing = 2.3
12487 0 INFO: PHDPINB750
12488 0 PHDPINB750 : Version of DEVDEF_OPTO obsolete or missing
12489 0 PHDPINB750 : illegal name on DEVDEF_OPTO or text missing
12492 0 PHDPINB750_W1 PHDPINB750_L1 : Fixed PAD_BARC width = 27.9 Fixed PAD_BARC length = 783.5
12501 0 PHDPINB750_S1 : Fixed PAD_BARC spacing = 7.5
12509 0 PHDPINB750_S1 : Fixed PAD_BARC spacing = 7.5
12510 0 PHDPINB750 : TRENCH_POM not over PHDPINB750 device
12517 0 PHDPINB750_X1 : DPTUB width = 3
12529 0 PHDPINB750_X2 : PDIFF width = 0.5
12537 0 PHDPINB750_X3 : DPTUB enclosure of PDIFF (inside) = 1.25
12546 0 PHDPINB750_X4 : NDIFF to DPTUB spacing = 1.25
12556 0 PHDPINB750_X6 : DEVDEF_opto enclosure of PAD_BARC = 1
12565 0 PHDPINB750_X5 : NDIFF enclosure of PAD_BARC = 1
12576 0 PHDPINB750_Y1 : NDIFF enclosure of PAD_BARC = 8
12584 0 PHDPINB750_Y2 : PAD_BARC to MET1 spacing = 7.1
12595 0 PHDPINB750_E1 : Fixed PPLUS enclosure of PDIFF = 0.25
12606 0 PHDPINB750_E2 : Fixed NPLUS enclosure of NDIFF = 0.25
12609 0  pad definition out pad
12610 0 Warning : pad definition does not interact pad layer
12630 0 SN_PS_R1 : (SN_PS and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12652 0 DN_PS_R1 : (DN_PS and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12663 0 DP_DN_R1 : (DP_DN and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12682 0 ND_SP_R1 : (ND_SP and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12698 0 PD_SN_R1 : (PD_SN and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12726 0 ND_R1 : (ND and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12741 0 PD_R1 : (PD and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12778 0 NWD_R1 : (NWD and not DIODE) must be connected in parallel to a similar diode in a device which is compared in LVS
12794 0 NMOSDIVST_DNX : f = NMOSDIVS600T  DNTUB enclosure of NDIFF = function 1.2 fixed, no common DNTUB allowed
12810 0 NMOSDIVST_DNX : f = NMOSDIVS650T  DNTUB enclosure of NDIFF = function 1.15 fixed, no common DNTUB allowed
12826 0 NMOSDIVST_DNX : f = NMOSDIVS700T  DNTUB enclosure of NDIFF = function 1.125 fixed, no common DNTUB allowed
12842 0 NMOSDIVST_DNX : f = NMOSDIVS750T  DNTUB enclosure of NDIFF = function 1.075 fixed, no common DNTUB allowed
12858 0 NMOSDIVST_DNX : f = NMOSDIVS800T  DNTUB enclosure of NDIFF = function 1.05 fixed, no common DNTUB allowed
12874 0 NMOSDIVST_DNX : f = NMOSDIVS850T  DNTUB enclosure of NDIFF = function 1.025 fixed, no common DNTUB allowed
12890 0 NMOSDIVST_DNX : f = NMOSDIVS900T  DNTUB enclosure of NDIFF = function 0.975 fixed, no common DNTUB allowed
12906 0 NMOSDIVST_DNX : f = NMOSDIVS975T  DNTUB enclosure of NDIFF = function 0.925 fixed, no common DNTUB allowed
12922 0 NMOSDIVST_DNX : f = NMOSDIVS1050T  DNTUB enclosure of NDIFF = function 0.9 fixed, no common DNTUB allowed
12938 0 NMOSDIVST_DNX : f = NMOSDIVS1125T  DNTUB enclosure of NDIFF = function 0.85 fixed, no common DNTUB allowed
12954 0 NMOSDIVST_DNX : f = NMOSDIVS1200T  DNTUB enclosure of NDIFF = function 0.8 fixed, no common DNTUB allowed
12970 0 NMOSDIVST_DNX : f = NMOSDIVS1275T  DNTUB enclosure of NDIFF = function 0.775 fixed, no common DNTUB allowed
12986 0 NMOSDIVST_DNX : f = NMOSDIVS1350T  DNTUB enclosure of NDIFF = function 0.725 fixed, no common DNTUB allowed
13002 0 NMOSDIVST_DNX : f = NMOSDIVS1450T  DNTUB enclosure of NDIFF = function 0.7 fixed, no common DNTUB allowed
13018 0 NMOSDIVST_DNX : f = NMOSDIVS1550T  DNTUB enclosure of NDIFF = function 0.65 fixed, no common DNTUB allowed
13034 0 NMOSDIVST_DNX : f = NMOSDIVS1650T  DNTUB enclosure of NDIFF = function 0.6 fixed, no common DNTUB allowed
13050 0 NMOSDIVST_DNX : f = NMOSDIVS1750T  DNTUB enclosure of NDIFF = function 0.575 fixed, no common DNTUB allowed
13066 0 NMOSDIVST_DNX : f = NMOSDIVS1850T  DNTUB enclosure of NDIFF = function 0.55 fixed, no common DNTUB allowed
13082 0 NMOSDIVST_DNX : f = NMOSDIVS1950T  DNTUB enclosure of NDIFF = function 0.525 fixed, no common DNTUB allowed
13098 0 NMOSDIVST_DNX : f = NMOSDIVS2050T  DNTUB enclosure of NDIFF = function 0.5 fixed, no common DNTUB allowed
13114 0 NMOSDIVST_DNX : f = NMOSDIVS2150T  DNTUB enclosure of NDIFF = function 0.475 fixed, no common DNTUB allowed
13130 0 NMOSDIVST_DNX : f = NMOSDIVS2300T  DNTUB enclosure of NDIFF = function 0.475 fixed, no common DNTUB allowed
13146 0 NMOSDIVST_DNX : f = NMOSDIVS2450T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13162 0 NMOSDIVST_DNX : f = NMOSDIVS2600T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13178 0 NMOSDIVST_DNX : f = NMOSDIVS2750T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13194 0 NMOSDIVST_DNX : f = NMOSDIVS2900T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13210 0 NMOSDIVST_DNX : f = NMOSDIVS3050T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13226 0 NMOSDIVST_DNX : f = NMOSDIVS3200T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13242 0 NMOSDIVST_DNX : f = NMOSDIVS3350T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13258 0 NMOSDIVST_DNX : f = NMOSDIVS3500T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13274 0 NMOSDIVST_DNX : f = NMOSDIVS3650T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13290 0 NMOSDIVST_DNX : f = NMOSDIVS3850T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13306 0 NMOSDIVST_DNX : f = NMOSDIVS4050T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
13322 0 NMOSDIVST_DNX : f = NMOSDIVS4250T  DNTUB enclosure of NDIFF = function 0.525 fixed, no common DNTUB allowed
13338 0 NMOSDIVST_DNX : f = NMOSDIVS4450T  DNTUB enclosure of NDIFF = function 0.6 fixed, no common DNTUB allowed
13354 0 NMOSDIVST_DNX : f = NMOSDIVS4650T  DNTUB enclosure of NDIFF = function 0.65 fixed, no common DNTUB allowed
13370 0 NMOSDIVST_DNX : f = NMOSDIVS4850T  DNTUB enclosure of NDIFF = function 0.725 fixed, no common DNTUB allowed
13386 0 NMOSDIVST_DNX : f = NMOSDIVS5050T  DNTUB enclosure of NDIFF = function 0.8 fixed, no common DNTUB allowed
13402 0 NMOSDIVST_DNX : f = NMOSDIVS5250T  DNTUB enclosure of NDIFF = function 0.875 fixed, no common DNTUB allowed
13418 0 NMOSDIVST_DNX : f = NMOSDIVS5450T  DNTUB enclosure of NDIFF = function 0.95 fixed, no common DNTUB allowed
13434 0 NMOSDIVST_DNX : f = NMOSDIVS5650T  DNTUB enclosure of NDIFF = function 1.025 fixed, no common DNTUB allowed
13450 0 NMOSDIVST_DNX : f = NMOSDIVS5850T  DNTUB enclosure of NDIFF = function 1.075 fixed, no common DNTUB allowed
13466 0 NMOSDIVST_DNX : f = NMOSDIVS6050T  DNTUB enclosure of NDIFF = function 1.15 fixed, no common DNTUB allowed
13482 0 NMOSDIVST_DNX : f = NMOSDIVS6250T  DNTUB enclosure of NDIFF = function 1.175 fixed, no common DNTUB allowed
13498 0 NMOSDIVST_DNX : f = NMOSDIVS6450T  DNTUB enclosure of NDIFF = function 1.225 fixed, no common DNTUB allowed
13514 0 NMOSDIVST_DNX : f = NMOSDIVS6650T  DNTUB enclosure of NDIFF = function 1.275 fixed, no common DNTUB allowed
13530 0 NMOSDIVST_DNX : f = NMOSDIVS6850T  DNTUB enclosure of NDIFF = function 1.325 fixed, no common DNTUB allowed
13546 0 NMOSDIVST_DNX : f = NMOSDIVS7050T  DNTUB enclosure of NDIFF = function 1.35 fixed, no common DNTUB allowed
13562 0 NMOSDIVST_DNX : f = NMOSDIVS7250T  DNTUB enclosure of NDIFF = function 1.4 fixed, no common DNTUB allowed
13578 0 NMOSDIVST_DNX : f = NMOSDIVS7450T  DNTUB enclosure of NDIFF = function 1.45 fixed, no common DNTUB allowed
13594 0 NMOSDIVST_DNX : f = NMOSDIVS7650T  DNTUB enclosure of NDIFF = function 1.5 fixed, no common DNTUB allowed
13610 0 NMOSDIVST_DNX : f = NMOSDIVS7850T  DNTUB enclosure of NDIFF = function 1.55 fixed, no common DNTUB allowed
13626 0 NMOSDIVST_DNX : f = NMOSDIVS8050T  DNTUB enclosure of NDIFF = function 1.575 fixed, no common DNTUB allowed
13642 0 NMOSDIVST_DNX : f = NMOSDIVS8250T  DNTUB enclosure of NDIFF = function 1.625 fixed, no common DNTUB allowed
13658 0 NMOSDIVST_DNX : f = NMOSDIVS8450T  DNTUB enclosure of NDIFF = function 1.675 fixed, no common DNTUB allowed
13674 0 NMOSDIVST_DNX : f = NMOSDIVS8650T  DNTUB enclosure of NDIFF = function 1.725 fixed, no common DNTUB allowed
13690 0 NMOSDIVST_DNX : f = NMOSDIVS8850T  DNTUB enclosure of NDIFF = function 1.75 fixed, no common DNTUB allowed
13706 0 NMOSDIVST_DNX : f = NMOSDIVS9050T  DNTUB enclosure of NDIFF = function 1.8 fixed, no common DNTUB allowed
13722 0 NMOSDIVST_DNX : f = NMOSDIVS9250T  DNTUB enclosure of NDIFF = function 1.85 fixed, no common DNTUB allowed
13738 0 NMOSDIVST_DNX : f = NMOSDIVS9450T  DNTUB enclosure of NDIFF = function 1.9 fixed, no common DNTUB allowed
13741 0 Sorry, this nmosdivst F is not supported, check for correct F value 
13757 0 NMOSIVST_DNX : f = NMOSIVS600T  DNTUB enclosure of NDIFF = function 0.975 fixed, no common DNTUB allowed
13773 0 NMOSIVST_DNX : f = NMOSIVS650T  DNTUB enclosure of NDIFF = function 0.95 fixed, no common DNTUB allowed
13789 0 NMOSIVST_DNX : f = NMOSIVS700T  DNTUB enclosure of NDIFF = function 0.925 fixed, no common DNTUB allowed
13805 0 NMOSIVST_DNX : f = NMOSIVS750T  DNTUB enclosure of NDIFF = function 0.9 fixed, no common DNTUB allowed
13821 0 NMOSIVST_DNX : f = NMOSIVS800T  DNTUB enclosure of NDIFF = function 0.85 fixed, no common DNTUB allowed
13837 0 NMOSIVST_DNX : f = NMOSIVS850T  DNTUB enclosure of NDIFF = function 0.825 fixed, no common DNTUB allowed
13853 0 NMOSIVST_DNX : f = NMOSIVS900T  DNTUB enclosure of NDIFF = function 0.8 fixed, no common DNTUB allowed
13869 0 NMOSIVST_DNX : f = NMOSIVS975T  DNTUB enclosure of NDIFF = function 0.775 fixed, no common DNTUB allowed
13885 0 NMOSIVST_DNX : f = NMOSIVS1050T  DNTUB enclosure of NDIFF = function 0.725 fixed, no common DNTUB allowed
13901 0 NMOSIVST_DNX : f = NMOSIVS1125T  DNTUB enclosure of NDIFF = function 0.7 fixed, no common DNTUB allowed
13917 0 NMOSIVST_DNX : f = NMOSIVS1200T  DNTUB enclosure of NDIFF = function 0.675 fixed, no common DNTUB allowed
13933 0 NMOSIVST_DNX : f = NMOSIVS1275T  DNTUB enclosure of NDIFF = function 0.65 fixed, no common DNTUB allowed
13949 0 NMOSIVST_DNX : f = NMOSIVS1350T  DNTUB enclosure of NDIFF = function 0.6 fixed, no common DNTUB allowed
13965 0 NMOSIVST_DNX : f = NMOSIVS1450T  DNTUB enclosure of NDIFF = function 0.575 fixed, no common DNTUB allowed
13981 0 NMOSIVST_DNX : f = NMOSIVS1550T  DNTUB enclosure of NDIFF = function 0.55 fixed, no common DNTUB allowed
13997 0 NMOSIVST_DNX : f = NMOSIVS1650T  DNTUB enclosure of NDIFF = function 0.525 fixed, no common DNTUB allowed
14013 0 NMOSIVST_DNX : f = NMOSIVS1750T  DNTUB enclosure of NDIFF = function 0.5 fixed, no common DNTUB allowed
14029 0 NMOSIVST_DNX : f = NMOSIVS1850T  DNTUB enclosure of NDIFF = function 0.475 fixed, no common DNTUB allowed
14045 0 NMOSIVST_DNX : f = NMOSIVS1950T  DNTUB enclosure of NDIFF = function 0.475 fixed, no common DNTUB allowed
14061 0 NMOSIVST_DNX : f = NMOSIVS2050T  DNTUB enclosure of NDIFF = function 0.475 fixed, no common DNTUB allowed
14077 0 NMOSIVST_DNX : f = NMOSIVS2150T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14093 0 NMOSIVST_DNX : f = NMOSIVS2300T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14109 0 NMOSIVST_DNX : f = NMOSIVS2450T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14125 0 NMOSIVST_DNX : f = NMOSIVS2600T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14141 0 NMOSIVST_DNX : f = NMOSIVS2750T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14157 0 NMOSIVST_DNX : f = NMOSIVS2900T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14173 0 NMOSIVST_DNX : f = NMOSIVS3050T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14189 0 NMOSIVST_DNX : f = NMOSIVS3200T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14205 0 NMOSIVST_DNX : f = NMOSIVS3350T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14221 0 NMOSIVST_DNX : f = NMOSIVS3500T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14237 0 NMOSIVST_DNX : f = NMOSIVS3650T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14253 0 NMOSIVST_DNX : f = NMOSIVS3850T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14269 0 NMOSIVST_DNX : f = NMOSIVS4050T  DNTUB enclosure of NDIFF = function 0.45 fixed, no common DNTUB allowed
14285 0 NMOSIVST_DNX : f = NMOSIVS4250T  DNTUB enclosure of NDIFF = function 0.525 fixed, no common DNTUB allowed
14301 0 NMOSIVST_DNX : f = NMOSIVS4450T  DNTUB enclosure of NDIFF = function 0.6 fixed, no common DNTUB allowed
14317 0 NMOSIVST_DNX : f = NMOSIVS4650T  DNTUB enclosure of NDIFF = function 0.65 fixed, no common DNTUB allowed
14333 0 NMOSIVST_DNX : f = NMOSIVS4850T  DNTUB enclosure of NDIFF = function 0.725 fixed, no common DNTUB allowed
14349 0 NMOSIVST_DNX : f = NMOSIVS5050T  DNTUB enclosure of NDIFF = function 0.8 fixed, no common DNTUB allowed
14365 0 NMOSIVST_DNX : f = NMOSIVS5250T  DNTUB enclosure of NDIFF = function 0.875 fixed, no common DNTUB allowed
14381 0 NMOSIVST_DNX : f = NMOSIVS5450T  DNTUB enclosure of NDIFF = function 0.95 fixed, no common DNTUB allowed
14397 0 NMOSIVST_DNX : f = NMOSIVS5650T  DNTUB enclosure of NDIFF = function 1.025 fixed, no common DNTUB allowed
14413 0 NMOSIVST_DNX : f = NMOSIVS5850T  DNTUB enclosure of NDIFF = function 1.075 fixed, no common DNTUB allowed
14429 0 NMOSIVST_DNX : f = NMOSIVS6050T  DNTUB enclosure of NDIFF = function 1.15 fixed, no common DNTUB allowed
14445 0 NMOSIVST_DNX : f = NMOSIVS6250T  DNTUB enclosure of NDIFF = function 1.175 fixed, no common DNTUB allowed
14461 0 NMOSIVST_DNX : f = NMOSIVS6450T  DNTUB enclosure of NDIFF = function 1.225 fixed, no common DNTUB allowed
14477 0 NMOSIVST_DNX : f = NMOSIVS6650T  DNTUB enclosure of NDIFF = function 1.275 fixed, no common DNTUB allowed
14493 0 NMOSIVST_DNX : f = NMOSIVS6850T  DNTUB enclosure of NDIFF = function 1.325 fixed, no common DNTUB allowed
14509 0 NMOSIVST_DNX : f = NMOSIVS7050T  DNTUB enclosure of NDIFF = function 1.35 fixed, no common DNTUB allowed
14525 0 NMOSIVST_DNX : f = NMOSIVS7250T  DNTUB enclosure of NDIFF = function 1.4 fixed, no common DNTUB allowed
14541 0 NMOSIVST_DNX : f = NMOSIVS7450T  DNTUB enclosure of NDIFF = function 1.45 fixed, no common DNTUB allowed
14557 0 NMOSIVST_DNX : f = NMOSIVS7650T  DNTUB enclosure of NDIFF = function 1.5 fixed, no common DNTUB allowed
14573 0 NMOSIVST_DNX : f = NMOSIVS7850T  DNTUB enclosure of NDIFF = function 1.55 fixed, no common DNTUB allowed
14589 0 NMOSIVST_DNX : f = NMOSIVS8050T  DNTUB enclosure of NDIFF = function 1.575 fixed, no common DNTUB allowed
14605 0 NMOSIVST_DNX : f = NMOSIVS8250T  DNTUB enclosure of NDIFF = function 1.625 fixed, no common DNTUB allowed
14621 0 NMOSIVST_DNX : f = NMOSIVS8450T  DNTUB enclosure of NDIFF = function 1.675 fixed, no common DNTUB allowed
14637 0 NMOSIVST_DNX : f = NMOSIVS8650T  DNTUB enclosure of NDIFF = function 1.725 fixed, no common DNTUB allowed
14653 0 NMOSIVST_DNX : f = NMOSIVS8850T  DNTUB enclosure of NDIFF = function 1.75 fixed, no common DNTUB allowed
14669 0 NMOSIVST_DNX : f = NMOSIVS9050T  DNTUB enclosure of NDIFF = function 1.8 fixed, no common DNTUB allowed
14685 0 NMOSIVST_DNX : f = NMOSIVS9250T  DNTUB enclosure of NDIFF = function 1.85 fixed, no common DNTUB allowed
14701 0 NMOSIVST_DNX : f = NMOSIVS9450T  DNTUB enclosure of NDIFF = function 1.9 fixed, no common DNTUB allowed
14704 0 Sorry, this nmosivst F is not supported, check for correct F value 
14707 0 VERT10_P2 Element Rule : Base Ntub Perimeter/4 = 13.8
14711 0 VERT10_P3 Element Rule : Ptap Inside Perimeter/4 = 14.9
14720 0 VERT10_E1 Element Rule : NTUB enclosure of ntap = 0.45
14722 0 LAT2_P1 Element Rule : Emitter Perimeter/4 = 2
14725 0 LAT2_P2 Element Rule : Collector net_pdiff Perimeter/4 = 6.2
14728 0 LAT2_P3 Element Rule : Base Ntub Perimeter/4 = 10.0
14732 0 LAT2_P4 Element Rule : Ptap Inside Perimeter/4 = 11.1
14739 0 LAT2_W1 Element Rule : Lateral Base Width = 1
14748 0 LAT2_E1 Element Rule : NTUB enclosure of ntap = 0.45
14753 0 LAT2_G1 Element Rule : gate of lat2 transistor not connected to VDD or VCC
14755 0 NMOSH_O1/NMOSMH_O1 Element Rule : Gate Overlap of Ntub = 1.6 U
14765 0 NMOSH_S1/NMOSMH_S1 Element Rule : Gate Drain Diff spacing = 2.8
14774 0 NMOSH_E1/NMOSMH_E1 Element Rule : Poly Extension of gate = 0.6 U
14781 0 NMOSH_L1/NMOSMH_L1 Element Rule : Gate Length = 3.0 U
14783 0 NMOSH_X1/NMOSMH_X1 Element Rule : drain angles = 45, 8 vertices
14785 0 NMOSH_X1/NMOSMH_X1 Element Rule : edge length = 0.6 * sqrt(2)
14802 0 CVART_MIN_W Element Rule : cvart min w length = 10.0
14803 0 CVARM_MIN_W Element Rule : cvarm min w length = 10.0
14804 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
14805 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
14806 0 CVARIT_MIN_W Element Rule : cvarit min w length = 10.0
14807 0 CVARIM_MIN_W Element Rule : cvarim min w length = 10.0
14808 0 CVARIT_MIN_L Element Rule : cvarit min l length = 2.0
14809 0 CVARIT_MIN_L Element Rule : cvarit min l length = 2.0
14816 0 CVAR_W1 Element Rule : Gate unit width = 0.65
14819 0 CVAR_L1 Element Rule : Gate unit length = 6.60
14828 0 CVAR_X1 Element Rule : Gate spacing 1.0
14838 0 CVAR_Y1 Element Rule : Diff spacing 1.6
14839 0 Illegal device : Zener diode must have 0.2 implant ovlp
14840 0 ZD2SM24_O1 Element Rule : must have 0.2 U implant ovlp
14847 0 ZD2SM24_W1 Element Rule : must have 0.40 U n-implant edge length
14848 0 ZD2SM24_W1 Element Rule : must have 0.40 U p-implant edge length
14851 0 PFR001 : DEVDEF_pfuse outside IPDEF is not allowed
14852 0 Error : RESDEF over DEVDEF_pfuse not allowed
14859 0 ERC Warning : This poly2 over HRES layer is high ohmic, but shorted for LVS
14910 0 REC002 DNTUB not multiple 45 degrees
14911 0 REC002 SNTUB not multiple 45 degrees
14912 0 REC002 SPTUB not multiple 45 degrees
14916 0 REC002 DPTUB not multiple 45 degrees
14917 0 REC002 HVOX not multiple 45 degrees
14918 0 REC002 HVDEF not multiple 90 degrees
14919 0 DNTUB net layer must not be used in layout view
14920 0 SNTUB net layer must not be used in layout view
14921 0 DPTUB net layer must not be used in layout view
14922 0 SPTUB net layer must not be used in layout view
14942 0 S1HVHV Minimum HVDEF spacing = 0.1
14944 0 HVR001 Each HVDEF shape must be marked with a single HVDEF text label
14946 0 HVR001 : multiple text on HVDEF
14964 0 S2NWNW Minimum NTUB50V to NTUB spacing = 8.3
14966 0 W1DP Minimum DPTUB width = 1
14984 0 W2DP Minimum DPTUB width outside DNTUB = 2.3
14988 0 S1DPDP Minimum DPTUB spacing = 1.7
14990 0 S2DPDP Minimum DPTUB notch = 1
14994 0 S1DPNW Minimum DPTUB to NTUB spacing V(NTUB,PSUB) <= 5V = 0 
14995 0 DPR001  DPTUB over NTUB is not allowed
15000 0 DPR002  DPTUB must overlap SPTUB
15005 0 W1SP Minimum SPTUB width = 1
15010 0 S1SPSP Minimum SPTUB spacing = 1.7
15012 0 S2SPSP Minimum SPTUB notch = 1
15016 0 S1NWRP Minimum RPTUB to NTUB spacing V(NTUB,PSUB) <= 5V = 0 
15021 0 E1DPSP : Minimum DPTUB enclosure of SPTUB = 0
15032 0 W2SP ( SPTUB not connected to psub) : Maximum SPTUB width inside DNTUB = 65
15437 0 SPR001  Utmost structures within SPTUB must be closed PTAP rings
16682 0 SPR001 ISO Utmost structures within SPTUB must be closed PTAP rings
16701 0 SPR002  SPTUB must be a copy of DPTUB
17088 0 ERC Warning : pdiff in ISO ring in rptub not closed or missing
17111 0 W1DN Minimum DNTUB width = 14
17114 0 S1DNDN Minimum DNTUB spacing = 13.5 sep notch
17116 0 S1DNNW  Minimum DNTUB to NTUB spacing = 11.8
17118 0 S1DNRP  Minimum DNTUB to RPTUB spacing = 4.5
17119 0 DNR001  DNTUB over NTUB is not allowed
17513 0 DNR002  Utmost structures within DNTUB must be closed NTAP rings in SNTUB
17518 0 DNR003  (totaly isolated)  Each DNTUB shape must be fully enclosed with RPTUB of >= 4.5 um width
17535 0 DNR003 new  (between rings)  Each DNTUB shape must be fully enclosed with RPTUB of >= 4.5 um width
17537 0 DNR003  More DNTUB shapes enclosed by RPTUB ring
17539 0 INFO DNR003 : rptub hole encloses rptub ring ( hole inside hole)
18708 0 S2DNRP : Maximum DNTUB to RPTUB spacing = 9.5
18714 0 DNR004  DIFF is not allowed between DNTUB and its enclosing RPTUB
19173 0 DNR007  POLY1 is not allowed between DNTUB and its enclosing (PTAP in RPTUB)
19175 0 DNR008  POLY2 is not allowed between DNTUB and its enclosing (PTAP in RPTUB)
19198 0 W1SN Minimum SNTUB width = 1.1
19203 0 S1SNSN  Minimum SNTUB spacing = 1
19217 0 S2SNSN  Minimum SNTUB spacing outside DNTUB = 9
19223 0 S4SNSN Minimum SNTUB20V spacing = 1.7
19225 0 S1DNSN Minimum DNTUB to SNTUB spacing = 13
19230 0 S1NWSN Minimum SNTUB to NTUB spacing = 9.5
19244 0 S1RPSN Minimum SNTUB to RPTUB spacing outside DNTUB = 4
20008 0 S2RPSN : Maximum SNTUB to RPTUB spacing outside DNTUB = 6
20009 0 SNR001  SNTUB over NTUB is not allowed
20011 0 SNR002  SNTUB over DPTUB is not allowed
20013 0 SNR003  SNTUB over SPTUB is not allowed
20021 0 SNR004  SNTUB outside DNTUB is not allowed
20030 0 INFO SNR005 : sntub hole encloses sntub ring ( hole inside hole): Each RPTUB shape inside DNTUB must be fully enclosed with SNTUB
20031 0 SNR005 : RPTUB shape IN DNTUB is totally outside sntub ring Each RPTUB shape inside DNTUB must be fully enclosed with SNTUB
20034 0 SNR005 More RPTUB shapes enclosed by SNTUB ring : Each RPTUB shape inside DNTUB must be fully enclosed with SNTUB
20050 0 SNR005  (between rings)  Each RPTUB shape inside DNTUB must be fully enclosed with SNTUB
20055 0 E1RPND Minimum (RPTUB and DNTUB) enclosure of NDIFF V(NDIFF,RPTUB) <= 5V = 1.2
20066 0 E1RPPD Minimum (RPTUB and DNTUB) enclosure of PDIFF V(DNTUB,PDIFF) <= 5V = 0.2
20071 0 E2RPPD Minimum (RPTUB and not DNTUB) enclosure of PDIFF = 0.3
20080 0 E3RPPD Minimum (RPTUB and not DNTUB) enclosure of PDIFF adjacent to DNTUB within 9um = 1
20097 0 E1SNND Minimum SNTUB enclosure of NDIFF = 0.2
20109 0 E1SNPD Minimum SNTUB enclosure of PDIFF V(SNTUB,PDIFF) <= 5V = 1.2
20118 0 NDR001  NDIFF is not allowed in (DNTUB and not SNTUB and not RPTUB)
20133 0 PDR001  PDIFF is not allowed in (DPTUB and not SPTUB)
20141 0 PDR002  PSD is not allowed in (DNTUB and not SNTUB)
20152 0 NDR002  NDIFF is not allowed in (RPTUB and not DNTUB)
20173 0 S1AAND  Minimum (NTAP hole overlapping (HVDEF and DNTUB)) spacing to (DIFF outside HVDEF) = 4.9
20343 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos50s_holes  sep <  7.4
20345 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos20_holes  sep <  7.4
20347 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosi50_holes  sep <  7.4
20349 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosi20_holes  sep <  7.4
20351 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos10mh_holes  sep <  7.4
20353 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos20s_holes  sep <  7.4
20355 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosdi50_holes  sep <  7.4
20357 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosdi20_holes  sep <  7.4
20359 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosfi25_holes  sep <  7.4
20361 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20363 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos120_holes  sep <  7.4
20365 0 S2NDND ntap_hv_pmos50_holes ntap_hv_nmosi120_holes  sep <  7.4
20367 0 S2NDND ntap_hv_pmos50_holes ntap_hv_pmos10mh_holes  sep <  7.4
20369 0 PMOSVST_R2 ntap_hv_pmos50_holes  ntap_hv_pmosvst_holes sep <  8.7
20371 0 PMOSDVST_R2 ntap_hv_pmos50_holes  ntap_hv_pmosdvst_holes sep <  8.7
20373 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_pmos20_holes  sep <  7.4
20375 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosi50_holes  sep <  7.4
20377 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosi20_holes  sep <  7.4
20379 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosdi50_holes  sep <  7.4
20381 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosdi20_holes  sep <  7.4
20383 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosfi25_holes  sep <  7.4
20385 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20387 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_pmos120_holes  sep <  7.4
20389 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_nmosi120_holes  sep <  7.4
20391 0 S2NDND ntap_hv_pmos50s_holes ntap_hv_pmos10mh_holes  sep <  7.4
20393 0 PMOSVST_R2 ntap_hv_pmos50s_holes  ntap_hv_pmosvst_holes sep <  8.7
20395 0 PMOSDVST_R2 ntap_hv_pmos50s_holes  ntap_hv_pmosdvst_holes sep <  8.7
20397 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosi50_holes  sep <  7.4
20399 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosi20_holes  sep <  7.4
20401 0 S2NDND ntap_hv_pmos20_holes ntap_hv_pmos120_holes  sep <  7.4
20403 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosdi50_holes  sep <  7.4
20405 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosdi20_holes  sep <  7.4
20407 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosfi25_holes  sep <  7.4
20409 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20411 0 S2NDND ntap_hv_pmos20_holes ntap_hv_pmos120_holes  sep <  7.4
20413 0 S2NDND ntap_hv_pmos20_holes ntap_hv_nmosi120_holes  sep <  7.4
20415 0 S2NDND ntap_hv_pmos20_holes ntap_hv_pmos10mh_holes  sep <  7.4
20417 0 PMOSVST_R2 ntap_hv_pmos20s_holes  ntap_hv_pmosvst_holes sep <  8.7
20419 0 PMOSDVST_R2 ntap_hv_pmos20s_holes  ntap_hv_pmosdvst_holes sep <  8.7
20421 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosi20_holes  sep <  7.4
20423 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosdi50_holes  sep <  7.4
20425 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosdi20_holes  sep <  7.4
20427 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosfi25_holes  sep <  7.4
20429 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20431 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_pmos120_holes  sep <  7.4
20433 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_nmosi120_holes  sep <  7.4
20435 0 S2NDND ntap_hv_nmosi50_holes ntap_hv_pmos10mh_holes  sep <  7.4
20437 0 PMOSVST_R2 ntap_hv_nmosi50_holes  ntap_hv_pmosvst_holes sep <  8.7
20439 0 PMOSDVST_R2 ntap_hv_nmosi50_holes  ntap_hv_pmosdvst_holes sep <  8.7
20441 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_pmos20s_holes  sep <  7.4
20443 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_nmosdi50_holes  sep <  7.4
20445 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_nmosdi20_holes  sep <  7.4
20447 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_nmosfi25_holes  sep <  7.4
20449 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20451 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_pmos120_holes  sep <  7.4
20453 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_nmosi120_holes  sep <  7.4
20455 0 S2NDND ntap_hv_nmosi20_holes ntap_hv_pmos10mh_holes  sep <  7.4
20457 0 PMOSVST_R2 ntap_hv_nmosi20_holes  ntap_hv_pmosvst_holes sep <  8.7
20459 0 PMOSDVST_R2 ntap_hv_nmosi20_holes  ntap_hv_pmosdvst_holes sep <  8.7
20461 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_nmosdi50_holes  sep <  7.4
20463 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_nmosdi20_holes  sep <  7.4
20465 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_nmosfi25_holes  sep <  7.4
20467 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20469 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_pmos120_holes  sep <  7.4
20471 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_nmosi120_holes  sep <  7.4
20473 0 S2NDND ntap_hv_pmos20s_holes ntap_hv_pmos10mh_holes  sep <  7.4
20475 0 PMOSVST_R1 ntap_hv_pmos20s_holes  ntap_hv_pmosvst_holes sep <  8.7
20477 0 PMOSDVST_R1 ntap_hv_pmos20s_holes  ntap_hv_pmosdvst_holes sep <  8.7
20479 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_nmosdi20_holes  sep <  7.4
20481 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_nmosfi25_holes  sep <  7.4
20483 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20485 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_pmos120_holes  sep <  7.4
20487 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_nmosi120_holes  sep <  7.4
20489 0 S2NDND ntap_hv_nmosdi50_holes ntap_hv_pmos10mh_holes  sep <  7.4
20491 0 PMOSVST_R2 ntap_hv_pmos20s_holes  ntap_hv_pmosvst_holes sep <  8.7
20493 0 PMOSDVST_R2 ntap_hv_pmos20s_holes  ntap_hv_pmosdvst_holes sep <  8.7
20495 0 S2NDND ntap_hv_nmosdi20_holes ntap_hv_nmosfi25_holes  sep <  7.4
20497 0 S2NDND ntap_hv_nmosdi20_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20499 0 S2NDND ntap_hv_nmosdi20_holes ntap_hv_pmos120_holes  sep <  7.4
20501 0 S2NDND ntap_hv_nmosdi20_holes ntap_hv_nmosi120_holes  sep <  7.4
20503 0 PMOSVST_R2 ntap_hv_nmosdi20_holes  ntap_hv_pmosvst_holes sep <  8.7
20505 0 PMOSDVST_R2 ntap_hv_nmosdi20_holes  ntap_hv_pmosdvst_holes sep <  8.7
20507 0 S2NDND ntap_hv_nmosfi25_holes ntap_hv_nmosfi25s_holes  sep <  7.4
20509 0 S2NDND ntap_hv_nmosfi25_holes ntap_hv_pmos120_holes  sep <  7.4
20511 0 S2NDND ntap_hv_nmosfi25_holes ntap_hv_nmosi120_holes  sep <  7.4
20513 0 S2NDND ntap_hv_nmosfi25_holes ntap_hv_pmos10mh_holes  sep <  7.4
20515 0 PMOSVST_R2 ntap_hv_nmosfi25_holes  ntap_hv_pmosvst_holes sep <  8.7
20517 0 PMOSDVST_R2 ntap_hv_nmosfi25_holes  ntap_hv_pmosdvst_holes sep <  8.7
20519 0 S2NDND ntap_hv_nmosfi25s_holes ntap_hv_pmos120_holes  sep <  7.4
20521 0 S2NDND ntap_hv_nmosfi25s_holes ntap_hv_nmosi120_holes  sep <  7.4
20523 0 S2NDND ntap_hv_nmosfi25s_holes ntap_hv_pmos10mh_holes  sep <  7.4
20525 0 PMOSVST_R2 ntap_hv_nmosfi25s_holes  ntap_hv_pmosvst_holes sep <  8.7
20527 0 PMOSDVST_R2 ntap_hv_nmosfi25s_holes  ntap_hv_pmosdvst_holes sep <  8.7
20529 0 S2NDND ntap_hv_pmos120_holes ntap_hv_nmosi120_holes  sep <  7.4
20531 0 S2NDND ntap_hv_pmos120_holes ntap_hv_pmos10mh_holes  sep <  7.4
20533 0 PMOSVST_R2 ntap_hv_pmos120_holes  ntap_hv_pmosvst_holes sep <  8.7
20535 0 PMOSDVST_R2 ntap_hv_pmos120_holes  ntap_hv_pmosdvst_holes sep <  8.7
20537 0 S2NDND  ntap_hv_pmos50 ntap_esd_device sep < 7.4
20539 0 S2NDND  ntap_hv_pmos50s ntap_esd_device sep < 7.4
20541 0 S2NDND  ntap_hv_pmos20 ntap_esd_device  sep < 7.4
20543 0 S2NDND  ntap_hv_nmosi50 ntap_esd_device sep < 7.4
20545 0 S2NDND ntap_hv_pmos120_holes  ntap_esd_device_holes sep < 7.4
20547 0 S2NDND ntap_hv_nmosi20_holes  ntap_esd_device_holes sep < 7.4
20549 0 S2NDND ntap_hv_nmosi50_holes  ntap_esd_device_holes sep < 7.4
20551 0 S2NDND ntap_hv_nmosdi20_holes  ntap_esd_device_holes sep < 7.4
20553 0 S2NDND ntap_hv_nmosdi50_holes  ntap_esd_device_holes sep < 7.4
20557 0 S2NDND ntap_hv_nmosdi120_holes  ntap_esd_device_holes sep < 7.4
20559 0 S2NDND ntap_hv_pmos10mh_holes  ntap_esd_device_holes sep < 7.4
20561 0 PMOSVST_R2 ntap_esd_device_holes ntap_hv_pmosvst_holes sep <  8.7 
20563 0 PMOSDVST_R2 ntap_esd_device_holes ntap_hv_pmosdvst_holes sep <  8.7 
20565 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdtd40_holes < 7.4
20567 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdtd42_holes < 7.4
20569 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdtd45_holes < 7.4
20571 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdtd60_holes < 7.4
20573 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdpd10_holes < 7.4
20575 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdfdi50_holes < 7.4
20577 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdgcni5_holes < 7.4
20579 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdgci3_holes < 7.4
20581 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdgci20_holes < 7.4
20583 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdpnp42_holes < 7.4
20585 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdgcpi5_holes < 7.4
20587 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdfdni5_holes < 7.4
20589 0 S2NDND ntap_hv_esdtd50_holes ntap_hv_esdfdpi5_holes < 7.4
20591 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdtd42_holes < 7.4
20593 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdtd45_holes < 7.4
20595 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdtd60_holes < 7.4
20597 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdpd10_holes < 7.4
20599 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdfdi50_holes < 7.4
20601 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdgcni5_holes < 7.4
20603 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdgci3_holes < 7.4
20605 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdgci20_holes < 7.4
20607 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdgcpi5_holes < 7.4
20609 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdfdni5_holes < 7.4
20611 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdfdpi5_holes < 7.4
20613 0 S2NDND ntap_hv_esdtd40_holes ntap_hv_esdpnp42_holes < 7.4
20615 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdtd45_holes < 7.4
20617 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdtd60_holes < 7.4
20619 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdpd10_holes < 7.4
20621 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdfdi50_holes < 7.4
20623 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdgcni5_holes < 7.4
20625 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdgci3_holes < 7.4
20627 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdgci20_holes < 7.4
20629 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdgcpi5_holes < 7.4
20631 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdfdni5_holes < 7.4
20633 0 S2NDND ntap_hv_esdtd42_holes ntap_hv_esdfdpi5_holes < 7.4
20635 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdtd60_holes < 7.4
20637 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdpd10_holes < 7.4
20639 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdfdi50_holes < 7.4
20641 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdgcni5_holes < 7.4
20643 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdgci3_holes < 7.4
20645 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdgci20_holes < 7.4
20647 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdgcpi5_holes < 7.4
20649 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdfdni5_holes < 7.4
20651 0 S2NDND ntap_hv_esdtd45_holes ntap_hv_esdfdpi5_holes < 7.4
20653 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdpd10_holes < 7.4
20655 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdfdi50_holes < 7.4
20657 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdgcni5_holes < 7.4
20659 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdgci3_holes < 7.4
20661 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdgci20_holes < 7.4
20663 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdgcpi5_holes < 7.4
20665 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdfdni5_holes < 7.4
20667 0 S2NDND ntap_hv_esdtd60_holes ntap_hv_esdfdpi5_holes < 7.4
20669 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdfdi50_holes < 7.4
20671 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdgcni5_holes < 7.4
20673 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdgci3_holes < 7.4
20675 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdgci20_holes < 7.4
20677 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdgcpi5_holes < 7.4
20679 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdfdni5_holes < 7.4
20681 0 S2NDND ntap_hv_esdpd10_holes ntap_hv_esdfdpi5_holes < 7.4
20683 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdgcni5_holes < 7.4
20685 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdgci3_holes < 7.4
20687 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdgci20_holes < 7.4
20689 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdgcpi5_holes < 7.4
20691 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdfdni5_holes < 7.4
20693 0 S2NDND ntap_hv_esdfdi50_holes ntap_hv_esdfdpi5_holes < 7.4
20695 0 S2NDND ntap_hv_esdgcni5_holes ntap_hv_esdgci3_holes < 7.4
20697 0 S2NDND ntap_hv_esdgcni5_holes ntap_hv_esdgci20_holes < 7.4
20699 0 S2NDND ntap_hv_esdgcni5_holes ntap_hv_esdgcpi5_holes < 7.4
20701 0 S2NDND ntap_hv_esdgcni5_holes ntap_hv_esdfdni5_holes < 7.4
20703 0 S2NDND ntap_hv_esdgcni5_holes ntap_hv_esdfdpi5_holes < 7.4
20705 0 S2NDND ntap_hv_esdgci20_holes ntap_hv_esdgci20_holes < 7.4
20707 0 S2NDND ntap_hv_esdgci20_holes ntap_hv_esdgcpi5_holes < 7.4
20709 0 S2NDND ntap_hv_esdgci20_holes ntap_hv_esdfdni5_holes < 7.4
20711 0 S2NDND ntap_hv_esdgci20_holes ntap_hv_esdfdpi5_holes < 7.4
20727 0 S2NDND  ntap_hv_pmos50_holes  ntap_esddevice_holes   < 7.4
20729 0 S2NDND  ntap_hv_pmos50s_holes ntap_esddevice_holes   < 7.4
20731 0 S2NDND  ntap_hv_pmos20s_holes ntap_esddevice_holes   < 7.4
20733 0 S2NDND  ntap_hv_pmos20_holes  ntap_esddevice_holes   < 7.4
20735 0 S2NDND  ntap_hv_pmos120_holes ntap_esddevice_holes   < 7.4
20737 0 S2NDND  ntap_hv_nmosi50_holes ntap_esddevice_holes   < 7.4
20739 0 S2NDND  ntap_hv_nmosi20_holes ntap_esddevice_holes   < 7.4
20741 0 S2NDND  ntap_hv_nmosdi20_holes ntap_esddevice_holes  < 7.4
20743 0 S2NDND  ntap_hv_nmosdi50_holes ntap_esddevice_holes  < 7.4
20745 0 S2NDND  ntap_hv_nmosi120_holes ntap_esddevice_holes  < 7.4
20747 0 S2NDND  ntap_hv_pmos10mh ntap_esddevice_holes  < 7.4
20749 0 S2NDND  ntap_esddevice_holes  ntap_esd_device_holes  < 7.4
20750 0 S2NDND bad ntap  ntap_hv_pmos50_holes            ntap_hv_pmos50s_holes
20751 0 S2NDND bad ntap  ntap_hv_pmos50_holes            ntap_hv_pmos20_holes
20752 0 S2NDND bad ntap  ntap_hv_pmos50_holes            ntap_hv_nmosi50_holes
20753 0 S2NDND bad ntap  ntap_hv_pmos50_holes            ntap_hv_nmosi20_holes
20754 0 S2NDND bad ntap  ntap_hv_pmos50s_holes           ntap_hv_pmos20_holes
20755 0 S2NDND bad ntap  ntap_hv_pmos50s_holes           ntap_hv_nmosi50_holes
20756 0 S2NDND bad ntap  ntap_hv_pmos50s_holes           ntap_hv_nmosi20_holes
20757 0 S2NDND bad ntap  ntap_hv_pmos20_holes            ntap_hv_nmosi50_holes
20758 0 S2NDND bad ntap  ntap_hv_pmos20_holes            ntap_hv_nmosi20_holes
20759 0 S2NDND bad ntap  ntap_hv_nmosi50_holes           ntap_hv_nmosi20_holes
20761 0 W1HX Minimum HVOX width = 0.6
20764 0 S1HXHX Minimum HVOX spacing = 0.6
20774 0 E1HXAA Minimum HVOX enclosure of DIFF = 0.6
20782 0 E1HXP1 Minimum HVOX enclosure of POLY1 overlapping HVDEF = 0.3
20784 0 S1AAHX Minimum HVOX to DIFF spacing = 0.6
20790 0 S1HXP1 Minimum HVOX to (POLY1 overlapping HVDEF) spacing = 0.3
20803 0 BAD1HX HVOX must overlap GATE
20810 0 E1TXP1 Minimum MIDOX enclosure of POLY1 overlapping HVDEF = 0.3
20813 0 S1P1TX Minimum MIDOX to (POLY1 overlapping HVDEF) spacing = 0.3
20815 0 ATTENTION : Layer SFCDEF should not be used on design data for DRC checking, SFCDEF is a special definition layer for MASK Fabrication
20816 0 PWR001 FIMP outside SFCDEF will be removed and regenerated
20818 0 LDR001 NLDD outside SFCDEF will be removed and regenerated
20820 0 L2R001 NLDD50 outside SFCDEF will be removed and regenerated
20822 0 APR001 ANTIPU outside SFCDEF will be removed and regenerated
20824 0 P1R001  Floating POLY1 overlapping HVDEF is not allowed
20827 0 S1DNP1  Minimum DNTUB to POLY1 spacing = 4.5
20831 0 E1DNP1  Minimum DNTUB enclosure of POLY1 = 0.2
20834 0 S1P1RP  Minimum POLY1 to (RPTUB and not DNTUB) spacing = 1
20839 0 E1RPP1  Minimum (RPTUB and not DNTUB) enclosure of POLY1 = 1
20841 0 M1R001  Floating MET1 overlapping HVDEF is not allowed
20844 0 NWR001 NTUB overlapping KEPOUT is not allowed
20846 0 S1KONW Minimum NTUB spacing to KEPOUT or SFCDEF = 3
20847 0 AAR001 DIFF overlapping KEPOUT is not allowed
20849 0 S1AAKO Minimum DIFF spacing to KEPOUT or SFCDEF = 0.6
20850 0 TXR002 MIDOX overlapping KEPOUT is not allowed
20852 0 S1KOTX Minimum MIDOX spacing to KEPOUT or SFCDEF = 0.6
20853 0 P1R002 POLY1 overlapping KEPOUT is not allowed
20855 0 S1KOP1 Minimum POLY1 spacing to KEPOUT or SFCDEF = 0.45
20856 0 NSR001 NPLUS overlapping KEPOUT is not allowed
20858 0 S1KONS Minimum NPLUS spacing to KEPOUT or SFCDEF = 0.6
20859 0 PSR001 PPLUS overlapping KEPOUT is not allowed
20861 0 S1KOPS Minimum PPLUS spacing to KEPOUT or SFCDEF = 0.6
20862 0 HRR004 HRES overlapping KEPOUT is not allowed
20864 0 S1HRKO Minimum HRES spacing to KEPOUT or SFCDEF = 0.6
20865 0 P2R002 POLY2 overlapping KEPOUT is not allowed
20867 0 S1KOP2 Minimum POLY2 spacing to KEPOUT or SFCDEF = 0.6
20868 0 COR002 CONT overlapping KEPOUT is not allowed
20870 0 S1COKO Minimum CONT spacing to KEPOUT or SFCDEF = 0.4
20871 0 M1R002 MET1 overlapping KEPOUT is not allowed
20873 0 S1KOM1 Minimum MET1 spacing to KEPOUT or SFCDEF = 0.45
20874 0 V1R002 VIA1 overlapping KEPOUT is not allowed
20876 0 S1KOV1 Minimum VIA1 spacing to KEPOUT or SFCDEF = 0.45
20877 0 M2R002 MET2 overlapping KEPOUT is not allowed
20879 0 S1KOM2 0.5
20880 0 V2R002 VIA2 overlapping KEPOUT is not allowed
20882 0 S1KOV2 Minimum VIA2 spacing to KEPOUT or SFCDEF = 0.45
20883 0 M3R002 MET3 overlapping KEPOUT is not allowed
20885 0 S1KOM3 Minimum MET3 spacing to KEPOUT or SFCDEF = 0.6
20886 0 PAR002 PAD overlapping KEPOUT is not allowed
20888 0 S1KOPA Minimum PAD spacing to KEPOUT or SFCDEF = 9
20889 0 V3R002 VIA3 overlapping KEPOUT is not allowed
20891 0 S1KOV3 Minimum VIA3 spacing to KEPOUT or SFCDEF = 0.45
20892 0 M4R002 MET4 overlapping KEPOUT is not allowed
20894 0 S1KOM4 Minimum MET4 spacing to KEPOUT or SFCDEF = 2
20895 0 DNR006 DNTUB overlapping KEPOUT is not allowed
20897 0 S1DNKO Minimum DNTUB spacing to KEPOUT or SFCDEF = 4.5
20898 0 SNR006 SNTUB overlapping KEPOUT is not allowed
20900 0 S1KOSN Minimum SNTUB spacing to KEPOUT or SFCDEF = 4
20901 0 DPR003 DPTUB overlapping KEPOUT is not allowed
20903 0 S1DPKO Minimum DPTUB spacing to KEPOUT or SFCDEF = 1.7
20904 0 SPR003 SPTUB overlapping KEPOUT is not allowed
20906 0 S1KOSP Minimum SPTUB spacing to KEPOUT or SFCDEF = 1.7
20907 0 HXR002 HVOX overlapping KEPOUT is not allowed
20909 0 S1HXKO Minimum HVOX spacing to KEPOUT or SFCDEF = 0.6
20910 0 LVR004 LVTDEF overlapping KEPOUT is not allowed
20912 0 S1KOLV Minimum LVTDEF spacing to KEPOUT or SFCDEF = 0.6
20913 0 MCR002 METCAP overlapping KEPOUT is not allowed
20915 0 S1MCKO Minimum METCAP spacing to KEPOUT or SFCDEF = 0.8
21119 0 DNTUB Voltage Definition : this text on met1 is not a valid text definition for dntub (-120 to +120)
21121 0 INFO : multiple text on MET1 for DNTUB voltage definition
21125 0 DNTUB Voltage Definition : this text on met1 is a valid text definition for dntub (-120 to +120) but not supported yet
21137 0 INFO : this dntub has 5 Volt
21138 0 INFO : this dntub has 50 Volt
21139 0 INFO : this dntub has 20 Volt
21140 0 INFO : this dntub has 120 Volt
21143 0 DNTUB Voltage warning : found more different voltages ( 5,20 ) for DNTUB, is this ok ??
21146 0 DNTUB Voltage warning : found more different voltages ( 5,50 ) for DNTUB, is this ok ??
21149 0 DNTUB Voltage warning : found more different voltages ( 5,120 ) for DNTUB, is this ok ??
21152 0 DNTUB Voltage warning : found more different voltages ( 20,50 ) for DNTUB, is this ok ??
21155 0 DNTUB Voltage warning : found more different voltages ( 20,120 ) for DNTUB, is this ok ??
21158 0 DNTUB Voltage warning : found more different voltages ( 50,120 ) for DNTUB, is this ok ??
21161 0 Illegal DNTUB120V : missing or bad voltage definition for dntub of 120 Volt device
21163 0 S2DNDN Minimum DNTUB_120V to DNTUB spacing = 17.5
21165 0 S2DNSN  Minimum DNTUB_120V to (SNTUB and not DNTUB) spacing = 15.5
21167 0 S2DNNW Minimum DNTUB_120V to NTUB spacing = 17.5
22755 0 S4DNRP : Maximum DNTUB_120V to RPTUB spacing = 13
23716 0 DNR005  Region between DNTUB oversized by 0.6 and RPTUB must be covered with MET1 connected to RPTUB = 0.6
23718 0 S3DNRP  Minimum DNTUB_120V to RPTUB spacing = 6.5
23722 0 E1DNDP  Minimum DNTUB_120V enclosure of DPTUB = 4.8
23726 0 E1DNSP  Minimum DNTUB_120V enclosure of SPTUB = 4.8
23730 0 E2DNSN  Minimum DNTUB_120V enclosure of SNTUB = 1.8
23734 0 E1DNND  Minimum DNTUB_120V enclosure of NDIFF = 2.6
23752 0 Warning : this DNTUB has no voltage info in spite of other voltages found on layout (120,50,20,5) checked for 50 Volt Isolation, is this OK ?
23755 0 PMOS20T/M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23769 0 PMOS20M/H R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23770 0 PMOS20T/M/H : IsoVolt 120 must be in dntub 120V
23771 0 PMOS20T/M/H : IsoVolt 20 must be in dntub 20V
23772 0 PMOS20T/M/H : IsoVolt 50 must be in dntub 50V
23773 0 PMOS20T/M/H : IsoVolt 5 must be in dntub 5V
23776 0 PMOS10MH    R2 Element Rule : HVDEF2 isoVoltage  text string missing
23790 0 PMOS10MH   1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23791 0 PMOS10MH  : IsoVolt 120 must be in dntub 120V
23792 0 PMOS10MH   : IsoVolt 20 must be in dntub 20V
23793 0 PMOS10MH   : IsoVolt 50 must be in dntub 50V
23794 0 PMOS10MH    : IsoVolt 5 must be in dntub 5V
23797 0 PMOSVST R1 Element Rule : HVDEF2 isoVoltage  text string missing
23811 0 PMOSVST R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23812 0 PMOSVST R1 : IsoVolt 120 must be in dntub 120V
23813 0 PMOSVST R1 : IsoVolt 20 must be in dntub 20V
23814 0 PMOSVST R1 : IsoVolt 50 must be in dntub 50V
23815 0 PMOSVST R1 : IsoVolt 5 must be in dntub 5V
23818 0 PMOSDVST R1 Element Rule : HVDEF2 isoVoltage  text string missing
23832 0 PMOSDVST R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23833 0 PMOSDVST R1 : IsoVolt 120 must be in dntub 120V
23834 0 PMOSDVST R1 : IsoVolt 20 must be in dntub 20V
23835 0 PMOSDVST R1 : IsoVolt 50 must be in dntub 50V
23836 0 PMOSDVST R1 : IsoVolt 5 must be in dntub 5V
23839 0 NMOSDIVST R1 Element Rule : HVDEF2 isoVoltage  text string missing
23853 0 NMOSDIVST R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23854 0 NMOSDIVST R1 : IsoVolt 120 must be in dntub 120V
23855 0 NMOSDIVST R1 : IsoVolt 20 must be in dntub 20V
23856 0 NMOSDIVST R1 : IsoVolt 50 must be in dntub 50V
23857 0 NMOSDIVST R1 : IsoVolt 5 must be in dntub 5V
23860 0 NMOSIVST R1 Element Rule : HVDEF2 isoVoltage  text string missing
23874 0 NMOSIVST R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23875 0 NMOSIVST R1 : IsoVolt 120 must be in dntub 120V
23876 0 NMOSIVST R1 : IsoVolt 20 must be in dntub 20V
23877 0 NMOSIVST R1 : IsoVolt 50 must be in dntub 50V
23878 0 NMOSIVST R1 : IsoVolt 5 must be in dntub 5V
23881 0 PMOS50T/M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23895 0 PMOS50M/H R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23896 0 PMOS50T/M/H : IsoVolt 120 must be in dntub 120V
23897 0 PMOS50T/M/H : IsoVolt 20 must be in dntub 20V
23898 0 PMOS50T/M/H : IsoVolt 50 must be in dntub 50V
23899 0 PMOS50T/M/H : IsoVolt 5 must be in dntub 5V
23916 0 PMOS20HS R1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23917 0 PMOS20HS    : IsoVolt 120 must be in dntub 120V
23918 0 PMOS20HS    : IsoVolt 20 must be in dntub 20V
23919 0 PMOS20HS    : IsoVolt 50 must be in dntub 50V
23920 0 PMOS20HS    : IsoVolt 5 must be in dntub 5V
23923 0 PMOS50HS    R2 Element Rule : HVDEF2 isoVoltage  text string missing
23937 0 PMOS50HS   1 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23938 0 PMOS50HS    : IsoVolt 120 must be in dntub 120V
23939 0 PMOS50HS    : IsoVolt 20 must be in dntub 20V
23940 0 PMOS50HS    : IsoVolt 50 must be in dntub 50V
23941 0 PMOS50HS    : IsoVolt 5 must be in dntub 5V
23944 0 PMOS120M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23947 0 PMOS120M/H : IsoVolt 120 must be in dntub 120V
23950 0 NMOSI120M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23953 0 NMOSI120M/H: IsoVolt 120 must be in dntub 120V
23956 0 NMOSI20T/M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23970 0 NMOSI20T/M/H Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23971 0 NMOSI20T/M/H: IsoVolt 120 must be in dntub 120V
23972 0 NMOSI20T/M/H: IsoVolt 20 must be in dntub 20V
23973 0 NMOSI20T/M/H: IsoVolt 50 must be in dntub 50V
23974 0 NMOSI20T/M/H: IsoVolt 5 must be in dntub 5V
23977 0 NMOSDI20H R2 Element Rule : HVDEF2 isoVoltage  text string missing
23991 0 NMOSDI20H Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
23992 0 NMOSDI20H: IsoVolt 120 must be in dntub 120V
23993 0 NMOSDI20H: IsoVolt 20 must be in dntub 20V
23994 0 NMOSDI20H: IsoVolt 50 must be in dntub 50V
23995 0 NMOSDI20H: IsoVolt 5 must be in dntub 5V
23998 0 NMOSI50T/M/H R2 Element Rule : HVDEF2 isoVoltage  text string missing
24012 0 NMOSI50T/M/H Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24013 0 NMOSI50T/M/H: IsoVolt 120 must be in dntub 120V
24014 0 NMOSI50T/M/H: IsoVolt 20 must be in dntub 20V
24015 0 NMOSI50T/M/H: IsoVolt 50 must be in dntub 50V
24016 0 NMOSI50T/M/H: IsoVolt 5 must be in dntub 5V
24019 0 NMOSDI50H R2 Element Rule : HVDEF2 isoVoltage  text string missing
24033 0 NMOSDI50H Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24034 0 NMOSDI50H: IsoVolt 120 must be in dntub 120V
24035 0 NMOSDI50H: IsoVolt 20 must be in dntub 20V
24036 0 NMOSDI50H: IsoVolt 50 must be in dntub 50V
24037 0 NMOSDI50H: IsoVolt 5 must be in dntub 5V
24040 0 RPWELLR  R2 Element Rule : HVDEF2 isoVoltage  text string missing
24054 0 RPWELLR Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24055 0 RPWELLR  : IsoVolt 120 must be in dntub 120V
24056 0 RPWELLR  : IsoVolt 20 must be in dntub 20V
24057 0 RPWELLR  : IsoVolt 50 must be in dntub 50V
24058 0 RPWELLR  : IsoVolt 5 must be in dntub 5V
24061 0 RDIFFPS  R2 Element Rule : HVDEF2 isoVoltage  text string missing
24075 0 RDIFFPS Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24076 0 RDIFFPS  : IsoVolt 120 must be in dntub 120V
24077 0 RDIFFPS  : IsoVolt 20 must be in dntub 20V
24078 0 RDIFFPS  : IsoVolt 50 must be in dntub 50V
24079 0 RDIFFPS  : IsoVolt 5 must be in dntub 5V
24082 0 RDIFFNR  R2 Element Rule : HVDEF2 isoVoltage  text string missing
24096 0 RDIFFNR Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24097 0 RDIFFNR  : IsoVolt 120 must be in dntub 120V
24098 0 RDIFFNR  : IsoVolt 20 must be in dntub 20V
24099 0 RDIFFNR  : IsoVolt 50 must be in dntub 50V
24100 0 RDIFFNR  : IsoVolt 5 must be in dntub 5V
24104 0 PMOSI  R1 Element Rule : isoVoltage  text string missing
24118 0 PMOSI  Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24119 0 PMOSI  IsoVolt 120 must be in dntub 120V
24120 0 PMOSI  IsoVolt 20 must be in dntub 20V
24121 0 PMOSI  IsoVolt 50 must be in dntub 50V
24122 0 PMOSI  IsoVolt 5 must be in dntub 5V
24126 0 PMOSIM  R1 Element Rule : isoVoltage  text string missing
24140 0 PMOSIM  Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24141 0 PMOSIM  IsoVolt 120 must be in dntub 120V
24142 0 PMOSIM  IsoVolt 20 must be in dntub 20V
24143 0 PMOSIM  IsoVolt 50 must be in dntub 50V
24144 0 PMOSIM  IsoVolt 5 must be in dntub 5V
24148 0 NMOSI  R1 Element Rule : isoVoltage  text string missing
24162 0 NMOSI  Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24163 0 NMOSI  IsoVolt 120 must be in dntub 120V
24164 0 NMOSI  IsoVolt 20 must be in dntub 20V
24165 0 NMOSI  IsoVolt 50 must be in dntub 50V
24166 0 NMOSI  IsoVolt 5 must be in dntub 5V
24170 0 NMOSIM  R1 Element Rule : isoVoltage  text string missing
24184 0 NMOSIM  Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24185 0 NMOSIM  IsoVolt 120 must be in dntub 120V
24186 0 NMOSIM  IsoVolt 20 must be in dntub 20V
24187 0 NMOSIM  IsoVolt 50 must be in dntub 50V
24188 0 NMOSIM  IsoVolt 5 must be in dntub 5V
24192 0 ESDTD20 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24206 0 ESDTD20 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24207 0 ESDTD20: IsoVolt 120 must be in dntub 120V
24208 0 ESDTD20: IsoVolt 20 must be in dntub 20V
24209 0 ESDTD20: IsoVolt 50 must be in dntub 50V
24210 0 ESDTD20: IsoVolt 5 must be in dntub 5V
24214 0 ESDTD40 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24228 0 ESDTD40 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24229 0 ESDTD40: IsoVolt 120 must be in dntub 120V
24230 0 ESDTD40: IsoVolt 20 must be in dntub 20V
24231 0 ESDTD40: IsoVolt 50 must be in dntub 50V
24232 0 ESDTD40: IsoVolt 5 must be in dntub 5V
24236 0 ESDTD50 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24250 0 ESDTD50 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24251 0 ESDTD50: IsoVolt 120 must be in dntub 120V
24252 0 ESDTD50: IsoVolt 20 must be in dntub 20V
24253 0 ESDTD50: IsoVolt 50 must be in dntub 50V
24254 0 ESDTD50: IsoVolt 5 must be in dntub 5V
24258 0 ESDTD42 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24272 0 ESDTD42 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24273 0 ESDTD42: IsoVolt 120 must be in dntub 120V
24274 0 ESDTD42: IsoVolt 20 must be in dntub 20V
24275 0 ESDTD42: IsoVolt 50 must be in dntub 50V
24276 0 ESDTD42: IsoVolt 5 must be in dntub 5V
24280 0 ESDTD45 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24294 0 ESDTD45 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24295 0 ESDTD45: IsoVolt 120 must be in dntub 120V
24296 0 ESDTD45: IsoVolt 20 must be in dntub 20V
24297 0 ESDTD45: IsoVolt 50 must be in dntub 50V
24298 0 ESDTD45: IsoVolt 5 must be in dntub 5V
24302 0 ESDTD60 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24316 0 ESDTD60 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24317 0 ESDTD60: IsoVolt 120 must be in dntub 120V
24318 0 ESDTD60: IsoVolt 20 must be in dntub 20V
24319 0 ESDTD60: IsoVolt 50 must be in dntub 50V
24320 0 ESDTD60: IsoVolt 5 must be in dntub 5V
24324 0 ESDPD10 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24338 0 ESDPD10 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24339 0 ESDPD10: IsoVolt 120 must be in dntub 120V
24340 0 ESDPD10: IsoVolt 20 must be in dntub 20V
24341 0 ESDPD10: IsoVolt 50 must be in dntub 50V
24342 0 ESDPD10: IsoVolt 5 must be in dntub 5V
24346 0 ESDPNP40 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24360 0 ESDPNP40 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24361 0 ESDPNP40: IsoVolt 120 must be in dntub 120V
24362 0 ESDPNP40: IsoVolt 20 must be in dntub 20V
24363 0 ESDPNP40: IsoVolt 50 must be in dntub 50V
24364 0 ESDPNP40: IsoVolt 5 must be in dntub 5V
24368 0 ESDPNP42 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24382 0 ESDPNP42 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24383 0 ESDPNP42: IsoVolt 120 must be in dntub 120V
24384 0 ESDPNP42: IsoVolt 20 must be in dntub 20V
24385 0 ESDPNP42: IsoVolt 50 must be in dntub 50V
24386 0 ESDPNP42: IsoVolt 5 must be in dntub 5V
24390 0 ESDFDNI5 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24404 0 ESDFDNI5 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24405 0 ESDFDNI5: IsoVolt 120 must be in dntub 120V
24406 0 ESDFDNI5: IsoVolt 20 must be in dntub 20V
24407 0 ESDFDNI5: IsoVolt 50 must be in dntub 50V
24408 0 ESDFDNI5: IsoVolt 5 must be in dntub 5V
24412 0 ESDGCNI5 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24426 0 ESDGCNI5 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24427 0 ESDGCNI5: IsoVolt 120 must be in dntub 120V
24428 0 ESDGCNI5: IsoVolt 20 must be in dntub 20V
24429 0 ESDGCNI5: IsoVolt 50 must be in dntub 50V
24430 0 ESDGCNI5: IsoVolt 5 must be in dntub 5V
24434 0 ESDGCI20 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24448 0 ESDGCI20 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24449 0 ESDGCI20: IsoVolt 120 must be in dntub 120V
24450 0 ESDGCI20: IsoVolt 20 must be in dntub 20V
24451 0 ESDGCI20: IsoVolt 50 must be in dntub 50V
24452 0 ESDGCI20: IsoVolt 5 must be in dntub 5V
24456 0 ESDFDI50 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24470 0 ESDFDI50 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24471 0 ESDFDI50: IsoVolt 120 must be in dntub 120V
24472 0 ESDFDI50: IsoVolt 20 must be in dntub 20V
24473 0 ESDFDI50: IsoVolt 50 must be in dntub 50V
24474 0 ESDFDI50: IsoVolt 5 must be in dntub 5V
24478 0 ESDGCI3 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24492 0 ESDGCI3 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24493 0 ESDGCI3: IsoVolt 120 must be in dntub 120V
24494 0 ESDGCI3: IsoVolt 20 must be in dntub 20V
24495 0 ESDGCI3: IsoVolt 50 must be in dntub 50V
24496 0 ESDGCI3: IsoVolt 5 must be in dntub 5V
24500 0 ESDGCPI5 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24514 0 ESDGCPI5 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24515 0 ESDGCPI5: IsoVolt 120 must be in dntub 120V
24516 0 ESDGCPI5: IsoVolt 20 must be in dntub 20V
24517 0 ESDGCPI5: IsoVolt 50 must be in dntub 50V
24518 0 ESDGCPI5: IsoVolt 5 must be in dntub 5V
24522 0 ESDFDPI5 R2 Element Rule : HVDEF2 isoVoltage  text string missing
24536 0 ESDFDPI5 Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
24537 0 ESDFDPI5: IsoVolt 120 must be in dntub 120V
24538 0 ESDFDPI5: IsoVolt 20 must be in dntub 20V
24539 0 ESDFDPI5: IsoVolt 50 must be in dntub 50V
24540 0 ESDFDPI5: IsoVolt 5 must be in dntub 5V
24565 0 Voltage Definition : this text on met1 is not a valid text definition for sntub (+5,+20,+50)
24567 0 INFO : multiple text on MET1 for SNTUB voltage definition
24570 0 INFO : this sntub for LVT has 1205 Volt( SNLVT120V) not supported
24572 0 INFO : this sntub for LVT  has 50 Volt( SNLVT50V)
24574 0 INFO : this sntub  for LVT has 20 Volt( SNLVT20V)
24576 0 INFO : this sntub for LVT has 5 Volt( SNLVT5V)
24579 0 SNLVT Voltage : No voltage found for this sntub,  must have +5/+20/+50 on met1 conn to ntap ,assuming highest voltage 50 Volt for all checks
24580 0 SNLVT Voltage warning : found more different voltages ( 5, 20 )  for SNLVT, is this ok ??
24581 0 SNLVT Voltage warning : found more different voltages ( 5, 50 )  for SNLVT, is this ok ??
24582 0 SNLVT Voltage warning : found more different voltages ( 5, 120 )  for SNLVT, is this ok ??
24583 0 SNLVT Voltage warning : found more different voltages ( 20, 50 )  for SNLVT, is this ok ??
24584 0 SNLVT Voltage warning : found more different voltages ( 20, 120 )  for SNLVT, is this ok ??
24585 0 SNLVT Voltage warning : found more different voltages ( 50, 120 )  for SNLVT, is this ok ??
24597 0 INFO : This SNLVT has no LVT device,is this ok ?? ??
24599 0 W1LV Minimum LVTDEF width = 0.6
24602 0 S1LVLV Minimum LVTDEF spacing = 0.6
24609 0 E1LVAA Minimum LVTDEF enclosure of DIFF = 0.25
24611 0 S1AALV Minimum LVTDEF to DIFF spacing = 0.35
24612 0 LVR001 LVTDEF over ZENER is not allowed
24614 0 LVR002 LVTDEF outside GATE is not allowed
24623 0 LVR003 LVTDEF and not (SNTUB sized by 0.1) and not (DNTUB and RPTUB) is not allowed
24626 0 SNR007 Each SNLVT shape must be fully enclosed with RPTUB
24628 0 S5SNSN  Minimum SNLVT5V spacing to SNTUB = 1.7
24630 0 S6SNSN  Minimum SNLVT20V spacing to SNTUB = 2
24632 0 S7SNSN  Minimum SNLVT50V spacing to SNTUB = 5.5
24634 0 S3RPSN  Minimum SNLVT5V to RPTUB spacing outside DNTUB = 0
24636 0 S4RPSN  Minimum SNLVT20V to RPTUB spacing outside DNTUB = 0
24638 0 S5RPSN  Minimum SNLVT50V to RPTUB spacing outside DNTUB = 2
24641 0 E2SNND Minimum SNLVT5V enclosure of NTAP = 0.2
24644 0 E3SNND Minimum SNLVT20V enclosure of NTAP = 1
24647 0 E4SNND Minimum SNLVT50V enclosure of NTAP = 1
24651 0 E2SNPD Minimum SNLVT5V enclosure of PDIFF = 1.2
25042 0 SNR008 Utmost structures within SNLVT20V must be closed NTAP rings
25433 0 SNR009 Utmost structures within SNLVT50V must be closed NTAP rings
25449 0 E4RPPD Minimum RPTUB enclosure of PTAP outside DNTUB adjacent to SNLVT5V within 3um = 0.2
25459 0 E5RPPD Minimum RPTUB enclosure of PTAP outside DNTUB adjacent to SNLVT20V within 3um = 0.5
25469 0 E6RPPD Minimum RPTUB enclosure of PTAP outside DNTUB adjacent to SNLVT50V within 3um = 0.5
25476 0 PMOSSL_R1 : SNTUB voltage must be specified with MET1 text +5/+20/+50
25477 0 PMOSSML_R1 : SNTUB voltage must be specified with MET1 text +5/+20/+50
25478 0 PMOSIL_R1 : DNTUB voltage must be specified with MET1 text +5/+20/+50/+120
25479 0 PMOSIML_R1 : DNTUB voltage must be specified with MET1 text +5/+20/+50/+120
25480 0 NMOSIL_R1 : DNTUB voltage must be specified with MET1 text +5/+20/+50/+120
25481 0 NMOSIML_R1 : DNTUB voltage must be specified with MET1 text +5/+20/+50/+120
25485 0 PMOSIL_R1 Element Rule : isoVoltage  text string missing
25499 0 PMOSIL Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25500 0 PMOSIL IsoVolt 120 must be in dntub 120V
25501 0 PMOSIL IsoVolt 20 must be in dntub 20V
25502 0 PMOSIL IsoVolt 50 must be in dntub 50V
25503 0 PMOSIL IsoVolt 5 must be in dntub 5V
25507 0 PMOSIML_R1 Element Rule : isoVoltage  text string missing
25521 0 PMOSIML Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25522 0 PMOSIML IsoVolt 120 must be in dntub 120V
25523 0 PMOSIML IsoVolt 20 must be in dntub 20V
25524 0 PMOSIML IsoVolt 50 must be in dntub 50V
25525 0 PMOSIML IsoVolt 5 must be in dntub 5V
25529 0 NMOSIL_R1 Element Rule : isoVoltage  text string missing
25543 0 NMOSIL Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25544 0 NMOSIL IsoVolt 120 must be in dntub 120V
25545 0 NMOSIL IsoVolt 20 must be in dntub 20V
25546 0 NMOSIL IsoVolt 50 must be in dntub 50V
25547 0 NMOSIL IsoVolt 5 must be in dntub 5V
25551 0 NMOSIML_R1 Element Rule : isoVoltage  text string missing
25565 0 NMOSIML Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25566 0 NMOSIML IsoVolt 120 must be in dntub 120V
25567 0 NMOSIML IsoVolt 20 must be in dntub 20V
25568 0 NMOSIML IsoVolt 50 must be in dntub 50V
25569 0 NMOSIML IsoVolt 5 must be in dntub 5V
25573 0 PMOSSL_R1 Element Rule : isoVoltage  text string missing
25587 0 PMOSSL Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25588 0 PMOSSL IsoVolt 120 must be in snlvt 120V
25589 0 PMOSSL IsoVolt 20 must be in snlvt 20V
25590 0 PMOSSL IsoVolt 50 must be in snlvt 50V
25591 0 PMOSSL IsoVolt 5 must be in snlvt 5V
25595 0 PMOSSML_R1 Element Rule : isoVoltage  text string missing
25609 0 PMOSSML Element Rule : Voltage not found :  HVDEF2 isoVoltage= 120/50/20/5 missing
25610 0 PMOSSML IsoVolt 120 must be in snlvt 120V
25611 0 PMOSSML IsoVolt 20 must be in snlvt 20V
25612 0 PMOSSML IsoVolt 50 must be in snlvt 50V
25613 0 PMOSSML IsoVolt 5 must be in snlvt 5V
25616 0 ILL_ELEMENT_RPOLY2P_RPOLY2PH Process Modules: RPOLY2P and RPOLY2PH are mutually exclusive
25617 0 NTUB net layer must not be used in layout view
25618 0 DIFF net layer must not be used in layout view
25619 0 POLY1 net layer must not be used in layout view
25620 0 POLY2 net layer must not be used in layout view
25621 0 CONT net layer must not be used in layout view
25622 0 MET1 net layer must not be used in layout view
25623 0 VIA1 net layer must not be used in layout view
25624 0 MET2 net layer must not be used in layout view
25625 0 VIA2 net layer must not be used in layout view
25626 0 MET3 net layer must not be used in layout view
25627 0 VIA3 net layer must not be used in layout view
25628 0 MET4 net layer must not be used in layout view
25629 0 PAD net layer must not be used in layout view
25638 0 REC002 NTUB not multiple 45 degrees REC002
25639 0 REC002 DIFF not multiple 45 degrees REC002
25640 0 REC002 MIDOX not multiple 45 degrees REC002
25644 0 REC002 POLY1 not multiple 45 degrees REC002
25645 0 REC002 NPLUS not multiple 45 degrees REC002
25646 0 REC002 PPLUS not multiple 45 degrees REC002
25647 0 REC002 HRES not multiple 45 degrees REC002
25648 0 REC002 CONT not multiple 45 degrees REC002
25652 0 REC002 MET1 not multiple 45 degrees REC002
25653 0 REC002 VIA1 not multiple 45 degrees REC002
25655 0 REC002 MET2 not multiple 45 degrees REC002
25656 0 REC002 VIA2 not multiple 45 degrees REC002
25657 0 REC002 MET3 not multiple 45 degrees REC002
25658 0 REC002 VIA3 not multiple 45 degrees REC002
25659 0 REC002 MET4 not multiple 45 degrees REC002
25660 0 REC002 PAD not multiple 45 degrees REC002
25679 0 INFO: hot nwell
25682 0 NW_W_1 Minimum NTUB width = 1.7
25685 0 NW_W_2 Minimum HOT_NTUB width = 3
25692 0 NW_S_1 Minimum spacing of NTUB with different potential = 3
25695 0 NW_S_2 Minimum spacing of NTUB with same potential = 1
25697 0 NW_S_2 Minimum spacing of NTUB with same potential = 1 notch
25710 0 OD_W_1 Minimum DIFF width to define the width of NMOS / PMOS = 0.4 ngate
25719 0 OD_W_1 Minimum DIFF width to define the width of NMOS / PMOS = 0.4 pgate
25721 0 OD_W_2 Minimum DIFF width for interconnection (NDIFF or PDIFF) = 0.3
25724 0 OD_S_1 Minimum DIFF spacing = 0.6
25726 0 OD_S_1 Minimum DIFF spacing = 0.6 notch 
25732 0 OD_C_1 Minimum NTUB enclosure of NDIFF = 0.2
25735 0 OD_C_2 Minimum NDIFF to NTUB spacing = 1.2
25751 0 OD_C_3 Minimum NDIFF to HOT_NTUB spacing (without PTAP in between) = 2.6
25755 0 OD_C_4 Minimum NTUB enclosure of PDIFF = 1.2
25757 0 OD_C_5 Minimum PDIFF to NTUB spacing = 0.2
25763 0 OD_C_6a Minimum PDIFF to NGATE spacing = 0.45
25770 0 OD_C_6b Minimum NDIFF to PGATE spacing = 0.45
25778 0 OD_S_2B Minimum NDIFF to non-butting PDIFF spacing = 0.6
25779 0 INFO : nplus pplus overlap
25787 0 INFO: DIFF missing nplus/pplus
25789 0 W1TX Minimum MIDOX width = 0.6
25797 0 OD2_E_1 Minimum MIDOX enclosure of DIFF = 0.6
25800 0 OD2S1 Minimum MIDOX spacing = 0.6
25802 0 OD2_C_1 Minimum MIDOX to DIFF spacing = 0.6
25804 0 BAD1TX MIDOX must overlap GATE
25812 0 PO_W_1a Minimum GATE length of PMOS = 0.35
25814 0 PO_W_1b Minimum GATE length of PMOSM = 0.5
25816 0 PO_W_2a Minimum GATE length of NMOS = 0.35
25818 0 PO_W_2b Minimum GATE length of NMOSM = 0.5
25826 0 PO_W_3 Minimum POLY1 width for interconnect = 0.35
25829 0 PO_S_1 Minimum POLY1 spacing = 0.45 
25831 0 PO_S_1 Minimum POLY1 spacing = 0.45 notch
25833 0 PO_C_1 Minimum POLY1 to DIFF spacing = 0.2
25843 0 PO_C_2 Minimum DIFF extension of GATE = 0.5
25853 0 PO_O_1 Minimum POLY1 extension of GATE = 0.4
25855 0 PO_R_1 Minimum density of POLY1 area [%] Density = total poly layer area / chip area Recommended dummy structures are 5um * 2um rectangles with 2um spacing. They should not be placed on active devices. = 14
25857 0 PO2_W_1 Minimum CPOLY width = 0.8
25860 0 PO2_S_1 Minimum CPOLY spacing = 0.65
25863 0 PO2_E_1 Minimum POLY1 enclosure of CPOLY = 1
25866 0 PO2_E_2 Minimum CPOLY enclosure of POLY2CON = 0.6
25868 0 PO2_C_1 Minimum POLY1CON to CPOLY spacing = 1.2
25870 0 PO2_W_2 Minimum POLY2 width = 0.65
25873 0 PO2_S_2 Minimum POLY2 spacing = 0.5
25875 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
25877 0 PO2_W_3 Minimum RPOLYH width = 0.8
25880 0 PO2_S_3 Minimum RPOLYH spacing = 0.75
25882 0 PO2_S_3 Minimum RPOLYH spacing = 0.75 notch
25884 0 PO2_C_2 Minimum DIFF to POLY2 spacing = 0.2
25886 0 PO2_C_3 Minimum POLY1 to POLY2 spacing = 0.65
25891 0 PO2_E_3 Minimum POLY2 enclosure of POLY2CON = 0.25
25892 0 PO2_R_1 POLY2 on DIFF is not allowed
25894 0 PP_W_1 Minimum PPLUS width = 0.6
25897 0 PP_S_1 Minimum PPLUS spacing = 0.6
25899 0 PP_C_1 Minimum PPLUS to DIFF spacing = 0.35
25906 0 PP_C_2 Minimum PPLUS to NGATE spacing = 0.45
25914 0 PP_C_3 Minimum PPLUS extension of PGATE = 0.45
25916 0 PP_O_1  Minimum overlap of PPLUS and DIFF = 0.45
25919 0 PP_E_1 Minimum PPLUS extension of DIFF = 0.25
25926 0 NP_C_5 PP_C_5  Minimum PPLUS to NPLUS spacing on POLY1 = 0.25
25928 0 PP_C_6 Minimum PPLUS to NPLUS spacing on DIFF with same potential = 0
25930 0 NP_W_1 Minimum NPLUS width = 0.6
25933 0 NP_S_1 Minimum NPLUS spacing = 0.6
25937 0 NP_C_1 Minimum NPLUS to DIFF spacing = 0.35
25944 0 NP_C_2 Minimum NPLUS to PGATE spacing = 0.45
25952 0 NP_C_3 Minimum NPLUS extension of NGATE = 0.45
25954 0 NP_O_1  Minimum overlap of NPLUS and DIFF = 0.45
25957 0 NP_E_1 Minimum NPLUS extension of DIFF = 0.25
25959 0 NP_C_6 Minimum NPLUS to PPLUS spacing on DIFF with same potential = 0
25961 0 CO_W_1 Fixed CONT width = 0.4
25964 0 CO_S_1 Minimum CONT spacing = 0.4
25966 0 CO_C_1 Minimum DIFFCON to GATE spacing = 0.3
25968 0 CO_C_2  Minimum POLY1CON to DIFF spacing = 0.4
25971 0 CO_E_1 Minimum DIFF enclosure of DIFFCON = 0.15
25974 0 CO_E_2 Minimum POLY1 enclosure of POLY1CON = 0.2
25988 0 CO_E_3 Minimum PPLUS enclosure of PDIFFCON = 0.25
26009 0 CO_E_4  Minimum NPLUS enclosure of NDIFFCON = 0.25
26010 0 CO_R_1 POLY1CON on DIFF is not allowed
26013 0 CO_R_2 Butted CONT is not allowed
26014 0 R01C0 CONT without DIFF or POLY1 or POLY2 is not allowed
26015 0 ERC Warning: CONT without metal1
26016 0 ERC Warning: CONT without diff or poly
26018 0 M1_W_1 Minimum MET1 width = 0.5
26021 0 M1_S_1  Minimum MET1 spacing = 0.45
26064 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide wide
26066 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide small
26071 0 M1_E_1 Minimum MET1 enclosure of CONT = 0.15
26073 0 M1_R_1 Minimum density of MET1 area [%] = 30
26075 0 VIA1_W_1 Fixed VIA1 width = 0.5
26078 0 VIA1_S_1 Minimum VIA1 spacing = 0.45
26083 0 VIA1_E_1 Minimum MET1 enclosure of VIA1 = 0.2
26084 0 R01V1 VIA1 without MET1 is not allowed
26085 0 ERC Warning: Via1 missing metal1
26087 0 M2_W_1 Minimum MET2 width = 0.6
26090 0 M2_S_1 Minimum MET2 spacing = 0.5
26133 0 M2_S_2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide wide
26135 0 M2S2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide small
26140 0 M2_E_1 Minimum MET2 enclosure of VIA1 = 0.15
26142 0 M2_R_1 Minimum density of MET2 area [%] = 30
26144 0 VIA2_W_1 Fixed VIA2 width = 0.5
26147 0 VIA2_S_1 Minimum VIA2 spacing = 0.45
26152 0 VIA2_E_1 Minimum MET2 enclosure of VIA2 = 0.2
26153 0 R01V2 VIA2 without MET2 is not allowed
26154 0 ERC Warning: Via2 missing metal2
26156 0 M3_W_1  Minimum MET3 width = 0.6
26159 0 M3_S_1 Minimum MET3 spacing = 0.5
26164 0 M3_E_1 Minimum MET3 enclosure of VIA2 = 0.15
26207 0 M3S2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide wide 
26209 0 M3_S_2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide small
26211 0 M3_R_1 Minimum density of MET3 area [%] = 30
26213 0 VIA3_W_1 Fixed VIA3 width = 0.5
26216 0 VIA3_S_1 Minimum VIA3 spacing = 0.45
26221 0 VIA3_E_1 Minimum MET3 enclosure of VIA3 = 0.2
26222 0 R01V3 VIA3 without MET3 is not allowed
26223 0 ERC Warning: VIA3 missing met3
26225 0 W1M4 Minimum MET4 width = 2.5
26228 0 S1M4M4 Minimum MET4 spacing = 2
26233 0 E1M4V3 Minimum MET4 enclosure of VIA3 = 0.5
26235 0 R01M4 Minimum density of MET4 area [%] = 30
26236 0 ERC Warning: VIA3 missing met4
26241 0 INFO: illegal diffusion on pad
26243 0 INFO: illegal poly1 on pad
26245 0 INFO: illegal poly2 on pad
26247 0 INFO: illegal contact on pad
26249 0 CB_R_1 CB_R_1 Bond stack PAD_ST missing met1
26251 0 CB_R_1 CB_R_1 Bond stack PAD_ST missing met2
26253 0 CB_R_1 CB_R_1 Bond stack PAD_ST missing met3
26256 0 CB_R_1 CB_R_1 Bond stack PAD_ST missing met4
26257 0 ERC Warning: Missing top met4 on Test or Probe pad
26259 0 W1PA Minimum PAD width = 15
26263 0 CB_W_1  Minimum bonding PAD width = 85  preferred
26265 0 CB_W_1 Minimum bonding PAD width (85um preferred, 60um on request) = 70
26268 0 CB_S_1 Minimum PAD spacing = 15
26272 0 CB_E_1 Minimum MET1 enclosure of PAD_ST = 5
26276 0 CB_E_2 Minimum MET2 enclosure of PAD_3OA/PAD_ST = 5
26279 0 CB_E_3 Minimum MET3 enclosure of PAD = 5
26282 0 CB_E_4 Minimum MET4 enclosure of PAD = 5
26301 0 CB_E_5 Minimum MET1 enclosure of the nearest PADVIA1 = 3
26344 0 CBE5 bad diamond shape of pad via array must have 4 corners
26347 0 CBE5 bad diamond shape of pad via array
26348 0 CBE7 bad diamond shape of padvia2 array must have 4 corners
26351 0 CBE7 bad diamond shape of padvia2 array
26362 0 CBE9 bad diamond shape of padvia3 array must have 4 corners
26365 0 CBE9 bad diamond shape of padvia3 array
26368 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia1
26371 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia2
26374 0 CB_E_9  Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
26377 0 CB_E_9 Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
26380 0 CB_E_11 Minimum MET4 enclosure of the nearest PADVIA3 = 3
26383 0 CB_S_2 Minimum PADVIA1 spacing = 0.8
26386 0 CB_S_3 Minimum PADVIA2 spacing = 0.8
26389 0 CB_S_4 Minimum PADVIA3 spacing = 0.8
26391 0 CB_C_1 Minimum PADVIA2 to PADVIA1 spacing = 0.3
26393 0 CB_C_2 Minimum PADVIA3 to PADVIA2 spacing = 0.3
26395 0 CB_R_2 Minimum ratio of PADVIA1 area to PAD_ST area [%] = 5
26397 0 CB_R_3 Minimum ratio of PADVIA2 area to PAD_ST area [%] = 5
26399 0 CB_R_4 Minimum ratio of PADVIA3 area to PAD_ST area [%] = 5
26400 0 CB_C_1 Illegal pad via stack via1/via2
26401 0 CB_C_2 Illegal pad via stack via2/via3
26406 0 S1DFPA Minimum PAD_ST to DIFF spacing = 9
26408 0 S1P1PA Minimum PAD_ST to POLY1 spacing = 9
26410 0 S1P2PA Minimum PAD_ST to POLY2 spacing = 9
26413 0 S1M1PA Minimum PAD_ST to MET1 spacing (different net) = 9
26416 0 S1M2PA Minimum PAD_ST to MET2 spacing (different net) = 9
26419 0 S1M3PA Minimum PAD_ST to MET3 spacing (different net) = 9
26422 0 S1M4PA Minimum PAD_ST to MET4 spacing (different net) = 9
26423 0 R01PA PAD without MET4 is not allowed
26424 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET1
26427 0 Illegal POA pad met3 stack for 4 metal process
26429 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET2
26431 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
26433 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
26435 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
26436 0 PAR006 : PAD_4OA overlapping VIA2 is not allowed
26439 0 S2PAV2 : Minimum PAD_4OA to VIA2 spacing = 0.5
26442 0 S1PAV3 : Minimum PAD_4OA to VIA3 spacing = 0.25
26446 0 E1PAV3 Minimum PAD_4OA enclosure of VIA3 = 0.2
26454 0 PAR007 : (PAD_4OA sized by -0.7) overlapping VIA3 is not allowed
26455 0 PAR002 KEPOUT definition : (PAD_4OA AND KEPOUT) is not allowed
26458 0 S2KOPA KEPOUT definition : Minimum spacing PAD_4OA to (KEPOUT or SFCDEF) = 7
26464 0 S2M3PA Minimum PAD_4OA to MET3 spacing (different net) = 7
26467 0 S2M4PA Minimum PAD_4OA to MET4 spacing (different net) = 7
26468 0 PAR010 : PAD_OA overlapping CPOLY is not allowed
26519 0 PAR008 Density : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3,via3 density probably too small for this rule
26548 0 PAR008 Density : use 1 row of via3 at min ovlp of PAD poa
26566 0 PAR008 : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3
26613 0 PAR009 : LV_GATE L > 0.5 PAD_OA overlapping GATE is not allowed,  No valid exemption for LV_GATE, L > 0.5
26619 0 PAR009 : LV_GATE L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for LV_GATE, L <= 0.5, but total W < 400 U
26655 0 PAR009 : NMOS50M/NMOS50T L > LMIN  PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26670 0 PAR009 : NMOS50M/NMOS50T L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26685 0 PAR009 : NMOS50H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.0 LMIN
26698 0 PAR009 : NMOS50H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.0 LMIN, but total W < 400 U
26734 0 PAR009 : NMOS20M/NMOS20T  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26749 0 PAR009 : NMOS20M/NMOS20T L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26764 0 PAR009 : NMOS20H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26779 0 PAR009 : NMOS20H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26810 0 PAR009 : NMOSD20M  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26823 0 PAR009 : NMOSD20M L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26858 0 PAR009 : NMOSI50M/T/H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26873 0 PAR009 : NMOSI50T/M/H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26904 0 PAR009 : NMOSDI50H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26919 0 PAR009 : NMOSDI50H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26955 0 PAR009 : NMOSI20M/H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
26970 0 PAR009 : NMOSI20M/H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
26985 0 PAR009 : NMOSI20T  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.7 LMIN
27000 0 PAR009 : NMOSI20T L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.7 LMIN, but total W < 400 U
27033 0 PAR009 : NMOSDI20M/H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
27048 0 PAR009 : NMOSDI20M/H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
27079 0 PAR009 : NMOS50HS  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 4.0 LMIN
27094 0 PAR009 : NMOS50HS L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 4.0 LMIN, but total W < 400 U
27125 0 PAR009 : NMOS20HS  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.8 LMIN
27140 0 PAR009 : NMOS20HS L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.8 LMIN, but total W < 400 U
27171 0 PAR009 : NMOS10MH  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.4 LMIN
27186 0 PAR009 : NMOS10MH L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.4 LMIN, but total W < 400 U
27217 0 PAR009 : NMOSD10MH  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.4 LMIN
27232 0 PAR009 : NMOSD10MH L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.4 LMIN, but total W < 400 U
27265 0 PAR009 : NMOSI120MH  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
27280 0 PAR009 : NMOSI120MH L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
27319 0 PAR009 : PMOS50M/PMOS50T  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.0 LMIN
27334 0 PAR009 : PMOS50M/PMOS50T L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.0 LMIN, but total W < 400 U
27349 0 PAR009 : PMOS50H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.4 LMIN
27364 0 PAR009 : PMOS50H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.4 LMIN, but total W < 400 U
27403 0 PAR009 : PMOS20M/PMOS20T  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.6 LMIN
27418 0 PAR009 : PMOS20M/PMOS20T L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.6 LMIN, but total W < 400 U
27433 0 PAR009 : PMOS20H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.1 LMIN
27448 0 PAR009 : PMOS20H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.1 LMIN, but total W < 400 U
27479 0 PAR009 : PMOSD20M/H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.6 LMIN
27494 0 PAR009 : PMOSD20M/H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.6 LMIN, but total W < 400 U
27525 0 PAR009 : PMOS50HS  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 2.8 LMIN
27540 0 PAR009 : PMOS50HS L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 2.8 LMIN, but total W < 400 U
27571 0 PAR009 : PMOS20HS  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.2 LMIN
27586 0 PAR009 : PMOS20HS L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.2 LMIN, but total W < 400 U
27617 0 PAR009 : PMOS10MH  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
27632 0 PAR009 : PMOS10MH L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
27663 0 PAR009 : PMOSD10MH  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
27678 0 PAR009 : PMOSD10MH L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
27715 0 PAR009 : PMOS120M  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.0 LMIN
27730 0 PAR009 : PMOS120M L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.0 LMIN, but total W < 400 U
27745 0 PAR009 : PMOS120H  L > LMIN PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 1.2 LMIN
27760 0 PAR009 : PMOS120H L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 1.2 LMIN, but total W < 400 U
27788 0 PAR009 : NMOSH  L > LMIN PAD_OA overlapping NMOSH_GATE is not allowed,  No valid exemption for NMOSH GATE, L > 3.0
27794 0 PAR009 : NMOSH L=LMIN W < 400 PAD_OA overlapping NMOSH_GATE is not allowed, No valid exemption for NMOSH__GATE, L <= 3.0, but total W < 400 U
27827 0 PAR009: ALL HV/LV GATES PAD_4OA overlapping GATE is not allowed,  Exemptions : HV_GATE  with HVDEF text ESD*/ LV_GATE L <= 0.5, total active trans W >= 400/ HV_GATE L = MIN, total active trans W >= 400 / LV_GATE overlapping holed POLY1 ..waffel trans
27829 0 W1HR Minimum HRES width = 0.6
27832 0 S1HRHR Minimum HRES spacing = 0.6
27833 0 BAD1HR HRES is not allowed over DIFF
27834 0 BAD2HR HRES is not allowed over NPLUS
27835 0 BAD3HR HRES is not allowed over POLY1
27839 0 E1HRP2 Minimum HRES enclosure of POLY2 = 3
27841 0 S1HRP1 Minimum HRES to POLY1 spacing = 0.35
27843 0 S1HRP2 Minimum HRES to POLY2 spacing = 3
27845 0 S1AAHR  Minimum HRES to DIFF spacing = 0.35
27846 0 INFO : metcap not inside met2
27849 0 W1MC Minimum METCAP width
27852 0 W2MC Minimum dummy METCAP width = 0.5
27862 0 W3MC Maximum METCAP size = 30
27863 0 W1M2  Maximum MET2 size (capacitor bottom plate ) = 35
27866 0 S1MCMC Minimum METCAP spacing
27868 0 S1M2M2 Minimum MET2 spacing (capacitor bottom plate) = 0.8
27872 0 S1MCV1 Minimum spacing between VIA1 and METCAP = 0.5
27876 0 S1MCV2 Minimum spacing between VIA2 and METCAP = 0.5
27881 0 S1V2V2  Minimum VIA2 spacing on MET2 bottom plate outside METCAP = 4
27885 0 S2V2V2  Minimum VIA2 spacing on METCAP
27890 0 E1M2MC Minimum MET2 enclosure of METCAP = 1
27902 0 E1M2V1 Minimum MET2 enclosure of VIA1 (capacitor bottom plate) = 0.2
27905 0 E1M2V2 Minimum MET2 enclosure of VIA2 (capacitor bottom plate) = 0.2
27909 0 E1MCV2 Minimum METCAP enclosure of VIA2
27911 0 R1MC Minimum METCAP density [%] = 3
27914 0 R1V2 Minimum VIA2 density inside METCAP [%] = 1
27915 0 BAD1M1 MET1 under METCAP region is not allowed
27934 0 CMIM_G1: cmim device over active or passive device not allowed
27935 0 CPOLY_G1 PPLUS on CPOLY is not allowed
27936 0 CPOLY_G2 NPLUS on CPOLY is not allowed
27937 0 RPOLY1_R1 PPLUS on RPOLY1 is not allowed
27938 0 RPOLY1_R2 NPLUS on RPOLY1 is not allowed
27939 0 RPOLY2_R1 PPLUS on RPOLY2 is not allowed
27940 0 RPOLY2_R2 NPLUS on RPOLY2 is not allowed
27941 0 RPOLY2P_R1 PPLUS on RPOLY2P is not allowed
27942 0 RPOLY2P_R2 NPLUS on RPOLY2P is not allowed
27943 0 RPOLY2PH_R1 PPLUS on RPOLY2PH is not allowed
27944 0 RPOLY2PH_R2 NPLUS on RPOLY2PH is not allowed
27947 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6
27948 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6 missing pplus
27957 0 S1IPP2 Minimum PPLUS to RPOLYH spacing = 0.35
27959 0 REC016 Minimum high precision RPOLYH width = 2
28297 0 AMW0 Maximum METx width = 35 metal1
28299 0 AMW0 Maximum METx width = 35 metal2
28301 0 AMW0 Maximum METx width = 35 metal3
28303 0 AMW0 Maximum METx width = 35 metal4
28305 0 AMW1 Fixed slot width = 3 metal1
28308 0 AMW1 Fixed slot width = 3  metal1toolarge
28310 0 AMW1 Fixed slot width = 3 metal2
28313 0 AMW1 Fixed slot width = 3  metal2toolarge
28315 0 AMW1 Fixed slot width = 3 metal3
28318 0 AMW1 Fixed slot width = 3  metal3toolarge
28320 0 AMW1 Fixed slot width = 3 metal4
28323 0 AMW1 Fixed slot width = 3  metal4toolarge
28325 0 AML1 AML2 Minimum slot length = 30 Maximum slot length = 300 metal1
28327 0 AML1 AML2 Minimum slot length = 30 Maximum slot length = 300 metal2
28329 0 AML1 AML2 Minimum slot length = 30 Maximum slot length = 300 metal3
28331 0 AML1 AML2 Minimum slot length = 30 Maximum slot length = 300 metal4
28334 0 AMS1 Minimum spacing between two parallel slots = 10 metal1
28337 0 AMS1 Minimum spacing between two parallel slots = 10 metal2
28340 0 AMS1 Minimum spacing between two parallel slots = 10 metal3
28343 0 AMS1 Minimum spacing between two parallel slots = 10 metal4
28345 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met1 met2 
28347 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met2 met3 
28348 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met1 met2 overlap 
28349 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met2 met3 overlap 
28351 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met3 met4 
28352 0 AMC1 Minimum slots spacing between neighbor layers  = 2 met3 met4 overlap 
28355 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal1
28358 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal2
28361 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal3
28364 0 AMC2 AMC3 Minimum slot to inner metal edge spacing = 10 metal4
28365 0 AM ERROR BAD SLOT: met1 slot outside met1
28366 0 AM ERROR BAD SLOT: met2 slot outside met2
28367 0 AM ERROR BAD SLOT: met3 slot outside met3
28368 0 AM ERROR BAD SLOT: met1 slot over cont
28369 0 AM ERROR BAD SLOT: met1 slot over via1
28370 0 AM ERROR BAD SLOT: met2 slot over via1
28371 0 AM ERROR BAD SLOT: met2 slot over via2
28372 0 AM ERROR BAD SLOT: met3 slot over via2
28373 0 AM ERROR BAD SLOT: met4 slot outside met4
28374 0 AM ERROR BAD SLOT: met4 slot over via3
28378 0 AMTW1 AMTL1 fixed with of dummy MTOP thick blocks 2.5 x 5.0 U
28380 0 AMTS2  Minimum MTOP feature to dummy MTOP thick block spacing = 2
29068 0 AMTS1 Maximum MTOP spacing when the width of one or both MTOP shapes is less than 10um. = 10
29173 0 AMTS3 maximum met4 to met4 block spacing
29176 0  AMTS4 fixed met4 block spacing (checked min only 2.0 U)
29179 0 Recommendation: Fixed RESTRM enclosure of RESDEF edge 0.1
29182 0 Recommendation: Fixed RESTRM enclosure of TUBDEF edge 0.1
29187 0 Warning: Illegal Layout Convention: RESDEF/TUBDEF missing RESTRM
29190 0 Warning: Illegal Layout Convention: RESTRM missing RESDEF
29192 0 INFO: Probe pad with probe layer
29197 0 ERC Warning: Missing met4 and/or via3 on Probe Pad
29201 0 ERC Warning: met4 on Probe Pad too small
29203 0 ERC Warning: Minimum PROBE width = 3 U
29205 0 PYR001 PCOAT outside SFCDEF will be removed and regenerated
29207 0 Minimum PCOAT width = 15
29210 0 Minimum PCOAT spacing = 15
29211 0 REC002 PCOAT not multiple 45 degrees PCOAT
29214 0 W1BK Minimum PCOAT_black width = 2
29217 0 S1BKBK Minimum PCOAT_black spacing = 2.0
29219 0 S1BKPA Minimum PCOAT_blackto PAD spacing = 3.0
29222 0 S1BKSB Minimum PCOAT_black to CHIPEDGE spacing = 20.0
29225 0 W1CR Minimum PCOAT_clear width = 2
29228 0 S1CRCR Minimum PCOAT_clear spacing = 2.0
29230 0 S1CRPA Minimum PCOAT_clear to PAD spacing = 3.0
29233 0 S1CRSB Minimum PCOAT_clear to CHIPEDGE spacing = 20.0
29236 0 W1GN Minimum PCOAT_green width = 2
29239 0 S1GNGN Minimum PCOAT_green spacing = 2.0
29241 0 S1GNPA Minimum PCOAT_greento PAD spacing = 3.0
29244 0 S1GNSB Minimum PCOAT_green to CHIPEDGE spacing = 20.0
29247 0 W1RD Minimum PCOAT_red width = 2
29250 0 S1RDRD Minimum PCOAT_red spacing = 2.0
29252 0 S1PARD Minimum PCOAT_red to PAD spacing = 3.0
29255 0 S1RDSB Minimum PCOAT_red to CHIPEDGE spacing = 20.0
29258 0 W1BU Minimum PCOAT_blue width = 2
29261 0 S1BUBU Minimum PCOAT_blue spacing = 2.0
29263 0 S1BUPA Minimum PCOAT_blue to PAD spacing = 3.0
29266 0 S1BUSB Minimum PCOAT_blue to CHIPEDGE spacing = 20.0
29272 0 ERC Warning: DIFF without any contact
29275 0 ERC Warning: Floating Poly1
29276 0 ERC Warning: Floating Poly2
29279 0 ERC Warning: Floating met1
29282 0 ERC Warning: Floating met2
29285 0 ERC Warning: Floating met3
29288 0 ERC Warning: Floating met4
29310 0 ERC Warning: HV Gates connected to VDD/VCC
29311 0 ERC Warning: HV Gates connected to VSS/GND
29312 0 ERC Warning: LV Gates connected to VDD/VCC
29313 0 ERC Warning: LV Gates connected to VSS/GND
29367 0 ERC Warning: floating gate not connected to s/d, pad, pin or resistor
29437 0 ERC Warning: Distance nwell taps > 50
29508 0 ERC Warning: Distance pwell taps > 50
29510 0 ERC Warning: illegal contact covering poly2 resistor
29512 0 ERC Warning: illegal contact covering poly2p resistor
29514 0 ERC Warning: illegal contact covering poly2ph resistor
29517 0 ERC Warning: illegal contact covering ndiff resistor
29520 0 ERC Warning: illegal contact covering pdiff resistor
29521 0 ERC Warning: illegal contact covering rpolyh resistor
29523 0 ERC Warning: illegal contact covering nwell resistor
29529 0 ERC Warning: illegal POLY2 touching rpoly2 resistor outside or bad cut layer
29530 0 ERC Warning: illegal poly2cut touching rpolyh resistor
29534 0 ERC Warning: illegal NTUB touching rnwell resistor outside
29540 0 ERC Warning: illegal pdiff touching rdiffp resistor outside
29546 0 ERC Warning: illegal ndiff touching rdiffn resistor outside
29691 0 ERC Warning: Latchup rule LAT3 distance s/d diff ngate net_subtap > 20
29823 0 ERC Warning: Latchup rule LAT3 distance s/d diff pgate net_welltap > 20
29830 0 BAD_PDIFF_MULTCONN_ERC
29835 0 BAD_NDIFF_MULTCONN_ERC
29968 0 S2AAP1 : Minimum POLY1_120V to DIFF spacing (different net, not over HVDEF) = 0.6 ( different nets, not over HVDEF )
29976 0 S3P1P1 : Minimum POLY1_120V to POLY1 spacing (different net, not over HVDEF) = 1.0 ( different nets, not over HVDEF )
30012 0 S2AAP2 : Minimum POLY2_120V to DIFF spacing (different net) = 0.6 ( different nets)
30020 0 S3P2P2 : Minimum POLY2_120V to POLY2 spacing (different net, not over HVDEF) = 1.0 ( different nets, not over HVDEF )
30028 0 S2M1M1 : Minimum MET1_120V to MET1 spacing  (different net, not over HVDEF) = 1 ( different nets, not over HVDEF )
30034 0 S2M2M2 :  Minimum MET2_120V to MET2 spacing  (different net) = 1 ( different nets)
30040 0 S2M3M3 : Minimum MET3_120V to MET3 spacing  (different net) = 1  ( different nets)
30044 0 AR1_error_gate: AR1: Maximum ratio of floating POLY1 edge area to connected GATE area t1(POLY1)=0.282um = 200
30046 0 AR2_error_gate: AR2: Maximum ratio of floating MET1 edge area to connected GATE area t1(MET1)=0.665um = 400
30048 0 AR3_error_gate: AR3: Maximum ratio of floating MET2 edge area to connected GATE area t1(MET2)=0.64um = 400
30050 0 AR4_error_gate: AR4: Maximum ratio of floating MET3 edge area to connected GATE area t1(MET3)=0.64um = 400
30052 0 AR5_error_gate: AR5: Maximum ratio of floating MET4 edge area to connected GATE area t1(MET4)=2.8um = 400
30053 0 rpoly1_g1_pres1_wexp: RPOLY1_G1: Minimum number of RPOLY1 squares = 5
30054 0 rpoly2_g1_pres_wexp: RPOLY2_G1: Minimum number of RPOLY2 squares = 5
30055 0 rpoly2p_g1_presp_wexp: RPOLY2P_G1: Minimum number of RPOLY2P squares = 5
30056 0 rpoly2ph_g1_presph_wexp: RPOLY2PH_G1: Minimum number of RPOLY2PH squares = 5
30057 0 rnwell_g1_nwres_wexp: RNWELL_G1: Minimum number of squares = 5
30058 0 rpolyh_g1_presh_wexp: RPOLYH_G1: Minimum number of RPOLYH squares = 5
30059 0 rnwell_s_g1_nwres_s_wexp: RNWELLS_G1: Minimum number of squares = 5
30060 0 pwres_r_g1_pwres_r_wexp: RPWELLR_G1: Minimum number of squares = 5
30061 0 pdres_all_g1_pdres_all_wexp: RDIFFPS_G1: Minimum number of squares = 5
30062 0 ndres_all_g1_ndres_all_wexp: RDIFFNR_G1: Minimum number of squares = 5
30063 0 G01P1_error_net_poly1con: G01P1: Maximum ratio of POLY2 area to connected CONT area = 18000
30064 0 G01P2_error_net_poly2con: G01P2: Maximum ratio of POLY2 area to connected CONT area = 22000
30072 0 CBR1 PAD met2 not connected to met1
30073 0 CBR1 PAD met3 not connected to met2
30074 0 CBR1 PAD met4 not connected to met3
30081 0 ERC Warning NDIFF and butting PDIFF must be connected with MET1
30082 0 # H35B4 (Last updated 20-Nov-2018 10:48) #
