*******************************************************************************
****** PWRCUT_DIG_P_DXS_HV cmos_sch IOLIB_HV_4M  <vs>  PWRCUT_DIG_P_DXS_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DN_PS) DIO                                       6       6
(PD_SN) DIO                                       4      26*
                                             ------  ------
Total                                            10      32

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(DN_PS) DIO                                       6       6           6       6
(PD_SN) DIO                                       4      26*          4       4
                                             ------  ------      ------  ------
Total                                            10      32          10      10

*******************************************************************************
****** APRIOP_HV schematic IOLIB_ANA_HV_4M  <vs>  APRIOP_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PD_SN) DIO                                       3      33*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       3       5*
(ND_SP) DIO                                       1       1
(RPOLY2) RES                                      9       9
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
                                             ------  ------
Total                                            17      51

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(RPOLY2) RES                                      9       9           2       2
(DN_PS) DIO                                       3       5*          3       3
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       3      33*          3       3
                                             ------  ------      ------  ------
Total                                            17      50          10      10

*******************************************************************************
****** APRIO200P_HV schematic IOLIB_ANA_HV_4M  <vs>  APRIO200P_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PD_SN) DIO                                       3      33*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       3       5*
(ND_SP) DIO                                       1       1
(RPOLY2) RES                                      9       9
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
                                             ------  ------
Total                                            17      51

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(RPOLY2) RES                                      9       9           3       3
(DN_PS) DIO                                       3       5*          3       3
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       3      33*          3       3
                                             ------  ------      ------  ------
Total                                            17      50          11      11

*******************************************************************************
****** AVDD3ALLP_HV schematic IOLIB_ANA_HV_4M  <vs>  AVDD3ALLP_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DP_DN) DIO                                       1       1
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(SHORT) RES                                       2      28*
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             6      42

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       2      28*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             6      41           6       6

*******************************************************************************
****** AGND3ALLP_HV schematic IOLIB_ANA_HV_4M  <vs>  AGND3ALLP_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DN_PS) DIO                                       1       1
(DP_DN) DIO                                       1       1
(RPOLY1) RES                                      1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(SHORT) RES                                       3      22*
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             7      36

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       3      22*          1       1
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             7      35           5       5

*******************************************************************************
****** BU2P_HV cmos_sch IOLIB_HV_4M  <vs>  BU2P_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3      21*
(NMOSI) MOS                                       3      13*
(RDIFFPS) RES                                     2       2
(g_proto_HV schematic IOLIB_HV_4M, _) Cell        1       0*
(esdnmosi schematic ESDLIB, _) Cell               2       0*
(esdpmosi schematic ESDLIB, _) Cell               2       0*
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
(RPOLY1) RES                                      0       1*
(ND_SP) DIO                                       0       1*
(PD_SN) DIO                                       0       1*
(DP_DN) DIO                                       0       2*
(DN_PS) DIO                                       0       2*
                                             ------  ------
Total                                            13      44

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       5      13*          5       5
(PMOSI) MOS                                       5      21*          5       5
(RDIFFPS) RES                                     2       2           2       2
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       2*          1       1
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                            17      43          17      17

*******************************************************************************
****** ICP_HV cmos_sch IOLIB_HV_4M  <vs>  ICP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(ND_SP) DIO                                       1       1
(PD_SN) DIO                                       1       1
(PMOSI) MOS                                       2      21*
(NMOSI) MOS                                       2      12*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       1       2*
(RDIFFPS) RES                                     2       2
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(esdpmosi schematic ESDLIB, _) Cell               1       0*
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                            13      43

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3      12*          3       3
(PMOSI) MOS                                       3      21*          3       3
(RDIFFPS) RES                                     2       2           2       2
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       2*          1       1
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                            13      42          13      13

*******************************************************************************
****** VSUBALLP_HV cmos_sch IOLIB_HV_4M  <vs>  VSUBALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOSI) MOS                                       1      10*
(DP_DN) DIO                                       1       1
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                             4      14

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             4      13           4       4

*******************************************************************************
****** VDD3ALLP_HV cmos_sch IOLIB_HV_4M  <vs>  VDD3ALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DP_DN) DIO                                       1       1
(NMOSI) MOS                                       1      10*
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(SHORT) RES                                       2      28*
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                             6      42

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       2      28*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             6      41           6       6

*******************************************************************************
****** GND3ALLP_HV cmos_sch IOLIB_HV_4M  <vs>  GND3ALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(SHORT) RES                                       3      22*
(DN_PS) DIO                                       1       1
(DP_DN) DIO                                       1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             7      36

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       3      22*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             7      35           6       6

*******************************************************************************
****** ioring schematic MINIMAL_IO_HV  <vs>  ioring layout MINIMAL_IO_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PWRCUT_DIG_P_DXS_HV cmos_sch IOLIB_HV_4M, PWRCUT_DIG_P_DXS_HV) Cell          2       2
(APRIOP_HV schematic IOLIB_ANA_HV_4M, APRIOP_HV) Cell               2       2
(APRIO200P_HV schematic IOLIB_ANA_HV_4M, APRIO200P_HV) Cell         1       1
(AVDD3ALLP_HV schematic IOLIB_ANA_HV_4M, AVDD3ALLP_HV) Cell         1       1
(AGND3ALLP_HV schematic IOLIB_ANA_HV_4M, AGND3ALLP_HV) Cell         1       1
(BU2P_HV cmos_sch IOLIB_HV_4M, BU2P_HV) Cell              3       3
(ICP_HV cmos_sch IOLIB_HV_4M, ICP_HV) Cell        3       3
(VSUBALLP_HV cmos_sch IOLIB_HV_4M, VSUBALLP_HV) Cell                1       1
(VDD3ALLP_HV cmos_sch IOLIB_HV_4M, VDD3ALLP_HV) Cell                1       1
(GND3ALLP_HV cmos_sch IOLIB_HV_4M, GND3ALLP_HV) Cell                1       1
(_, CORNERP_HV layout IOLIB_HV_4M) Cell           0       4*
(_, PERI_SPACER_100_P_HV layout IOLIB_HV_4M) Cell         0      13*
(_, PERI_SPACER_10_P_HV layout IOLIB_HV_4M) Cell          0       1*
(_, PERI_SPACER_20_P_HV layout IOLIB_HV_4M) Cell          0       1*
(_, PERI_SPACER_2_P_HV layout IOLIB_HV_4M) Cell           0       8*
(_, PERI_SPACER_50_P_HV layout IOLIB_HV_4M) Cell          0      13*
                                             ------  ------
Total                                            16      56

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(AGND3ALLP_HV) Cell                               1       1           1       1
(APRIO200P_HV) Cell                               1       1           1       1
(APRIOP_HV) Cell                                  2       2           2       2
(AVDD3ALLP_HV) Cell                               1       1           1       1
(BU2P_HV) Cell                                    3       3           3       3
(GND3ALLP_HV) Cell                                1       1           1       1
(ICP_HV) Cell                                     3       3           3       3
(PWRCUT_DIG_P_DXS_HV) Cell                        2       2           2       2
(VDD3ALLP_HV) Cell                                1       1           1       1
(VSUBALLP_HV) Cell                                1       1           1       1
                                             ------  ------      ------  ------
Total                                            16      16          16      16

Schematic and Layout Match
