###############################################################
#  Generated by:      Cadence Innovus 23.15-s106_1
#  OS:                Linux x86_64(Host ID edatools)
#  Generated on:      Wed Sep  2 10:12:04 2026
#  Design:            counter
#  Command:           saveDesign -cellview {COUNTER counter layout}
###############################################################
current_design counter
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name CLK -period 20.000000 -waveform {0.000000 10.000000}
set_propagated_clock  [get_ports {clk}]
#END OF CLOCK SECTION#
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -min -pin Q [get_ports {reset}]
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -min -pin Q [get_ports {reset}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -max -pin Q [get_ports {reset}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -max -pin Q [get_ports {reset}]
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -min -pin Q [get_ports {clk}]
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -min -pin Q [get_ports {clk}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -max -pin Q [get_ports {clk}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -max -pin Q [get_ports {clk}]
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -min -pin Q [get_ports {enable}]
set_driving_cell -lib_cell BUFX2_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -min -pin Q [get_ports {enable}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -rise -max -pin Q [get_ports {enable}]
set_driving_cell -lib_cell BUFX24_DCV_HV -library h35_CORELIBD_DCV_HV_ss_2V97_150C -fall -max -pin Q [get_ports {enable}]
set_load -pin_load -max  1  [get_ports {out[7]}]
set_load -pin_load -min  0.01  [get_ports {out[7]}]
set_load -pin_load -max  1  [get_ports {out[6]}]
set_load -pin_load -min  0.01  [get_ports {out[6]}]
set_load -pin_load -max  1  [get_ports {out[5]}]
set_load -pin_load -min  0.01  [get_ports {out[5]}]
set_load -pin_load -max  1  [get_ports {out[4]}]
set_load -pin_load -min  0.01  [get_ports {out[4]}]
set_load -pin_load -max  1  [get_ports {out[3]}]
set_load -pin_load -min  0.01  [get_ports {out[3]}]
set_load -pin_load -max  1  [get_ports {out[2]}]
set_load -pin_load -min  0.01  [get_ports {out[2]}]
set_load -pin_load -max  1  [get_ports {out[1]}]
set_load -pin_load -min  0.01  [get_ports {out[1]}]
set_load -pin_load -max  1  [get_ports {out[0]}]
set_load -pin_load -min  0.01  [get_ports {out[0]}]
set_wire_load_mode enclosed
set_input_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {enable}]
set_input_delay -add_delay 10 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {enable}]
set_input_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {reset}]
set_input_delay -add_delay 10 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {reset}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[6]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[6]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[4]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[4]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[2]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[2]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[0]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[0]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[7]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[7]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[5]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[5]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[3]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[3]}]
set_output_delay -add_delay 0.1 -min -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[1]}]
set_output_delay -add_delay 2 -max -network_latency_included -clock [get_clocks {CLK}] [get_ports {out[1]}]
set_clock_uncertainty 0.4 -hold [get_clocks {CLK}]
set_clock_uncertainty 2 -setup [get_clocks {CLK}]
