0 0 dataAuditErrors
513 0 DEVICE Error: Illegal nmosh device
604 0 Not Qualified CPMIM device
616 0 DEVICE Error illegal element : CVAR_device RF not supported for this technology
937 0 INFO: unidentified diffusion = diff without implant, outside hv devices
1020 0 Process Modules : PHDPINB750 not available for this process module
1448 0 Illegal Device : nmos50ts not supported
1449 0 Illegal Device : nmos50ms not supported
1486 0 Illegal Device : nmos20ts not supported
1487 0 Illegal Device : nmos20ms not supported
1757 0 PMOSD20M INFO only : large device w > 200  gate split up
1758 0 PMOSD20T INFO only : large device w > 200  gate split up
1763 0 PMOSD20M INFO only : this device is identical with pmos20m with m-factor 1 , but with text pmosd20m on HVDEF layer
1768 0 PMOSD20T INFO only : this device is identical with pmos20t with m-factor 1 , but with text pmosd20t on HVDEF layer
1789 0 Illegal Device : pmos20ts not supported
1790 0 Illegal Device : pmos20ms not supported
1890 0 Illegal Device : pmos50ts not supported
1891 0 Illegal Device : pmos50ms not supported
1919 0 Illegal Device : pmos120t not supported
2007 0 Unsupported Device PMOSVS with HVOX
2009 0 Unsupported Device PMOSVS with MIDOX
2099 0 Unsupported Device PMOSDVS with HVOX
2101 0 Unsupported Device PMOSDVS with MIDOX
2316 0 NMOSDI20H INFO only : large device w > 200  gate split up
2317 0 NMOSDI20M INFO only : large device w > 200  gate split up
2488 0 Unsupported Device NMOSDIVS with MIDOX
2513 0 Unsupported Device NMOSDIVS with HVOX
2623 0 Unsupported Device NMOSIVS with MIDOX
2648 0 Unsupported Device NMOSIVS with HVOX
2691 0 Illegal Device: NMOSFI25T not supported
2692 0 Illegal Device: NMOSFI25M not supported
2723 0 Illegal Device: NMOSFI25MS not supported
2725 0 Illegal Device: NMOSFI25TS not supported
3572 0 Error: MET1 resistors (shorts) must be rectangular
3574 0 Error: Number of MET1 resistor terminals != 2
3576 0 Error: MET1 resistor def layer METRES touches CONT OR VIA1
3592 0 Error: MET2 resistors (shorts) must be rectangular
3594 0 Error: Number of MET2 resistor terminals != 2
3596 0 Error: MET2 resistor def layer METRES touches VIA1 or VIA2
3612 0 Error: MET3 resistors (shorts) must be rectangular
3614 0 Error: Number of MET3 resistor terminals != 2
3616 0 Error: MET3 resistor def layer METRES touches VIA2 or VIA3
3630 0 Error: MET4 resistors (shorts) must be rectangular
3632 0 Error: Number of MET4 resistor terminals != 2
3633 0 Error: MET4 resistor def layer METRES touches VIA3
3643 0 RVIA1 Definition layer: does not open all via connection, is shorted
3646 0 RVIA1 Definition layer: truncates via1, device shorted
3647 0 RVIA1 Definition layer: does not define a device
3651 0 RVIA1 Definition layer: over METRES
3658 0 RVIA2 Definition layer: does not open all via connection, is shorted
3661 0 RVIA2 Definition layer: truncates via2, device shorted
3662 0 RVIA2 Definition layer : does not define a device
3666 0 RVIA2 Definition layer: over METRES
3674 0 RVIA3 Definition layer: does not open all via connection, is shorted
3677 0 RVIA3 Definition layer: truncates via3, device shorted
3678 0 RVIA3 Definition layer : does not define a device
3682 0 RVIA3 Definition layer: over METRES
3827 0 ERROR : POLY1 pin outside poly1
3828 0 ERROR : MET1 pin outside met1
3829 0 ERROR : MET2 pin outside met2
3832 0 ERROR : MET3 pin outside met3
3834 0 ERROR : MET4 pin outside met4
3835 0 ERROR : PAD pin outside pad metal
3875 0 HVDEF_isoVoltage layer does not have any isoVoltage text
3878 0 HVDEF_isoType layer does not have any isoType text
3879 0 INFO : isotype_definition_type1
3880 0 INFO : isotype_definition_type2
3881 0 INFO : isovolt_definition_volt5
3882 0 INFO : isovolt_definition_volt20
3883 0 INFO : isovolt_definition_volt50
3884 0 INFO : isovolt_definition_volt120
3887 0  IsoVolt 50/120 overlaps definition layer for ISOVOLT
3888 0  IsoVolt 20/120 overlaps definition layer for ISOVOLT
3889 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
3890 0  IsoVolt 5/120 overlaps definition layer for ISOVOLT
3891 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
3892 0  IsoVolt 50/5 overlaps definition layer for ISOVOLT
3893 0  IsoType 1/2  overlaps definition layer for ISOTYPE
3929 0 CPMIM Error: cpmim must be totally inside POLY2
3930 0 CPMIM Error: cpoly must enclose cmim
3932 0 CPMIM Error: met3/poly1 plates of CPMIM not connected correctly
3934 0 CPMIM Error: met2/poly2 plates of CPMIM not connected correctly
3936 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
3938 0 CPMIM Error: poly1/poly2 plates of CPMIM shorted, is this ok ?
3943 0 HVR001 : No HVDEF on CWPM
3944 0 HVR001 : Version of CWPM obsolete or missing
3945 0 HVR001 : HVDEF has illegal name on CWPM
3949 0 HVR001 : No HVDEF on VERTN1
3950 0 HVR001 : Version of VERTN1 obsolete or missing
3951 0 HVR001 : HVDEF has illegal name on VERTN1
3955 0 HVR001 : No HVDEF on VERTPH
3956 0 HVR001 : Version of VERTPH obsolete or missing
3957 0 HVR001 : HVDEF has illegal name on VERTPH
3961 0 HVR001 : No HVDEF on RPWELLR
3962 0 HVR001 : Version of RPWELLR obsolete or missing
3963 0 HVR001 : HVDEF has illegal name on RPWELLR
3967 0 HVR001 : No HVDEF on RNWELLS
3968 0 HVR001 : Version of RNWELLS obsolete or missing
3969 0 HVR001 : HVDEF has illegal name on RNWELLS
3973 0 HVR001 : No HVDEF on PJFET
3974 0 HVR001 : Version of PJFET obsolete or missing
3975 0 HVR001 : HVDEF has illegal name on PJFET
3985 0 HVR001 : No HVDEF on NMOS50T
3986 0 HVR001 : No HVDEF on NMOS50M
3987 0 HVR001 : No HVDEF on NMOS50H
3988 0 HVR001 : Version of NMOS50T obsolete or missing
3989 0 HVR001 : Version of NMOS50M obsolete or missing
3990 0 HVR001 : Version of NMOS50H obsolete or missing
3991 0 HVR001 : HVDEF has illegal name on NMOS50T
3992 0 HVR001 : HVDEF has illegal name on NMOS50M
3993 0 HVR001 : HVDEF has illegal name on NMOS50H
4003 0 HVR001 : No HVDEF on NMOS20T
4004 0 HVR001 : No HVDEF on NMOS20M
4005 0 HVR001 : No HVDEF on NMOS20H
4006 0 HVR001 : Version of NMOS20T obsolete or missing
4007 0 HVR001 : Version of NMOS20M obsolete or missing
4008 0 HVR001 : Version of NMOS20H obsolete or missing
4009 0 HVR001 : HVDEF has illegal name on NMOS20T
4010 0 HVR001 : HVDEF has illegal name on NMOS20M
4011 0 HVR001 : HVDEF has illegal name on NMOS20H
4039 0 NMOSD20M_R1: NMOSD20M source/bulk met1 must be connected together
4042 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4043 0 NMOSD20M_R2 : source ndiff cannot be abutted with BULK PDIFF ring, except ptaps in ndiff holes
4047 0 HVR001 : Version of NMOSD20M obsolete or missing
4048 0 HVR001 : HVDEF has illegal name on NMOSD20M
4052 0 HVR001 : No HVDEF on NMOS50HS
4053 0 HVR001 : Version of NMOS50HS obsolete or missing
4054 0 HVR001 : HVDEF has illegal name on NMOS50HS
4058 0 HVR001 : No HVDEF on NMOS20HS
4059 0 HVR001 : Version of NMOS20HS obsolete or missing
4060 0 HVR001 : HVDEF has illegal name on NMOS20HS
4070 0 HVR001 : No HVDEF on NMOSI50T
4071 0 HVR001 : No HVDEF on NMOSI50M
4072 0 HVR001 : No HVDEF on NMOSI50H
4073 0 HVR001 : Version of NMOSI50T obsolete or missing
4074 0 HVR001 : Version of NMOSI50M obsolete or missing
4075 0 HVR001 : Version of NMOSI50H obsolete or missing
4076 0 HVR001 : HVDEF has illegal name on NMOSI50T
4077 0 HVR001 : HVDEF has illegal name on NMOSI50M
4078 0 HVR001 : HVDEF has illegal name on NMOSI50H
4082 0 HVR001 : No HVDEF on NMOSDI50H
4083 0 HVR001 : Version of NMOSDI50H obsolete or missing
4084 0 HVR001 : HVDEF has illegal name on NMOSDI50H
4091 0 HVR001 : No HVDEF on NMOSDI20M
4092 0 HVR001 : No HVDEF on NMOSDI20H
4093 0 HVR001 : Version of NMOSDI20M obsolete or missing
4094 0 HVR001 : Version of NMOSDI20H obsolete or missing
4095 0 HVR001 : HVDEF has illegal name on NMOSDI20M
4096 0 HVR001 : HVDEF has illegal name on NMOSDI20H
4106 0 HVR001 : No HVDEF on NMOSI20T
4107 0 HVR001 : No HVDEF on NMOSI20M
4108 0 HVR001 : No HVDEF on NMOSI20H
4109 0 HVR001 : Version of NMOSI20T obsolete or missing
4110 0 HVR001 : Version of NMOSI20M obsolete or missing
4111 0 HVR001 : Version of NMOSI20H obsolete or missing
4112 0 HVR001 : HVDEF has illegal name on NMOSI20T
4113 0 HVR001 : HVDEF has illegal name on NMOSI20M
4114 0 HVR001 : HVDEF has illegal name on NMOSI20H
4121 0 HVR001 : Version of NMOSD10MH obsolete or missing
4122 0 HVR001 : Version of NMOS10MH obsolete or missing
4129 0 HVR001 : No HVDEF on NMOSI120M
4130 0 HVR001 : No HVDEF on NMOSI120H
4131 0 HVR001 : Version of NMOSI120M obsolete or missing
4132 0 HVR001 : Version of NMOSI120H obsolete or missing
4133 0 HVR001 : HVDEF has illegal name on NMOSI120M
4134 0 HVR001 : HVDEF has illegal name on NMOSI120H
4138 0 HVR001 : Version of ESDPMOS18T obsolete or missing
4146 0 INFO: PMOS20H ESD DEVICE REV3 for peri cells only
4150 0 HVR001 : No HVDEF on PMOS20H
4151 0 HVR001 : No HVDEF on PMOS20M
4152 0 HVR001 : No HVDEF on PMOS20H
4153 0 HVR001 : Version of PMOS20T obsolete or missing
4154 0 HVR001 : Version of PMOS20M obsolete or missing
4155 0 HVR001 : Version of PMOS20H obsolete or missing
4156 0 HVR001 : HVDEF has illegal name on PMOS20H
4160 0 HVR001 : HVDEF has illegal name on PMOS20M/PMOSD20M
4162 0 HVR001 : No HVDEF on PMOSD20M
4163 0 HVR001 : Version of PMOSD20M obsolete or missing
4164 0 HVR001 : HVDEF has illegal name on PMOSD20M
4168 0 HVR001 : HVDEF has illegal name on PMOS20T/PMOSD20T
4170 0 HVR001 : No HVDEF on PMOSD20T
4171 0 HVR001 : Version of PMOSD20T obsolete or missing
4172 0 HVR001 : HVDEF has illegal name on PMOSD20T
4203 0 PMOSD20M_R1/PMOSD20T_R1 : PMOSD20 source/bulk met1 must be connected together
4206 0 PMOSD20_R2: source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4207 0 PMOSD20M_R2/PMOSD20T_R2 : source pdiff cannot be abutted with BULK NDIFF ring, except ntaps in pdiff holes
4211 0 HVR001 : No HVDEF on PMOS20HS
4212 0 HVR001 : Version of PMOS20HS obsolete or missing
4213 0 HVR001 : HVDEF has illegal name on PMOS20HS
4220 0 HVR001 : Version of PMOSD10MH obsolete or missing
4221 0 HVR001 : Version of PMOS10MH obsolete or missing
4231 0 HVR001 : No HVDEF on PMOS50T
4232 0 HVR001 : No HVDEF on PMOS50M
4233 0 HVR001 : No HVDEF on PMOS50H
4234 0 HVR001 : Version of PMOS50T obsolete or missing
4235 0 HVR001 : Version of PMOS50M obsolete or missing
4236 0 HVR001 : Version of PMOS50H obsolete or missing
4237 0 HVR001 : HVDEF has illegal name on PMOS50T
4238 0 HVR001 : HVDEF has illegal name on PMOS50M
4239 0 HVR001 : HVDEF has illegal name on PMOS50H
4243 0 HVR001 : No HVDEF on PMOS50HS
4244 0 HVR001 : Version of PMOS50HS obsolete or missing
4245 0 HVR001 : HVDEF has illegal name on PMOS50HS
4252 0 HVR001 : No HVDEF on PMOS120M
4253 0 HVR001 : No HVDEF on PMOS120H
4254 0 HVR001 : Version of PMOS120M obsolete or missing
4255 0 HVR001 : Version of PMOS120H obsolete or missing
4256 0 HVR001 : HVDEF has illegal name on PMOS120M
4257 0 HVR001 : HVDEF has illegal name on PMOS120H
4267 0 HVR001 : No HVDEF on NMOSFI25T
4268 0 HVR001 : No HVDEF on NMOSFI25M
4269 0 HVR001 : No HVDEF on NMOSFI25H
4270 0 HVR001 : Version of NMOSFI25T obsolete or missing
4271 0 HVR001 : Version of NMOSFI25M obsolete or missing
4272 0 HVR001 : Version of NMOSFI25H obsolete or missing
4273 0 HVR001 : HVDEF has illegal name on NMOSFI25T
4274 0 HVR001 : HVDEF has illegal name on NMOSFI25M
4275 0 HVR001 : HVDEF has illegal name on NMOSFI25H
4285 0 HVR001 : No HVDEF on NMOSFI25TS
4286 0 HVR001 : No HVDEF on NMOSFI25MS
4287 0 HVR001 : No HVDEF on NMOSFI25HS
4288 0 HVR001 : Version of NMOSFI25TS obsolete or missing
4289 0 HVR001 : Version of NMOSFI25MS obsolete or missing
4290 0 HVR001 : Version of NMOSFI25HS obsolete or missing
4291 0 HVR001 : HVDEF has illegal name on NMOSFI25TS
4292 0 HVR001 : HVDEF has illegal name on NMOSFI25MS
4293 0 HVR001 : HVDEF has illegal name on NMOSFI25HS
4297 0 HVR001 : Version of ESDGCI3 obsolete or missing
4298 0 HVR001 : HVDEF has illegal name on ESDGCI3
4305 0 ESDGCI3 connectivity error : emitter diff and emitter gate (poly ring) must be connected , common terminal E
4306 0 ESDGCI3 connectivity error : emitter diff and emitter dntub must be connected, common terminal E
4309 0 ESDGCI3 connectivity error :  emitter gate ( poly ring) and emitter dntub must be connected,  common terminal E
4313 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter met1 to met2, missing met2 connection or recommended via density too small < 25%
4324 0 ESDGCI3 connectivity problem : EMITTER :use as many via1 as possble to connect emitter ring met1 to met2, missing met2 connection or recommended via density too small  < 10% 
4330 0 ESDGCI3 connectivity problem : COLLECTOR : use as many via1 as possble to connect collector met1 to met2, missing met2 connection or recommended via density too small < 25 %
4334 0 HVR001 : Version of ESDNPN_PN3 obsolete or missing
4335 0 HVR001 : HVDEF has illegal name on ESDNPN_PN3
4346 0 ESDNPN_PN3_Y2 width MET1, not over COLLECTOR 0.7 u
4348 0 ESDNPN_PN3_E3 MET1 enclosure of CONT 0.25 u
4351 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (>)
4353 0 ESDNPN_PN3_Z1 Collector-ndiff to EMITTER-NDIFF spacing (diagonal) 0.636 u (<)
4354 0 ESDNPN_PN3_Y1 NDIFF right angle corner 0.4 u
4357 0 ESDNPN_PN3_X8_X10 COLLECTOR-NDIFF/EMITTER-NDIFF width 1.2 u
4362 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4364 0 ESDNPN_PN3_E1_E2 EMITTER-NDIFF enclosure of CONT corner 0.2*sqrt(2) u 
4366 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (<)
4368 0 ESDNPN_PN3_X7_X9 EMITTER-NDIFF/COLLECTOR-NDIFF  spacing 1.3u (>)
4381 0 ESDNPN_PN3_X6 COLLECTOR_NDIFF to EMITTER_NDIFF spacing ( projected edges) 0.05 u
4391 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (>)
4392 0 ESDNPN_PN3_x4 RPTUB enclosure of EMITTER_NDIFF 1.25u (<)
4394 0 ESDNPN_PN3_X2 NDIFF width 1.95u (<)
4395 0 ESDNPN_PN3_X2 NDIFF width 1.95u (>)
4401 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (enc)
4403 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (straddle)
4405 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u (outside)
4406 0 ESDNPN_PN3_X1_X3 SNTUB enclosure of NDIFF (inside/outside) 0.3 u
4417 0 ESDNPN_PN3_X11 MET1 width 3. u
4421 0 HVR001 : Version of ESDGCNI5 obsolete or missing
4422 0 HVR001 : HVDEF has illegal name on ESDGCNI5
4426 0 HVR001 : Version of ESDGCI20 obsolete or missing
4427 0 HVR001 : HVDEF has illegal name on ESDGCI20
4431 0 HVR001 : Version of ESDFDI50 obsolete or missing
4432 0 HVR001 : HVDEF has illegal name on ESDFDI50
4436 0 HVR001 : Version of ESDTD20 obsolete or missing
4437 0 HVR001 : HVDEF has illegal name on ESDTD20
4441 0 HVR001 : Version of ESDTD50 obsolete or missing
4442 0 HVR001 : HVDEF has illegal name on ESDTD50
4446 0 HVR001 : Version of ESDTD40 obsolete or missing
4447 0 HVR001 : HVDEF has illegal name on ESDTD40
4451 0 HVR001 : Version of ESDTD42 obsolete or missing
4452 0 HVR001 : HVDEF has illegal name on ESDTD42
4456 0 HVR001 : Version of ESDTD45 obsolete or missing
4457 0 HVR001 : HVDEF has illegal name on ESDTD45
4461 0 HVR001 : Version of ESDTD60 obsolete or missing
4462 0 HVR001 : HVDEF has illegal name on ESDTD60
4466 0 HVR001 : Version of ESDPD10 obsolete or missing
4467 0 HVR001 : HVDEF has illegal name on ESDPD10
4471 0 HVR001 : Version of ESDPD26 obsolete or missing
4472 0 HVR001 : HVDEF has illegal name on ESDPD26
4476 0 DEVICE : ESDFDI120 not implemented yet
4480 0 UNSUPPORTED DEVICE : ESDPD12
4484 0 HVR001 : Version of ESDPD18 obsolete or missing
4485 0 HVR001 : HVDEF has illegal name on ESDPD18
4489 0 HVR001 : Version of ESDPD30 obsolete or missing
4490 0 HVR001 : HVDEF has illegal name on ESDPD30
4494 0 HVR001 : Version of ESDGCPI5 obsolete or missing
4495 0 HVR001 : HVDEF has illegal name on ESDGCPI5
4499 0 HVR001 : Version of ESDFDNI5 obsolete or missing
4500 0 HVR001 : HVDEF has illegal name on ESDFDNI5
4504 0 HVR001 : Version of ESDFDPI5 obsolete or missing
4505 0 HVR001 : HVDEF has illegal name on ESDFDPI5
4509 0 HVR001 : Version of ESDGCN5 obsolete or missing
4510 0 HVR001 : HVDEF has illegal name on ESDGCN5
4514 0 HVR001 : Version of ESDGCP5 obsolete or missing
4515 0 HVR001 : HVDEF has illegal name on ESDGCP5
4519 0 HVR001 : Version of ESDFDP5 obsolete or missing
4520 0 HVR001 : HVDEF has illegal name on ESDFDP5
4524 0 HVR001 : Version of ESDFDN5 obsolete or missing
4525 0 HVR001 : HVDEF has illegal name on ESDFDN5
4529 0 HVR001 : Version of ESDPNP40 obsolete or missing
4530 0 HVR001 : HVDEF has illegal name on ESDPNP40
4534 0 HVR001 : Version of ESDPNP42 obsolete or missing
4535 0 HVR001 : HVDEF has illegal name on ESDPNP42
4556 0 HVR001 : Version of ESDSCR14_SN obsolete or missing
4557 0 HVR001 : HVDEF has illegal name on ESDSCR14_SN
4579 0 HVR001 : Version of ESDSCR55_SN obsolete or missing
4580 0 HVR001 : HVDEF has illegal name on ESDSCR55_SN
4593 0 Illegal Device : This ESD device is not supported ( no ESD_01/02/03/04/05/06)
4843 0 HVR001 : HVDEF does not enclose a valid HV-device, bad HVDEF or bad device
4850 0 HVR003_NMOS50_sources_must_be_connected_together
4860 0 HVR003_NMOS20_sources_must_be_connected_together
4869 0 HVR003_NMOS10MH_sources_must_be_connected_together
4878 0 HVR003_NMOSI50_sources_must_be_connected_together
4887 0 HVR003_NMOSDI50_sources_must_be_connected_together
4899 0 HVR003_NMOSFI25_sources_must_be_connected_together
4909 0 HVR003_NMOSI20_sources_must_be_connected_together
4919 0 HVR003_NMOSDI20_sources_must_be_connected_together
4928 0 HVR003_NMOSI120_sources_must_be_connected_together
4937 0 HVR003_PMOS50_sources_must_be_connected_together
4946 0 HVR003_PMOS20_sources_must_be_connected_together
4956 0 HVR003_ESDPMOS18T_sources_must_be_connected_together
4965 0 HVR003_PMOS120_sources_must_be_connected_together
4974 0 HVR003_PMOS10MH_sources_must_be_connected_together
4991 0 NMOSI20T_R1/NMOSI20M_R1/NMOSI20H_R1: Bulk and source must be connected with met1
5005 0 NMOSI50T_R1/NMOSI50M_R1/NMOSI50H_R1: Bulk and source must be connected with met1
5019 0 NMOSI120M_R1/NMOSI120H_R1: Bulk and source must be connected with met1
5032 0 NMOSDI20M_R1/NMOSDI20H_R1: Bulk and source must be connected with met1
5042 0 NMOSDI50H_R1: Bulk and source must be connected with met1
5065 0 NMOSD10MH_R1: Bulk and source must be connected with met1
5087 0 PMOSD10MH_R1: Bulk and source must be connected with met1
5211 0 HVDEF_IsoVoltage : nmosi device must be inside iso volt definition layer
5215 0 HVDEF_IsoType : nmosi device must be inside iso type definition layer
5239 0 HVDEF_IsoVoltage : nmosi device must be inside iso volt definition layer
5243 0 HVDEF_IsoType : nmosi device must be inside iso type definition layer
5267 0 HVDEF_IsoVoltage : pmosi device must be inside iso volt definition layer
5271 0 HVDEF_IsoType : pmosi device must be inside iso type definition layer
5295 0 HVDEF_IsoVoltage : pmosi device must be inside iso volt definition layer
5299 0 HVDEF_IsoType : pmosi device must be inside iso type definition layer
6195 0 HVDEF_IsoVoltage : rdiffps device must be inside iso volt definition layer
6199 0 HVDEF_IsoType : rdiffps device must be inside iso type definition layer
7097 0 PDI1N01S002_cath_StampErrorFloat
7098 0 PDI1N01S002_cath_StampErrorMult
7099 0 PDI1N01S002_cath_StampErrorConnect
7131 0 PDI1N13S002_cath_StampErrorFloat
7132 0 PDI1N13S002_cath_StampErrorMult
7133 0 PDI1N13S002_cath_StampErrorConnect
7248 0 HVDEF_IsoVoltage : dn_ps device must be inside iso volt definition layer
7252 0 HVDEF_IsoType : dn_ps device must be inside iso type definition layer
7839 0 esdscr14_sn_vio_StampErrorFloat
7840 0 esdscr14_sn_vio_StampErrorMult
7841 0 esdscr14_sn_vio_StampErrorConnect
7860 0 esdscr55_sn_vio_StampErrorFloat
7861 0 esdscr55_sn_vio_StampErrorMult
7862 0 esdscr55_sn_vio_StampErrorConnect
9316 0 # INFO: Set -resimulate_extracted- Switch for QRC! #
9317 0 # H35B4 ENG - 243 (Last updated 28-Mar-2025 00:09) #
9873 0 malformed device NMOSI_device_hv
9874 0 malformed device NMOSI_device_not_hv
9875 0 malformed device NMOSIM_device_hv
9876 0 malformed device NMOSIM_device_not_hv
9877 0 malformed device poa_nmos_waffle_2x
9878 0 malformed device poa_nmos_waffle_3x
9879 0 malformed device poa_nmos_waffle_4x
9880 0 malformed device poa_nmos_midox_waffle_2x
9881 0 malformed device poa_nmos_midox_waffle_3x
9882 0 malformed device poa_nmos_midox_waffle_4x
9883 0 malformed device NMOSH_device
9884 0 malformed device NMOSMH_device
9885 0 malformed device RPWELLR_device
9886 0 malformed device RNWELL_device
9887 0 malformed device RNWELLS_device
9888 0 malformed device RDIFFP_device
9889 0 malformed device RDIFFPS_device_hv
9890 0 malformed device RDIFFPS_device_not_hv
9891 0 malformed device RDIFFN_device
9892 0 malformed device RDIFFNR_device
9893 0 malformed device RPOLY2_PSUB_device
9894 0 malformed device RPOLY2_NTUB_device
9895 0 malformed device RPOLY2_PTUB_device
9896 0 malformed device RPOLY2PH_PSUB_device
9897 0 malformed device RPOLY2PH_PTUB_device
9898 0 malformed device RPOLY2PH_NTUB_device
9899 0 malformed device RPOLYH_PSUB_device
9900 0 malformed device RPOLYH_NTUB_device
9901 0 malformed device RPOLYH_PTUB_device
9902 0 malformed device RPOLY1_PSUB_device
9903 0 malformed device RPOLY1_NTUB_device
9904 0 malformed device RPOLY1_PTUB_device
9905 0 malformed device PFUSE_device
9906 0 malformed device LAT2_device
9907 0 malformed device VERT10_device
9908 0 malformed device VERTN1_device
9909 0 malformed device VERTPH_device
9910 0 malformed device PJFET_device
9911 0 malformed device CPOLY_PSUB_device
9912 0 malformed device CPOLY_NTUB_device
9913 0 malformed device CWPM_device
9914 0 malformed device CPM_device
9915 0 malformed device PROBE_device
9916 0 malformed device PDI1N01S002_device
9917 0 malformed device PDI1N13S002_device
9918 0 malformed device DN_PS_device_hv
9919 0 malformed device DN_PS_device_not_hv
9920 0 malformed device ESDGCI3_device
9921 0 malformed device ESDGCNI5_device
9922 0 malformed device ESDGCI20_device
9923 0 malformed device ESDVSD_device
9924 0 malformed device ESDVSS_device
9925 0 malformed device ESDFDI50_device
9926 0 malformed device ESDTD20_device
9927 0 malformed device ESDTD50_device
9928 0 malformed device ESDTD40_device
9929 0 malformed device ESDTD42_device
9930 0 malformed device ESDTD45_device
9931 0 malformed device ESDTD60_device
9932 0 malformed device ESDPD10_device
9933 0 malformed device ESDGCPI5_device
9934 0 malformed device ESDFDPI5_device
9935 0 malformed device ESDFDNI5_device
9936 0 malformed device ESDFDN5_device
9937 0 malformed device ESDGCN5_device
9938 0 malformed device ESDFDP5_device
9939 0 malformed device ESDGCP5_device
9940 0 malformed device ESDPNP40_device
9941 0 malformed device ESDPNP42_device
9942 0 malformed device ESDNPN_PN3_device
9943 0 malformed device ESDSCR14_SN_device
9944 0 malformed device ESDSCR55_SN_device
9945 0 malformed device NMOS50T_device
9946 0 malformed device NMOS50M_device
9947 0 malformed device NMOS50H_device
9948 0 malformed device NMOS50HS_device
9949 0 malformed device NMOSI50T_device
9950 0 malformed device NMOSI50M_device
9951 0 malformed device NMOSI50H_device
9952 0 malformed device NMOSI20H_device
9953 0 malformed device NMOSI20T_device
9954 0 malformed device NMOSI20M_device
9955 0 malformed device NMOS10MH_device
9956 0 malformed device NMOSD10MH_device
9957 0 malformed device NMOS20T_device
9958 0 malformed device NMOS20M_device
9959 0 malformed device NMOSD20M_device
9960 0 malformed device NMOS20H_device
9961 0 malformed device NMOS20HS_device
9962 0 malformed device NMOSDI20M_device
9963 0 malformed device NMOSDI20T_device
9964 0 malformed device NMOSDI20H_device
9965 0 malformed device NMOSDI50H_device
9966 0 malformed device NMOSDI50T_device
9967 0 malformed device NMOSI120H_device
9968 0 malformed device NMOSI120M_device
9969 0 malformed device NMOSDIVST_device
9970 0 malformed device NMOSIVST_device
9971 0 malformed device PMOS50T_device
9972 0 malformed device PMOS50M_device
9973 0 malformed device PMOS50H_device
9974 0 malformed device PMOS50HS_device
9975 0 malformed device PMOS10MH_device
9976 0 malformed device PMOSD10MH_device
9977 0 malformed device PMOS20H_device_rev4
9978 0 malformed device PMOS20H_device_rev3
9979 0 malformed device PMOS20T_device
9980 0 malformed device ESDPMOS18T_device
9981 0 malformed device PMOSD20T_device
9982 0 malformed device PMOS20M_device
9983 0 malformed device PMOSD20M_device
9984 0 malformed device PMOS20HS_device
9985 0 malformed device PMOS120H_device
9986 0 malformed device PMOS120M_device
9987 0 malformed device PMOSVST_device
9988 0 malformed device PMOSDVST_device
9989 0 malformed device HALL_XY12x12_Zx2_LN_device
9990 0 malformed device HALL_XY12x12_Zx2_STD_device
9991 0 malformed device HALL_XY8x8_Zx2_LN_device
9992 0 malformed device HALL_XY8x8_Zx2_STD_device
9993 0 malformed device HALL_C1_H35_device
9994 0 malformed device HALL_C1_H35X2_device
9995 0 malformed device HALL_C1_H35X4_device
9996 0 malformed device HALL_C2_H35_device
9997 0 malformed device HALL_C2_H35X2_device
9998 0 malformed device HALL_C2_H35X4_device
11551 0 unstable device for HALL_C2_H35X4_device_Device_185
11552 0 unpreserved device HALL_C2_H35X4_device_Device_185
11553 0 unstable device for HALL_C2_H35X2_device_Device_184
11554 0 unpreserved device HALL_C2_H35X2_device_Device_184
11555 0 unstable device for HALL_C2_H35_device_Device_183
11556 0 unpreserved device HALL_C2_H35_device_Device_183
11557 0 unstable device for HALL_C1_H35X4_device_Device_182
11558 0 unpreserved device HALL_C1_H35X4_device_Device_182
11559 0 unstable device for HALL_C1_H35X2_device_Device_181
11560 0 unpreserved device HALL_C1_H35X2_device_Device_181
11561 0 unstable device for HALL_C1_H35_device_Device_180
11562 0 unpreserved device HALL_C1_H35_device_Device_180
11563 0 unstable device for HALL_XY8x8_Zx2_STD_device_Device_179
11564 0 unpreserved device HALL_XY8x8_Zx2_STD_device_Device_179
11565 0 unstable device for HALL_XY8x8_Zx2_LN_device_Device_178
11566 0 unpreserved device HALL_XY8x8_Zx2_LN_device_Device_178
11567 0 unstable device for HALL_XY12x12_Zx2_STD_device_Device_177
11568 0 unpreserved device HALL_XY12x12_Zx2_STD_device_Device_177
11569 0 unstable device for HALL_XY12x12_Zx2_LN_device_Device_176
11570 0 unpreserved device HALL_XY12x12_Zx2_LN_device_Device_176
11571 0 unstable device for PMOSDVST_device_Device_175
11572 0 unpreserved device PMOSDVST_device_Device_175
11573 0 unstable device for PMOSVST_device_Device_174
11574 0 unpreserved device PMOSVST_device_Device_174
11575 0 unstable device for PMOS120M_device_Device_173
11576 0 unpreserved device PMOS120M_device_Device_173
11577 0 unstable device for PMOS120H_device_Device_172
11578 0 unpreserved device PMOS120H_device_Device_172
11579 0 unstable device for PMOS20HS_device_Device_171
11580 0 unpreserved device PMOS20HS_device_Device_171
11581 0 unstable device for PMOSD20M_device_Device_170
11582 0 unpreserved device PMOSD20M_device_Device_170
11583 0 unstable device for PMOS20M_device_Device_169
11584 0 unpreserved device PMOS20M_device_Device_169
11585 0 unstable device for PMOSD20T_device_Device_168
11586 0 unpreserved device PMOSD20T_device_Device_168
11587 0 unstable device for ESDPMOS18T_device_Device_167
11588 0 unpreserved device ESDPMOS18T_device_Device_167
11589 0 unstable device for PMOS20T_device_Device_166
11590 0 unpreserved device PMOS20T_device_Device_166
11591 0 unstable device for PMOS20H_device_rev3_Device_165
11592 0 unpreserved device PMOS20H_device_rev3_Device_165
11593 0 unstable device for PMOS20H_device_rev4_Device_164
11594 0 unpreserved device PMOS20H_device_rev4_Device_164
11595 0 unstable device for PMOSD10MH_device_Device_163
11596 0 unpreserved device PMOSD10MH_device_Device_163
11597 0 unstable device for PMOS10MH_device_Device_162
11598 0 unpreserved device PMOS10MH_device_Device_162
11599 0 unstable device for PMOS50HS_device_Device_161
11600 0 unpreserved device PMOS50HS_device_Device_161
11601 0 unstable device for PMOS50H_device_Device_160
11602 0 unpreserved device PMOS50H_device_Device_160
11603 0 unstable device for PMOS50M_device_Device_159
11604 0 unpreserved device PMOS50M_device_Device_159
11605 0 unstable device for PMOS50T_device_Device_158
11606 0 unpreserved device PMOS50T_device_Device_158
11607 0 unstable device for NMOSIVST_device_Device_157
11608 0 unpreserved device NMOSIVST_device_Device_157
11609 0 unstable device for NMOSDIVST_device_Device_156
11610 0 unpreserved device NMOSDIVST_device_Device_156
11611 0 unstable device for NMOSFI25HS_device_Device_155
11612 0 unpreserved device NMOSFI25HS_device_Device_155
11613 0 unstable device for NMOSFI25H_device_Device_154
11614 0 unpreserved device NMOSFI25H_device_Device_154
11615 0 unstable device for NMOSI120M_device_Device_153
11616 0 unpreserved device NMOSI120M_device_Device_153
11617 0 unstable device for NMOSI120H_device_Device_152
11618 0 unpreserved device NMOSI120H_device_Device_152
11619 0 unstable device for NMOSDI50T_device_Device_151
11620 0 unpreserved device NMOSDI50T_device_Device_151
11621 0 unstable device for NMOSDI50H_device_Device_150
11622 0 unpreserved device NMOSDI50H_device_Device_150
11623 0 unstable device for NMOSDI20H_device_Device_149
11624 0 unpreserved device NMOSDI20H_device_Device_149
11625 0 unstable device for NMOSDI20T_device_Device_148
11626 0 unpreserved device NMOSDI20T_device_Device_148
11627 0 unstable device for NMOSDI20M_device_Device_147
11628 0 unpreserved device NMOSDI20M_device_Device_147
11629 0 unstable device for NMOS20HS_device_Device_146
11630 0 unpreserved device NMOS20HS_device_Device_146
11631 0 unstable device for NMOS20H_device_Device_145
11632 0 unpreserved device NMOS20H_device_Device_145
11633 0 unstable device for NMOSD20M_device_Device_144
11634 0 unpreserved device NMOSD20M_device_Device_144
11635 0 unstable device for NMOS20M_device_Device_143
11636 0 unpreserved device NMOS20M_device_Device_143
11637 0 unstable device for NMOS20T_device_Device_142
11638 0 unpreserved device NMOS20T_device_Device_142
11639 0 unstable device for NMOSD10MH_device_Device_141
11640 0 unpreserved device NMOSD10MH_device_Device_141
11641 0 unstable device for NMOS10MH_device_Device_140
11642 0 unpreserved device NMOS10MH_device_Device_140
11643 0 unstable device for NMOSI20M_device_Device_139
11644 0 unpreserved device NMOSI20M_device_Device_139
11645 0 unstable device for NMOSI20T_device_Device_138
11646 0 unpreserved device NMOSI20T_device_Device_138
11647 0 unstable device for NMOSI20H_device_Device_137
11648 0 unpreserved device NMOSI20H_device_Device_137
11649 0 unstable device for NMOSI50H_device_Device_136
11650 0 unpreserved device NMOSI50H_device_Device_136
11651 0 unstable device for NMOSI50M_device_Device_135
11652 0 unpreserved device NMOSI50M_device_Device_135
11653 0 unstable device for NMOSI50T_device_Device_134
11654 0 unpreserved device NMOSI50T_device_Device_134
11655 0 unstable device for NMOS50HS_device_Device_133
11656 0 unpreserved device NMOS50HS_device_Device_133
11657 0 unstable device for NMOS50H_device_Device_132
11658 0 unpreserved device NMOS50H_device_Device_132
11659 0 unstable device for NMOS50M_device_Device_131
11660 0 unpreserved device NMOS50M_device_Device_131
11661 0 unstable device for NMOS50T_device_Device_130
11662 0 unpreserved device NMOS50T_device_Device_130
11663 0 unstable device for ESDSCR55_SN_device_Device_129
11664 0 unpreserved device ESDSCR55_SN_device_Device_129
11665 0 unstable device for ESDSCR14_SN_device_Device_128
11666 0 unpreserved device ESDSCR14_SN_device_Device_128
11667 0 unstable device for ESDNPN_PN3_device_Device_127
11668 0 unpreserved device ESDNPN_PN3_device_Device_127
11669 0 unstable device for ESDPNP42_device_Device_126
11670 0 unpreserved device ESDPNP42_device_Device_126
11671 0 unstable device for ESDPNP40_device_Device_125
11672 0 unpreserved device ESDPNP40_device_Device_125
11673 0 unstable device for ESDGCP5_device_Device_124
11674 0 unpreserved device ESDGCP5_device_Device_124
11675 0 unstable device for ESDFDP5_device_Device_123
11676 0 unpreserved device ESDFDP5_device_Device_123
11677 0 unstable device for ESDGCN5_device_Device_122
11678 0 unpreserved device ESDGCN5_device_Device_122
11679 0 unstable device for ESDFDN5_device_Device_121
11680 0 unpreserved device ESDFDN5_device_Device_121
11681 0 unstable device for ESDFDNI5_device_Device_120
11682 0 unpreserved device ESDFDNI5_device_Device_120
11683 0 unstable device for ESDFDPI5_device_Device_119
11684 0 unpreserved device ESDFDPI5_device_Device_119
11685 0 unstable device for ESDGCPI5_device_Device_118
11686 0 unpreserved device ESDGCPI5_device_Device_118
11687 0 unstable device for ESDPD30_device_Device_117
11688 0 unpreserved device ESDPD30_device_Device_117
11689 0 unstable device for ESDPD26_device_Device_116
11690 0 unpreserved device ESDPD26_device_Device_116
11691 0 unstable device for ESDPD18_device_Device_115
11692 0 unpreserved device ESDPD18_device_Device_115
11693 0 unstable device for ESDPD10_device_Device_114
11694 0 unpreserved device ESDPD10_device_Device_114
11695 0 unstable device for ESDTD60_device_Device_113
11696 0 unpreserved device ESDTD60_device_Device_113
11697 0 unstable device for ESDTD45_device_Device_112
11698 0 unpreserved device ESDTD45_device_Device_112
11699 0 unstable device for ESDTD42_device_Device_111
11700 0 unpreserved device ESDTD42_device_Device_111
11701 0 unstable device for ESDTD40_device_Device_110
11702 0 unpreserved device ESDTD40_device_Device_110
11703 0 unstable device for ESDTD50_device_Device_109
11704 0 unpreserved device ESDTD50_device_Device_109
11705 0 unstable device for ESDTD20_device_Device_108
11706 0 unpreserved device ESDTD20_device_Device_108
11707 0 unstable device for ESDFDI50_device_Device_107
11708 0 unpreserved device ESDFDI50_device_Device_107
11709 0 unstable device for ESDVSS_device_Device_106
11710 0 unpreserved device ESDVSS_device_Device_106
11711 0 unstable device for ESDVSD_device_Device_105
11712 0 unpreserved device ESDVSD_device_Device_105
11713 0 unstable device for ESDGCI20_device_Device_104
11714 0 unpreserved device ESDGCI20_device_Device_104
11715 0 unstable device for ESDGCNI5_device_Device_103
11716 0 unpreserved device ESDGCNI5_device_Device_103
11717 0 unstable device for ESDGCI3_device_Device_102
11718 0 unpreserved device ESDGCI3_device_Device_102
11719 0 unstable device for P_SN_PS_device_Device_101
11720 0 unpreserved device P_SN_PS_device_Device_101
11721 0 unstable device for SN_PS_device_Device_100
11722 0 unpreserved device SN_PS_device_Device_100
11723 0 unstable device for P_DN_PS_device_Device_99
11724 0 unpreserved device P_DN_PS_device_Device_99
11725 0 unstable device for DN_PS_device_not_hv_DIODE_98
11726 0 unpreserved device DN_PS_device_not_hv_DIODE_98
11727 0 unstable device for DN_PS_device_hv_DIODE_97
11728 0 unpreserved device DN_PS_device_hv_DIODE_97
11729 0 unstable device for P_DP_DN_device_Device_96
11730 0 unpreserved device P_DP_DN_device_Device_96
11731 0 unstable device for DP_DN_device_DIODE_95
11732 0 unpreserved device DP_DN_device_DIODE_95
11733 0 unstable device for P_PD_SN_device_Device_94
11734 0 unpreserved device P_PD_SN_device_Device_94
11735 0 unstable device for PD_SN_device_DIODE_93
11736 0 unpreserved device PD_SN_device_DIODE_93
11737 0 unstable device for P_ND_SP_device_Device_92
11738 0 unpreserved device P_ND_SP_device_Device_92
11739 0 unstable device for ND_SP_device_DIODE_91
11740 0 unpreserved device ND_SP_device_DIODE_91
11741 0 unstable device for PDI1N13S002_device_Device_90
11742 0 unpreserved device PDI1N13S002_device_Device_90
11743 0 unstable device for PDI1N01S002_device_Device_89
11744 0 unpreserved device PDI1N01S002_device_Device_89
11745 0 unstable device for PHDPINB750_device_Device_88
11746 0 unpreserved device PHDPINB750_device_Device_88
11747 0 unstable device for ZD2SM24_device_Device_87
11748 0 unpreserved device ZD2SM24_device_Device_87
11749 0 unstable device for P_NWD_device_Device_86
11750 0 unpreserved device P_NWD_device_Device_86
11751 0 unstable device for NWD_device_DIODE_85
11752 0 unpreserved device NWD_device_DIODE_85
11753 0 unstable device for P_PD_device_Device_84
11754 0 unpreserved device P_PD_device_Device_84
11755 0 unstable device for PD_device_DIODE_83
11756 0 unpreserved device PD_device_DIODE_83
11757 0 unstable device for P_ND_device_Device_82
11758 0 unpreserved device P_ND_device_Device_82
11759 0 unstable device for ND_device_DIODE_81
11760 0 unpreserved device ND_device_DIODE_81
11761 0 unstable device for CVARIM_device_Device_80
11762 0 unpreserved device CVARIM_device_Device_80
11763 0 unstable device for CVARM_device_Device_79
11764 0 unpreserved device CVARM_device_Device_79
11765 0 unstable device for CVART_device_Device_78
11766 0 unpreserved device CVART_device_Device_78
11767 0 unstable device for PROBE_device_Device_77
11768 0 unpreserved device PROBE_device_Device_77
11769 0 unstable device for CMIM20_device_Device_76
11770 0 unpreserved device CMIM20_device_Device_76
11771 0 unstable device for CMIM_device_Device_75
11772 0 unpreserved device CMIM_device_Device_75
11773 0 unstable device for CPM_device_CAP_74
11774 0 unpreserved device CPM_device_CAP_74
11775 0 unstable device for CWPM_device_CAP_73
11776 0 unpreserved device CWPM_device_CAP_73
11777 0 unstable device for CPOLY_NTUB_device_CAP_72
11778 0 unpreserved device CPOLY_NTUB_device_CAP_72
11779 0 unstable device for CPOLY_PSUB_device_CAP_71
11780 0 unpreserved device CPOLY_PSUB_device_CAP_71
11781 0 unstable device for PJFET_device_Device_70
11782 0 unpreserved device PJFET_device_Device_70
11783 0 unstable device for VERTPH_device_BJT_69
11784 0 unpreserved device VERTPH_device_BJT_69
11785 0 unstable device for VERTN1_device_BJT_68
11786 0 unpreserved device VERTN1_device_BJT_68
11787 0 unstable device for VERT10_device_BJT_67
11788 0 unpreserved device VERT10_device_BJT_67
11789 0 unstable device for LAT2_device_Device_66
11790 0 unpreserved device LAT2_device_Device_66
11791 0 unstable device for RVIA_PIN_PDIFF_Device_65
11792 0 unpreserved device RVIA_PIN_PDIFF_Device_65
11793 0 unstable device for RVIA_PIN_NDIFF_Device_64
11794 0 unpreserved device RVIA_PIN_NDIFF_Device_64
11795 0 unstable device for RVIA3_device_RES_63
11796 0 unpreserved device RVIA3_device_RES_63
11797 0 unstable device for RVIA2_device_RES_62
11798 0 unpreserved device RVIA2_device_RES_62
11799 0 unstable device for RVIA1_device_RES_61
11800 0 unpreserved device RVIA1_device_RES_61
11801 0 unstable device for RMET4_device_RES_60
11802 0 unpreserved device RMET4_device_RES_60
11803 0 unstable device for RMET3_device_RES_59
11804 0 unpreserved device RMET3_device_RES_59
11805 0 unstable device for RMET2_device_RES_58
11806 0 unpreserved device RMET2_device_RES_58
11807 0 unstable device for RMET1_device_RES_57
11808 0 unpreserved device RMET1_device_RES_57
11809 0 unstable device for PFUSE_device_RES_56
11810 0 unpreserved device PFUSE_device_RES_56
11811 0 unstable device for RPOLY1_PTUB_device_RES_55
11812 0 unpreserved device RPOLY1_PTUB_device_RES_55
11813 0 unstable device for RPOLY1_NTUB_device_RES_54
11814 0 unpreserved device RPOLY1_NTUB_device_RES_54
11815 0 unstable device for RPOLY1_PSUB_device_RES_53
11816 0 unpreserved device RPOLY1_PSUB_device_RES_53
11817 0 unstable device for RPOLYH_PTUB_device_RES_52
11818 0 unpreserved device RPOLYH_PTUB_device_RES_52
11819 0 unstable device for RPOLYH_NTUB_device_RES_51
11820 0 unpreserved device RPOLYH_NTUB_device_RES_51
11821 0 unstable device for RPOLYH_PSUB_device_RES_50
11822 0 unpreserved device RPOLYH_PSUB_device_RES_50
11823 0 unstable device for RPOLY2PH_NTUB_device_RES_49
11824 0 unpreserved device RPOLY2PH_NTUB_device_RES_49
11825 0 unstable device for RPOLY2PH_PTUB_device_RES_48
11826 0 unpreserved device RPOLY2PH_PTUB_device_RES_48
11827 0 unstable device for RPOLY2PH_PSUB_device_RES_47
11828 0 unpreserved device RPOLY2PH_PSUB_device_RES_47
11829 0 unstable device for RPOLY2P_NTUB_device_Device_46
11830 0 unpreserved device RPOLY2P_NTUB_device_Device_46
11831 0 unstable device for RPOLY2P_PTUB_device_Device_45
11832 0 unpreserved device RPOLY2P_PTUB_device_Device_45
11833 0 unstable device for RPOLY2P_PSUB_device_Device_44
11834 0 unpreserved device RPOLY2P_PSUB_device_Device_44
11835 0 unstable device for RPOLY2_PTUB_device_RES_43
11836 0 unpreserved device RPOLY2_PTUB_device_RES_43
11837 0 unstable device for RPOLY2_NTUB_device_RES_42
11838 0 unpreserved device RPOLY2_NTUB_device_RES_42
11839 0 unstable device for RPOLY2_PSUB_device_RES_41
11840 0 unpreserved device RPOLY2_PSUB_device_RES_41
11841 0 unstable device for RDIFFNR_device_Device_40
11842 0 unpreserved device RDIFFNR_device_Device_40
11843 0 unstable device for RDIFFN_device_RES_39
11844 0 unpreserved device RDIFFN_device_RES_39
11845 0 unstable device for RDIFFPS_device_not_hv_RES_38
11846 0 unpreserved device RDIFFPS_device_not_hv_RES_38
11847 0 unstable device for RDIFFPS_device_hv_RES_37
11848 0 unpreserved device RDIFFPS_device_hv_RES_37
11849 0 unstable device for RDIFFP_device_RES_36
11850 0 unpreserved device RDIFFP_device_RES_36
11851 0 unstable device for RNWELLS_device_RES_35
11852 0 unpreserved device RNWELLS_device_RES_35
11853 0 unstable device for RNWELL_device_RES_34
11854 0 unpreserved device RNWELL_device_RES_34
11855 0 unstable device for RPWELLR_device_RES_33
11856 0 unpreserved device RPWELLR_device_RES_33
11857 0 unstable device for NMOSMH_device_Device_32
11858 0 unpreserved device NMOSMH_device_Device_32
11859 0 unstable device for NMOSH_device_Device_31
11860 0 unpreserved device NMOSH_device_Device_31
11861 0 unstable device for poa_pmos_midox_waffle_4x_Device_30
11862 0 unpreserved device poa_pmos_midox_waffle_4x_Device_30
11863 0 unstable device for poa_pmos_midox_waffle_3x_Device_29
11864 0 unpreserved device poa_pmos_midox_waffle_3x_Device_29
11865 0 unstable device for poa_pmos_midox_waffle_2x_Device_28
11866 0 unpreserved device poa_pmos_midox_waffle_2x_Device_28
11867 0 unstable device for poa_pmos_waffle_4x_Device_27
11868 0 unpreserved device poa_pmos_waffle_4x_Device_27
11869 0 unstable device for poa_pmos_waffle_3x_Device_26
11870 0 unpreserved device poa_pmos_waffle_3x_Device_26
11871 0 unstable device for poa_pmos_waffle_2x_Device_25
11872 0 unpreserved device poa_pmos_waffle_2x_Device_25
11873 0 unstable device for poa_nmos_midox_waffle_4x_Device_24
11874 0 unpreserved device poa_nmos_midox_waffle_4x_Device_24
11875 0 unstable device for poa_nmos_midox_waffle_3x_Device_23
11876 0 unpreserved device poa_nmos_midox_waffle_3x_Device_23
11877 0 unstable device for poa_nmos_midox_waffle_2x_Device_22
11878 0 unpreserved device poa_nmos_midox_waffle_2x_Device_22
11879 0 unstable device for poa_nmos_waffle_4x_Device_21
11880 0 unpreserved device poa_nmos_waffle_4x_Device_21
11881 0 unstable device for poa_nmos_waffle_3x_Device_20
11882 0 unpreserved device poa_nmos_waffle_3x_Device_20
11883 0 unstable device for poa_nmos_waffle_2x_Device_19
11884 0 unpreserved device poa_nmos_waffle_2x_Device_19
11885 0 unstable device for PMOSSL_device_Device_18
11886 0 unpreserved device PMOSSL_device_Device_18
11887 0 unstable device for PMOSSML_device_Device_17
11888 0 unpreserved device PMOSSML_device_Device_17
11889 0 unstable device for PMOSIML_device_Device_16
11890 0 unpreserved device PMOSIML_device_Device_16
11891 0 unstable device for PMOSIM_device_not_hv_MOS_15
11892 0 unpreserved device PMOSIM_device_not_hv_MOS_15
11893 0 unstable device for PMOSIM_device_hv_MOS_14
11894 0 unpreserved device PMOSIM_device_hv_MOS_14
11895 0 unstable device for PMOSIL_device_Device_13
11896 0 unpreserved device PMOSIL_device_Device_13
11897 0 unstable device for PMOSI_device_not_hv_MOS_12
11898 0 unpreserved device PMOSI_device_not_hv_MOS_12
11899 0 unstable device for PMOSI_device_hv_MOS_11
11900 0 unpreserved device PMOSI_device_hv_MOS_11
11901 0 unstable device for NMOSIML_device_Device_10
11902 0 unpreserved device NMOSIML_device_Device_10
11903 0 unstable device for NMOSIM_device_not_hv_Device_9
11904 0 unpreserved device NMOSIM_device_not_hv_Device_9
11905 0 unstable device for NMOSIM_device_hv_Device_8
11906 0 unpreserved device NMOSIM_device_hv_Device_8
11907 0 unstable device for NMOSIL_device_Device_7
11908 0 unpreserved device NMOSIL_device_Device_7
11909 0 unstable device for NMOSI_device_not_hv_Device_6
11910 0 unpreserved device NMOSI_device_not_hv_Device_6
11911 0 unstable device for NMOSI_device_hv_Device_5
11912 0 unpreserved device NMOSI_device_hv_Device_5
11913 0 unstable device for PMOSM_device_MOS_4
11914 0 unpreserved device PMOSM_device_MOS_4
11915 0 unstable device for PMOS_device_MOS_3
11916 0 unpreserved device PMOS_device_MOS_3
11917 0 unstable device for NMOSM_device_MOS_2
11918 0 unpreserved device NMOSM_device_MOS_2
11919 0 unstable device for NMOS_device_MOS_1
11920 0 unpreserved device NMOS_device_MOS_1
