*******************************************************************************
****** inv schematic INV  <vs>  inv layout INV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOS4) MOS                                       1       1
(NMOS4) MOS                                       1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                       1       1           1       1
(PMOS4) MOS                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** BUFX8_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX8_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3       3
(nmosi4 schematic PRIMLIB, _) Cell                3       0*
(NMOSI) MOS                                       0       3*
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3       3           2       2
(PMOSI) MOS                                       3       3           2       2
                                             ------  ------      ------  ------
Total                                             6       6           4       4

*******************************************************************************
****** XOR2X1_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  XOR2X1_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       5       5
(nmosi4 schematic PRIMLIB, _) Cell                5       0*
(NMOSI) MOS                                       0       5*
                                             ------  ------
Total                                            10      10

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       5       5           5       5
(PMOSI) MOS                                       5       5           5       5
                                             ------  ------      ------  ------
Total                                            10      10          10      10

*******************************************************************************
****** AOI22X4_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  AOI22X4_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nmosi4 schematic PRIMLIB, _) Cell                4       0*
(PMOSI) MOS                                       8       4*
(NMOSI) MOS                                       0       4*
                                             ------  ------
Total                                            12       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       4       4           4       4
(PMOSI) MOS                                       8       4*          4       4
                                             ------  ------      ------  ------
Total                                            12       8           8       8

*******************************************************************************
****** HAX3_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  HAX3_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       7       7
(nmosi4 schematic PRIMLIB, _) Cell                7       0*
(NMOSI) MOS                                       0       7*
                                             ------  ------
Total                                            14      14

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       7       7           7       7
(PMOSI) MOS                                       7       7           7       7
                                             ------  ------      ------  ------
Total                                            14      14          14      14

*******************************************************************************
****** BUFX16_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX16_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       6       6
(nmosi4 schematic PRIMLIB, _) Cell                4       0*
(NMOSI) MOS                                       0       4*
                                             ------  ------
Total                                            10      10

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       4       4           2       2
(PMOSI) MOS                                       6       6           2       2
                                             ------  ------      ------  ------
Total                                            10      10           4       4

*******************************************************************************
****** AOI22X3_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  AOI22X3_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(nmosi4 schematic PRIMLIB, _) Cell                4       0*
(PMOSI) MOS                                       4       4
(NMOSI) MOS                                       0       4*
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       4       4           4       4
(PMOSI) MOS                                       4       4           4       4
                                             ------  ------      ------  ------
Total                                             8       8           8       8

*******************************************************************************
****** INVX4_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  INVX4_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       1       1
(nmosi4 schematic PRIMLIB, _) Cell                1       0*
(NMOSI) MOS                                       0       1*
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1       1           1       1
(PMOSI) MOS                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** INVX16_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  INVX16_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       4       4
(nmosi4 schematic PRIMLIB, _) Cell                3       0*
(NMOSI) MOS                                       0       3*
                                             ------  ------
Total                                             7       7

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3       3           1       1
(PMOSI) MOS                                       4       4           1       1
                                             ------  ------      ------  ------
Total                                             7       7           2       2

*******************************************************************************
****** DFX1_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  DFX1_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                      13      13
(nmosi4 schematic PRIMLIB, _) Cell               13       0*
(NMOSI) MOS                                       0      13*
                                             ------  ------
Total                                            26      26

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                      13      13          13      13
(PMOSI) MOS                                      13      13          13      13
                                             ------  ------      ------  ------
Total                                            26      26          26      26

*******************************************************************************
****** XNOR2X2_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  XNOR2X2_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       5       5
(nmosi4 schematic PRIMLIB, _) Cell                5       0*
(NMOSI) MOS                                       0       5*
                                             ------  ------
Total                                            10      10

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       5       5           5       5
(PMOSI) MOS                                       5       5           5       5
                                             ------  ------      ------  ------
Total                                            10      10          10      10

*******************************************************************************
****** NOR2X4_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  NOR2X4_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOSI) MOS                                       2       2
(PMOSI) MOS                                       2       2
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

*******************************************************************************
****** CLKBUFX16_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX16_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       6       5*
(nmosi4 schematic PRIMLIB, _) Cell                4       0*
(NMOSI) MOS                                       0       5*
                                             ------  ------
Total                                            10      10

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       4       5*          2       2
(PMOSI) MOS                                       6       5*          2       2
                                             ------  ------      ------  ------
Total                                            10      10           4       4

*******************************************************************************
****** BUFX12_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX12_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       4       4
(nmosi4 schematic PRIMLIB, _) Cell                3       0*
(NMOSI) MOS                                       0       3*
                                             ------  ------
Total                                             7       7

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3       3           2       2
(PMOSI) MOS                                       4       4           2       2
                                             ------  ------      ------  ------
Total                                             7       7           4       4

*******************************************************************************
****** CLKBUFX8_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX8_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3       3
(nmosi4 schematic PRIMLIB, _) Cell                3       0*
(NMOSI) MOS                                       0       3*
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3       3           2       2
(PMOSI) MOS                                       3       3           2       2
                                             ------  ------      ------  ------
Total                                             6       6           4       4

*******************************************************************************
****** CLKBUFX24_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX24_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       8       8
(nmosi4 schematic PRIMLIB, _) Cell                5       0*
(NMOSI) MOS                                       0       7*
                                             ------  ------
Total                                            13      15

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       5       7*          2       2
(PMOSI) MOS                                       8       8           2       2
                                             ------  ------      ------  ------
Total                                            13      15           4       4

*******************************************************************************
****** DLY1X1_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  DLY1X1_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       5       5
(nmosi4 schematic PRIMLIB, _) Cell                4       0*
(NMOSI) MOS                                       0       4*
                                             ------  ------
Total                                             9       9

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       4       4           4       4
(PMOSI) MOS                                       5       5           4       4
                                             ------  ------      ------  ------
Total                                             9       9           8       8

*******************************************************************************
****** BUFX6_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX6_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3       3
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       2*
                                             ------  ------
Total                                             5       5

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       3       3           2       2
                                             ------  ------      ------  ------
Total                                             5       5           4       4

*******************************************************************************
****** CLKBUFX12_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX12_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       4       4
(nmosi4 schematic PRIMLIB, _) Cell                3       0*
(NMOSI) MOS                                       0       4*
                                             ------  ------
Total                                             7       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3       4*          2       2
(PMOSI) MOS                                       4       4           2       2
                                             ------  ------      ------  ------
Total                                             7       8           4       4

*******************************************************************************
****** BUFX2_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX2_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       2       2
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       2*
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

*******************************************************************************
****** CLKBUFX3_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX3_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       2       2
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       2*
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

*******************************************************************************
****** FILLCAPX16_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  FILLCAPX16_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       1       1
(nmosi4 schematic PRIMLIB, _) Cell                1       0*
(NMOSI) MOS                                       0       1*
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1       1           1       1
(PMOSI) MOS                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** FILLCAPX8_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  FILLCAPX8_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       1       1
(nmosi4 schematic PRIMLIB, _) Cell                1       0*
(NMOSI) MOS                                       0       1*
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1       1           1       1
(PMOSI) MOS                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** FILLCAPX4_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  FILLCAPX4_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       1       1
(nmosi4 schematic PRIMLIB, _) Cell                1       0*
(NMOSI) MOS                                       0       1*
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1       1           1       1
(PMOSI) MOS                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

*******************************************************************************
****** CLKBUFX6_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX6_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3       3
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       3*
                                             ------  ------
Total                                             5       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       3*          2       2
(PMOSI) MOS                                       3       3           2       2
                                             ------  ------      ------  ------
Total                                             5       6           4       4

*******************************************************************************
****** BUFX4_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  BUFX4_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       2       2
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       2*
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

*******************************************************************************
****** CLKBUFX2_DCV_HV cmos_sch CORELIBD_DCV_HV  <vs>  CLKBUFX2_DCV_HV layout CORELIBD_DCV_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       2       2
(nmosi4 schematic PRIMLIB, _) Cell                2       0*
(NMOSI) MOS                                       0       2*
                                             ------  ------
Total                                             4       4

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       2       2           2       2
(PMOSI) MOS                                       2       2           2       2
                                             ------  ------      ------  ------
Total                                             4       4           4       4

*******************************************************************************
****** counter schematic COUNTER  <vs>  counter layout COUNTER
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(BUFX8_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX8_DCV_HV) Cell          1       1
(XOR2X1_DCV_HV cmos_sch CORELIBD_DCV_HV, XOR2X1_DCV_HV) Cell                  1       1
(AOI22X4_DCV_HV cmos_sch CORELIBD_DCV_HV, AOI22X4_DCV_HV) Cell                5       5
(HAX3_DCV_HV cmos_sch CORELIBD_DCV_HV, HAX3_DCV_HV) Cell            6       6
(BUFX16_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX16_DCV_HV) Cell                  2       2
(AOI22X3_DCV_HV cmos_sch CORELIBD_DCV_HV, AOI22X3_DCV_HV) Cell                2       2
(INVX4_DCV_HV cmos_sch CORELIBD_DCV_HV, INVX4_DCV_HV) Cell          1       1
(INVX16_DCV_HV cmos_sch CORELIBD_DCV_HV, INVX16_DCV_HV) Cell                  8       8
(DFX1_DCV_HV cmos_sch CORELIBD_DCV_HV, DFX1_DCV_HV) Cell            8       8
(XNOR2X2_DCV_HV cmos_sch CORELIBD_DCV_HV, XNOR2X2_DCV_HV) Cell                1       1
(NOR2X4_DCV_HV cmos_sch CORELIBD_DCV_HV, NOR2X4_DCV_HV) Cell                  8       8
(CLKBUFX16_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX16_DCV_HV) Cell            1       1
(BUFX12_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX12_DCV_HV) Cell                  7       7
(CLKBUFX8_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX8_DCV_HV) Cell              3       3
(CLKBUFX24_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX24_DCV_HV) Cell            3       3
(DLY1X1_DCV_HV cmos_sch CORELIBD_DCV_HV, DLY1X1_DCV_HV) Cell                  7       7
(BUFX6_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX6_DCV_HV) Cell          2       2
(CLKBUFX12_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX12_DCV_HV) Cell            5       5
(BUFX2_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX2_DCV_HV) Cell          2       2
(CLKBUFX3_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX3_DCV_HV) Cell              1       1
(FILLCAPX16_DCV_HV cmos_sch CORELIBD_DCV_HV, FILLCAPX16_DCV_HV) Cell          1       1
(FILLCAPX8_DCV_HV cmos_sch CORELIBD_DCV_HV, FILLCAPX8_DCV_HV) Cell            4       4
(FILLCAPX4_DCV_HV cmos_sch CORELIBD_DCV_HV, FILLCAPX4_DCV_HV) Cell            4       4
(CLKBUFX6_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX6_DCV_HV) Cell              1       1
(BUFX4_DCV_HV cmos_sch CORELIBD_DCV_HV, BUFX4_DCV_HV) Cell          2       2
(CLKBUFX2_DCV_HV cmos_sch CORELIBD_DCV_HV, CLKBUFX2_DCV_HV) Cell             11      11
(_, FILLCELLX4_DCV_HV layout CORELIBD_DCV_HV) Cell                  0      10*
                                             ------  ------
Total                                            97     107

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(AOI22X3_DCV_HV) Cell                             2       2           2       2
(AOI22X4_DCV_HV) Cell                             5       5           5       5
(BUFX12_DCV_HV) Cell                              7       7           7       7
(BUFX16_DCV_HV) Cell                              2       2           2       2
(BUFX2_DCV_HV) Cell                               2       2           2       2
(BUFX4_DCV_HV) Cell                               2       2           2       2
(BUFX6_DCV_HV) Cell                               2       2           2       2
(BUFX8_DCV_HV) Cell                               1       1           1       1
(CLKBUFX12_DCV_HV) Cell                           5       5           5       5
(CLKBUFX16_DCV_HV) Cell                           1       1           1       1
(CLKBUFX24_DCV_HV) Cell                           3       3           3       3
(CLKBUFX2_DCV_HV) Cell                           11      11          11      11
(CLKBUFX3_DCV_HV) Cell                            1       1           1       1
(CLKBUFX6_DCV_HV) Cell                            1       1           1       1
(CLKBUFX8_DCV_HV) Cell                            3       3           3       3
(DFX1_DCV_HV) Cell                                8       8           8       8
(DLY1X1_DCV_HV) Cell                              7       7           7       7
(FILLCAPX16_DCV_HV) Cell                          1       1           1       1
(FILLCAPX4_DCV_HV) Cell                           4       4           4       4
(FILLCAPX8_DCV_HV) Cell                           4       4           4       4
(HAX3_DCV_HV) Cell                                6       6           6       6
(INVX16_DCV_HV) Cell                              8       8           8       8
(INVX4_DCV_HV) Cell                               1       1           1       1
(NOR2X4_DCV_HV) Cell                              8       8           8       8
(XNOR2X2_DCV_HV) Cell                             1       1           1       1
(XOR2X1_DCV_HV) Cell                              1       1           1       1
                                             ------  ------      ------  ------
Total                                            97      97          97      97

*******************************************************************************
****** core schematic MINIMAL_CORE  <vs>  core layout MINIMAL_CORE
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(inv schematic INV, inv) Cell                     2       2
(counter schematic COUNTER, counter) Cell         1       1
                                             ------  ------
Total                                             3       3

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(counter) Cell                                    1       1           1       1
(inv) Cell                                        2       2           2       2
                                             ------  ------      ------  ------
Total                                             3       3           3       3

*******************************************************************************
****** PWRCUT_DIG_P_DXS_HV cmos_sch IOLIB_HV_4M  <vs>  PWRCUT_DIG_P_DXS_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DN_PS) DIO                                       6       6
(PD_SN) DIO                                       4      26*
                                             ------  ------
Total                                            10      32

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(DN_PS) DIO                                       6       6           6       6
(PD_SN) DIO                                       4      26*          4       4
                                             ------  ------      ------  ------
Total                                            10      32          10      10

*******************************************************************************
****** APRIOP_HV schematic IOLIB_ANA_HV_4M  <vs>  APRIOP_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PD_SN) DIO                                       3      33*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       3       5*
(ND_SP) DIO                                       1       1
(RPOLY2) RES                                      9       9
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
                                             ------  ------
Total                                            17      51

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(RPOLY2) RES                                      9       9           2       2
(DN_PS) DIO                                       3       5*          3       3
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       3      33*          3       3
                                             ------  ------      ------  ------
Total                                            17      50          10      10

*******************************************************************************
****** APRIO200P_HV schematic IOLIB_ANA_HV_4M  <vs>  APRIO200P_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PD_SN) DIO                                       3      33*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       3       5*
(ND_SP) DIO                                       1       1
(RPOLY2) RES                                      9       9
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
                                             ------  ------
Total                                            17      51

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(RPOLY2) RES                                      9       9           3       3
(DN_PS) DIO                                       3       5*          3       3
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       3      33*          3       3
                                             ------  ------      ------  ------
Total                                            17      50          11      11

*******************************************************************************
****** AVDD3ALLP_HV schematic IOLIB_ANA_HV_4M  <vs>  AVDD3ALLP_HV layout IOLIB_ANA_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DP_DN) DIO                                       1       1
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(SHORT) RES                                       2      28*
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             6      42

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       2      28*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             6      41           6       6

###############################################################################
###### AGND3ALLP_HV schematic IOLIB_ANA_HV_4M  <vs>  AGND3ALLP_HV layout IOLIB_ANA_HV_4M
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable devices.
###############################################################################
                     
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DN_PS) DIO                                       1       1
(DP_DN) DIO                                       1       1
(RPOLY1) RES                                      1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(SHORT) RES                                       3      22*
(_, g_padonly layout IOLIB_ANA_HV_4M) Cell        0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             7      36

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       3      22*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             7      35           6       6

*******************************************************************************
****** BU2P_HV cmos_sch IOLIB_HV_4M  <vs>  BU2P_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOSI) MOS                                       3      21*
(NMOSI) MOS                                       3      13*
(RDIFFPS) RES                                     2       2
(g_proto_HV schematic IOLIB_HV_4M, _) Cell        1       0*
(esdnmosi schematic ESDLIB, _) Cell               2       0*
(esdpmosi schematic ESDLIB, _) Cell               2       0*
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
(RPOLY1) RES                                      0       1*
(ND_SP) DIO                                       0       1*
(PD_SN) DIO                                       0       1*
(DP_DN) DIO                                       0       2*
(DN_PS) DIO                                       0       2*
                                             ------  ------
Total                                            13      44

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       5      13*          5       5
(PMOSI) MOS                                       5      21*          5       5
(RDIFFPS) RES                                     2       2           2       2
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       2*          1       1
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                            17      43          17      17

*******************************************************************************
****** ICP_HV cmos_sch IOLIB_HV_4M  <vs>  ICP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(ND_SP) DIO                                       1       1
(PD_SN) DIO                                       1       1
(PMOSI) MOS                                       2      21*
(NMOSI) MOS                                       2      12*
(DP_DN) DIO                                       1       2*
(DN_PS) DIO                                       1       2*
(RDIFFPS) RES                                     2       2
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(esdpmosi schematic ESDLIB, _) Cell               1       0*
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                            13      43

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       3      12*          3       3
(PMOSI) MOS                                       3      21*          3       3
(RDIFFPS) RES                                     2       2           2       2
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       2*          1       1
(DP_DN) DIO                                       1       2*          1       1
(ND_SP) DIO                                       1       1           1       1
(PD_SN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                            13      42          13      13

*******************************************************************************
****** VSUBALLP_HV cmos_sch IOLIB_HV_4M  <vs>  VSUBALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOSI) MOS                                       1      10*
(DP_DN) DIO                                       1       1
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                             4      14

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             4      13           4       4

*******************************************************************************
****** VDD3ALLP_HV cmos_sch IOLIB_HV_4M  <vs>  VDD3ALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(DP_DN) DIO                                       1       1
(NMOSI) MOS                                       1      10*
(DN_PS) DIO                                       1       1
(RPOLY1) RES                                      1       1
(SHORT) RES                                       2      28*
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
                                             ------  ------
Total                                             6      42

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       2      28*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             6      41           6       6

*******************************************************************************
****** GND3ALLP_HV cmos_sch IOLIB_HV_4M  <vs>  GND3ALLP_HV layout IOLIB_HV_4M
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(SHORT) RES                                       3      22*
(DN_PS) DIO                                       1       1
(DP_DN) DIO                                       1       1
(esdnmosi schematic ESDLIB, _) Cell               1       0*
(RPOLY1) RES                                      1       1
(_, g_padonly layout IOLIB_HV_4M) Cell            0       1*
(NMOSI) MOS                                       0      10*
                                             ------  ------
Total                                             7      36

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       3      22*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                             7      35           6       6

*******************************************************************************
****** ioring schematic MINIMAL_IO_HV  <vs>  ioring layout MINIMAL_IO_HV
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PWRCUT_DIG_P_DXS_HV cmos_sch IOLIB_HV_4M, PWRCUT_DIG_P_DXS_HV) Cell          2       2
(APRIOP_HV schematic IOLIB_ANA_HV_4M, APRIOP_HV) Cell               2       2
(APRIO200P_HV schematic IOLIB_ANA_HV_4M, APRIO200P_HV) Cell         1       1
(AVDD3ALLP_HV schematic IOLIB_ANA_HV_4M, AVDD3ALLP_HV) Cell         1       1
(AGND3ALLP_HV schematic IOLIB_ANA_HV_4M, AGND3ALLP_HV) Cell         1       1
(BU2P_HV cmos_sch IOLIB_HV_4M, BU2P_HV) Cell              3       3
(ICP_HV cmos_sch IOLIB_HV_4M, ICP_HV) Cell        3       3
(VSUBALLP_HV cmos_sch IOLIB_HV_4M, VSUBALLP_HV) Cell                1       1
(VDD3ALLP_HV cmos_sch IOLIB_HV_4M, VDD3ALLP_HV) Cell                1       1
(GND3ALLP_HV cmos_sch IOLIB_HV_4M, GND3ALLP_HV) Cell                1       1
(_, CORNERP_HV layout IOLIB_HV_4M) Cell           0       4*
(_, PERI_SPACER_100_P_HV layout IOLIB_HV_4M) Cell         0      13*
(_, PERI_SPACER_10_P_HV layout IOLIB_HV_4M) Cell          0       1*
(_, PERI_SPACER_20_P_HV layout IOLIB_HV_4M) Cell          0       1*
(_, PERI_SPACER_2_P_HV layout IOLIB_HV_4M) Cell           0       8*
(_, PERI_SPACER_50_P_HV layout IOLIB_HV_4M) Cell          0      13*
                                             ------  ------
Total                                            16      56

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(APRIO200P_HV) Cell                               1       1           1       1
(APRIOP_HV) Cell                                  2       2           2       2
(AVDD3ALLP_HV) Cell                               1       1           1       1
(BU2P_HV) Cell                                    3       3           3       3
(GND3ALLP_HV) Cell                                1       1           1       1
(ICP_HV) Cell                                     3       3           3       3
(PWRCUT_DIG_P_DXS_HV) Cell                        2       2           2       2
(VDD3ALLP_HV) Cell                                1       1           1       1
(VSUBALLP_HV) Cell                                1       1           1       1
(NMOSI) MOS                                       1      10*          1       1
(RPOLY1) RES                                      1       1           1       1
(SHORT) RES                                       3      22*          2       2
(DN_PS) DIO                                       1       1           1       1
(DP_DN) DIO                                       1       1           1       1
                                             ------  ------      ------  ------
Total                                            22      50          21      21

*******************************************************************************
****** top schematic MINIMAL_TOP  <vs>  top layout MINIMAL_TOP
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(core schematic MINIMAL_CORE, core) Cell          1       1
(ioring schematic MINIMAL_IO_HV, ioring) Cell             1       1
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(core) Cell                                       1       1           1       1
(ioring) Cell                                     1       1           1       1
                                             ------  ------      ------  ------
Total                                             2       2           2       2

Schematic and Layout Match
